.include <../../../Makefile.cfgparam>

SUBDIR_${CONFIG_E1000G}		=  e1000g
SUBDIR_${CONFIG_IGB}		+= igb
SUBDIR_${CONFIG_IXGBE}		+= ixgbe
SUBDIR_${CONFIG_VIRTIO_NET}	+= vioif

SUBDIR = ${SUBDIR_y}

.include <bsd.subdir.mk>
