.include <../../../Makefile.cfgparam>

SUBDIR_${CONFIG_BGE}		=  bge
SUBDIR_${CONFIG_BNXE}		+= bnxe
SUBDIR_${CONFIG_CHXGE}		+= chxge
SUBDIR_${CONFIG_E1000G}		+= e1000g
SUBDIR_${CONFIG_HXGE}		+= hxge
SUBDIR_${CONFIG_I40E}		+= i40e
SUBDIR_${CONFIG_IGB}		+= igb
SUBDIR_${CONFIG_IXGBE}		+= ixgbe
SUBDIR_${CONFIG_MYRI10GE}	+= myri10ge
SUBDIR_${CONFIG_NGE}		+= nge
SUBDIR_${CONFIG_NXGE}		+= nxge
SUBDIR_${CONFIG_SFXGE}		+= sfxge
SUBDIR_${CONFIG_VIRTIO_NET}	+= vioif
SUBDIR_${CONFIG_YGE}		+= yge

SUBDIR = ${SUBDIR_y} \
	 wifi

.include <bsd.subdir.mk>
