MAN = __fbufsize.3c \
      _longjmp.3c \
      _stack_grow.3c \
      a64l.3c \
      abort.3c \
      abs.3c \
      addsev.3c \
      addseverity.3c \
      aio_cancel.3c \
      aio_error.3c \
      aio_fsync.3c \
      aio_read.3c \
      aio_return.3c \
      aio_suspend.3c \
      aio_waitn.3c \
      aio_write.3c \
      aiocancel.3c \
      aioread.3c \
      aiowait.3c \
      aligned_alloc.3c \
      arc4random.3c \
      assert.3c \
      atexit.3c \
      atomic_add.3c \
      atomic_and.3c \
      atomic_bits.3c \
      atomic_cas.3c \
      atomic_dec.3c \
      atomic_inc.3c \
      atomic_ops.3c \
      atomic_or.3c \
      atomic_swap.3c \
      attropen.3c \
      basename.3c \
      bsd_signal.3c \
      bsearch.3c \
      bstring.3c \
      btowc.3c \
      call_once.3c \
      catgets.3c \
      catopen.3c \
      cfgetispeed.3c \
      cfsetispeed.3c \
      clearenv.3c \
      clock.3c \
      clock_nanosleep.3c \
      clock_settime.3c \
      closedir.3c \
      closefrom.3c \
      cnd.3c \
      cond_init.3c \
      confstr.3c \
      crypt.3c \
      crypt_genhash_impl.3c \
      crypt_gensalt.3c \
      crypt_gensalt_impl.3c \
      cset.3c \
      ctermid.3c \
      ctime.3c \
      ctype.3c \
      cuserid.3c \
      daemon.3c \
      decimal_to_floating.3c \
      difftime.3c \
      directio.3c \
      dirfd.3c \
      dirname.3c \
      div.3c \
      dladdr.3c \
      dlclose.3c \
      dldump.3c \
      dlerror.3c \
      dlinfo.3c \
      dlopen.3c \
      dlsym.3c \
      door_bind.3c \
      door_call.3c \
      door_create.3c \
      door_cred.3c \
      door_getparam.3c \
      door_info.3c \
      door_return.3c \
      door_revoke.3c \
      door_server_create.3c \
      door_ucred.3c \
      drand48.3c \
      dup2.3c \
      econvert.3c \
      ecvt.3c \
      enable_extended_FILE_stdio.3c \
      encrypt.3c \
      end.3c \
      endian.3c \
      epoll_create.3c \
      epoll_ctl.3c \
      epoll_wait.3c \
      euclen.3c \
      eventfd.3c \
      exit.3c \
      fattach.3c \
      fclose.3c \
      fcloseall.3c \
      fdatasync.3c \
      fdetach.3c \
      fdopen.3c \
      ferror.3c \
      fflush.3c \
      ffs.3c \
      fgetattr.3c \
      fgetc.3c \
      fgetpos.3c \
      fgetwc.3c \
      floating_to_decimal.3c \
      flock.3c \
      flockfile.3c \
      fmtmsg.3c \
      fnmatch.3c \
      fopen.3c \
      fpgetround.3c \
      fputc.3c \
      fputwc.3c \
      fputws.3c \
      fread.3c \
      freopen.3c \
      fseek.3c \
      fsetpos.3c \
      fsync.3c \
      ftell.3c \
      ftime.3c \
      ftok.3c \
      ftw.3c \
      fwide.3c \
      fwprintf.3c \
      fwrite.3c \
      fwscanf.3c \
      getcpuid.3c \
      getcwd.3c \
      getdate.3c \
      getdtablesize.3c \
      getentropy.3c \
      getenv.3c \
      getexecname.3c \
      getgrnam.3c \
      gethostid.3c \
      gethostname.3c \
      gethrtime.3c \
      getline.3c \
      getloadavg.3c \
      getlogin.3c \
      getmntent.3c \
      getnetgrent.3c \
      get_nprocs.3c \
      getopt.3c \
      getpagesize.3c \
      getpagesizes.3c \
      getpass.3c \
      getpeerucred.3c \
      getpriority.3c \
      getprogname.3c \
      getpw.3c \
      getpwnam.3c \
      getrusage.3c \
      gets.3c \
      getspnam.3c \
      getsubopt.3c \
      gettext.3c \
      gettimeofday.3c \
      gettxt.3c \
      getusershell.3c \
      getutent.3c \
      getutxent.3c \
      getvfsent.3c \
      getwc.3c \
      getwchar.3c \
      getwd.3c \
      getwidth.3c \
      getws.3c \
      getzoneid.3c \
      glob.3c \
      grantpt.3c \
      hsearch.3c \
      iconv.3c \
      iconv_close.3c \
      iconv_open.3c \
      imaxabs.3c \
      imaxdiv.3c \
      index.3c \
      initgroups.3c \
      insque.3c \
      isaexec.3c \
      isastream.3c \
      isatty.3c \
      isnand.3c \
      iswalpha.3c \
      iswctype.3c \
      killpg.3c \
      lckpwdf.3c \
      lfmt.3c \
      lio_listio.3c \
      localeconv.3c \
      lockf.3c \
      lsearch.3c \
      madvise.3c \
      makecontext.3c \
      makedev.3c \
      mblen.3c \
      mbrlen.3c \
      mbrtowc.3c \
      mbsinit.3c \
      mbsrtowcs.3c \
      mbtowc.3c \
      membar_ops.3c \
      memory.3c \
      mkfifo.3c \
      mkstemp.3c \
      mktemp.3c \
      mktime.3c \
      mlock.3c \
      mlockall.3c \
      monitor.3c \
      mq_close.3c \
      mq_getattr.3c \
      mq_notify.3c \
      mq_open.3c \
      mq_receive.3c \
      mq_send.3c \
      mq_setattr.3c \
      mq_unlink.3c \
      msync.3c \
      mtx.3c \
      mutex_init.3c \
      nanosleep.3c \
      ndbm.3c \
      newlocale.3c \
      nl_langinfo.3c \
      offsetof.3c \
      opendir.3c \
      perror.3c \
      pfmt.3c \
      plock.3c \
      popen.3c \
      port_alert.3c \
      port_associate.3c \
      port_create.3c \
      port_get.3c \
      port_send.3c \
      posix_fadvise.3c \
      posix_fallocate.3c \
      posix_madvise.3c \
      posix_openpt.3c \
      posix_spawn.3c \
      posix_spawn_file_actions_addclose.3c \
      posix_spawn_file_actions_addclosefrom_np.3c \
      posix_spawn_file_actions_adddup2.3c \
      posix_spawn_file_actions_destroy.3c \
      posix_spawn_pipe_np.3c \
      posix_spawnattr_destroy.3c \
      posix_spawnattr_getflags.3c \
      posix_spawnattr_getpgroup.3c \
      posix_spawnattr_getschedparam.3c \
      posix_spawnattr_getschedpolicy.3c \
      posix_spawnattr_getsigdefault.3c \
      posix_spawnattr_getsigignore_np.3c \
      posix_spawnattr_getsigmask.3c \
      printf.3c \
      priv_addset.3c \
      priv_set.3c \
      priv_str_to_set.3c \
      pset_getloadavg.3c \
      psignal.3c \
      pthread_atfork.3c \
      pthread_attr_getdetachstate.3c \
      pthread_attr_getguardsize.3c \
      pthread_attr_getinheritsched.3c \
      pthread_attr_getschedparam.3c \
      pthread_attr_getschedpolicy.3c \
      pthread_attr_getscope.3c \
      pthread_attr_getstack.3c \
      pthread_attr_getstackaddr.3c \
      pthread_attr_getstacksize.3c \
      pthread_attr_get_np.3c \
      pthread_attr_init.3c \
      pthread_barrier_destroy.3c \
      pthread_barrier_wait.3c \
      pthread_barrierattr_destroy.3c \
      pthread_barrierattr_getpshared.3c \
      pthread_cancel.3c \
      pthread_cleanup_pop.3c \
      pthread_cleanup_push.3c \
      pthread_cond_init.3c \
      pthread_cond_signal.3c \
      pthread_cond_wait.3c \
      pthread_condattr_getclock.3c \
      pthread_condattr_getpshared.3c \
      pthread_condattr_init.3c \
      pthread_create.3c \
      pthread_detach.3c \
      pthread_equal.3c \
      pthread_exit.3c \
      pthread_getconcurrency.3c \
      pthread_getschedparam.3c \
      pthread_getspecific.3c \
      pthread_join.3c \
      pthread_key_create.3c \
      pthread_key_delete.3c \
      pthread_kill.3c \
      pthread_mutex_consistent.3c \
      pthread_mutex_getprioceiling.3c \
      pthread_mutex_init.3c \
      pthread_mutex_lock.3c \
      pthread_mutex_timedlock.3c \
      pthread_mutexattr_getprioceiling.3c \
      pthread_mutexattr_getprotocol.3c \
      pthread_mutexattr_getpshared.3c \
      pthread_mutexattr_getrobust.3c \
      pthread_mutexattr_gettype.3c \
      pthread_mutexattr_init.3c \
      pthread_once.3c \
      pthread_rwlock_init.3c \
      pthread_rwlock_rdlock.3c \
      pthread_rwlock_timedrdlock.3c \
      pthread_rwlock_timedwrlock.3c \
      pthread_rwlock_unlock.3c \
      pthread_rwlock_wrlock.3c \
      pthread_rwlockattr_getpshared.3c \
      pthread_rwlockattr_init.3c \
      pthread_self.3c \
      pthread_setcancelstate.3c \
      pthread_setcanceltype.3c \
      pthread_setschedprio.3c \
      pthread_sigmask.3c \
      pthread_spin_destroy.3c \
      pthread_spin_lock.3c \
      pthread_spin_unlock.3c \
      pthread_testcancel.3c \
      ptrace.3c \
      ptsname.3c \
      putenv.3c \
      putpwent.3c \
      puts.3c \
      putspent.3c \
      putws.3c \
      qsort.3c \
      quick_exit.3c \
      raise.3c \
      rand.3c \
      random.3c \
      rctl_walk.3c \
      rctlblk_set_value.3c \
      re_comp.3c \
      realpath.3c \
      reboot.3c \
      regcmp.3c \
      regcomp.3c \
      remove.3c \
      rewind.3c \
      rewinddir.3c \
      rwlock.3c \
      scandir.3c \
      scanf.3c \
      sched_get_priority_max.3c \
      sched_getparam.3c \
      sched_getscheduler.3c \
      sched_rr_get_interval.3c \
      sched_setparam.3c \
      sched_setscheduler.3c \
      sched_yield.3c \
      schedctl_init.3c \
      seekdir.3c \
      select.3c \
      sem_close.3c \
      sem_destroy.3c \
      sem_getvalue.3c \
      sem_init.3c \
      sem_open.3c \
      sem_post.3c \
      sem_timedwait.3c \
      sem_unlink.3c \
      sem_wait.3c \
      semaphore.3c \
      setbuf.3c \
      setbuffer.3c \
      setcat.3c \
      setenv.3c \
      setjmp.3c \
      setkey.3c \
      setlocale.3c \
      shm_open.3c \
      shm_unlink.3c \
      sigfpe.3c \
      siginterrupt.3c \
      signal.3c \
      signalfd.3c \
      sigqueue.3c \
      sigsetops.3c \
      sigstack.3c \
      sigwaitinfo.3c \
      sleep.3c \
      ssignal.3c \
      smt_pause.3c \
      stack_getbounds.3c \
      stack_inbounds.3c \
      stack_setbounds.3c \
      stack_violation.3c \
      stdio.3c \
      str2sig.3c \
      strcoll.3c \
      strerror.3c \
      strfmon.3c \
      strftime.3c \
      string.3c \
      string_to_decimal.3c \
      strptime.3c \
      strsignal.3c \
      strtod.3c \
      strtoimax.3c \
      strtol.3c \
      strtoul.3c \
      strtows.3c \
      strxfrm.3c \
      swab.3c \
      sync_instruction_memory.3c \
      sysconf.3c \
      syslog.3c \
      system.3c \
      tcdrain.3c \
      tcflow.3c \
      tcflush.3c \
      tcgetattr.3c \
      tcgetpgrp.3c \
      tcgetsid.3c \
      tcsendbreak.3c \
      tcsetattr.3c \
      tcsetpgrp.3c \
      tell.3c \
      telldir.3c \
      termios.3c \
      thr_create.3c \
      thr_exit.3c \
      thr_getconcurrency.3c \
      thr_getprio.3c \
      thr_join.3c \
      thr_keycreate.3c \
      thr_kill.3c \
      thr_main.3c \
      thr_min_stack.3c \
      thr_self.3c \
      thr_sigsetmask.3c \
      thr_stksegment.3c \
      thr_suspend.3c \
      thr_yield.3c \
      thrd_create.3c \
      thrd_current.3c \
      thrd_detach.3c \
      thrd_equal.3c \
      thrd_exit.3c \
      thrd_join.3c \
      thrd_yield.3c \
      timer_create.3c \
      timer_delete.3c \
      timer_settime.3c \
      timeradd.3c \
      timerfd_create.3c \
      timespec_get.3c \
      tmpfile.3c \
      tmpnam.3c \
      toascii.3c \
      tolower.3c \
      toupper.3c \
      towlower.3c \
      towupper.3c \
      truncate.3c \
      tsearch.3c \
      tss.3c \
      ttyname.3c \
      ttyslot.3c \
      u8_strcmp.3c \
      u8_textprep_str.3c \
      u8_validate.3c \
      ualarm.3c \
      uconv_u16tou32.3c \
      ucred.3c \
      ungetc.3c \
      ungetwc.3c \
      unlockpt.3c \
      unsetenv.3c \
      uselocale.3c \
      usleep.3c \
      vfwprintf.3c \
      vlfmt.3c \
      vpfmt.3c \
      vprintf.3c \
      vsyslog.3c \
      wait.3c \
      wait3.3c \
      waitpid.3c \
      walkcontext.3c \
      wcpcpy.3c \
      wcrtomb.3c \
      wcscasecmp.3c \
      wcscoll.3c \
      wcsdup.3c \
      wcslen.3c \
      wcsftime.3c \
      wcsrtombs.3c \
      wcsstr.3c \
      wcstod.3c \
      wcstoimax.3c \
      wcstol.3c \
      wcstoul.3c \
      wcstring.3c \
      wcswidth.3c \
      wcsxfrm.3c \
      wctob.3c \
      wctomb.3c \
      wctrans.3c \
      wctype.3c \
      wcwidth.3c \
      wmemchr.3c \
      wmemcmp.3c \
      wmemcpy.3c \
      wmemmove.3c \
      wmemset.3c \
      wordexp.3c \
      wsprintf.3c \
      wsscanf.3c \
      wstring.3c \

MLINKS+=	__fbufsize.3c __flbf.3c
MLINKS+=	__fbufsize.3c __fpending.3c
MLINKS+=	__fbufsize.3c __fpurge.3c
MLINKS+=	__fbufsize.3c __freadable.3c
MLINKS+=	__fbufsize.3c __freading.3c
MLINKS+=	__fbufsize.3c __fsetlocking.3c
MLINKS+=	__fbufsize.3c __fwritable.3c
MLINKS+=	__fbufsize.3c __fwriting.3c
MLINKS+=	__fbufsize.3c _flushlbf.3c
MLINKS+=	_longjmp.3c _setjmp.3c
MLINKS+=	a64l.3c l64a.3c
MLINKS+=	abs.3c labs.3c
MLINKS+=	abs.3c llabs.3c
MLINKS+=	aioread.3c aiowrite.3c
MLINKS+=	arc4random.3c arc4random_buf.3c
MLINKS+=	arc4random.3c arc4random_uniform.3c
MLINKS+=	quick_exit.3c at_quick_exit.3c
MLINKS+=	atomic_add.3c atomic_add_16.3c
MLINKS+=	atomic_add.3c atomic_add_16_nv.3c
MLINKS+=	atomic_add.3c atomic_add_32.3c
MLINKS+=	atomic_add.3c atomic_add_32_nv.3c
MLINKS+=	atomic_add.3c atomic_add_64.3c
MLINKS+=	atomic_add.3c atomic_add_64_nv.3c
MLINKS+=	atomic_add.3c atomic_add_8.3c
MLINKS+=	atomic_add.3c atomic_add_8_nv.3c
MLINKS+=	atomic_add.3c atomic_add_char.3c
MLINKS+=	atomic_add.3c atomic_add_char_nv.3c
MLINKS+=	atomic_add.3c atomic_add_int.3c
MLINKS+=	atomic_add.3c atomic_add_int_nv.3c
MLINKS+=	atomic_add.3c atomic_add_long.3c
MLINKS+=	atomic_add.3c atomic_add_long_nv.3c
MLINKS+=	atomic_add.3c atomic_add_ptr.3c
MLINKS+=	atomic_add.3c atomic_add_ptr_nv.3c
MLINKS+=	atomic_add.3c atomic_add_short.3c
MLINKS+=	atomic_add.3c atomic_add_short_nv.3c
MLINKS+=	atomic_and.3c atomic_and_16.3c
MLINKS+=	atomic_and.3c atomic_and_16_nv.3c
MLINKS+=	atomic_and.3c atomic_and_32.3c
MLINKS+=	atomic_and.3c atomic_and_32_nv.3c
MLINKS+=	atomic_and.3c atomic_and_64.3c
MLINKS+=	atomic_and.3c atomic_and_64_nv.3c
MLINKS+=	atomic_and.3c atomic_and_8.3c
MLINKS+=	atomic_and.3c atomic_and_8_nv.3c
MLINKS+=	atomic_and.3c atomic_and_uchar.3c
MLINKS+=	atomic_and.3c atomic_and_uchar_nv.3c
MLINKS+=	atomic_and.3c atomic_and_uint.3c
MLINKS+=	atomic_and.3c atomic_and_uint_nv.3c
MLINKS+=	atomic_and.3c atomic_and_ulong.3c
MLINKS+=	atomic_and.3c atomic_and_ulong_nv.3c
MLINKS+=	atomic_and.3c atomic_and_ushort.3c
MLINKS+=	atomic_and.3c atomic_and_ushort_nv.3c
MLINKS+=	atomic_bits.3c atomic_clear_long_excl.3c
MLINKS+=	atomic_bits.3c atomic_set_long_excl.3c
MLINKS+=	atomic_cas.3c atomic_cas_16.3c
MLINKS+=	atomic_cas.3c atomic_cas_32.3c
MLINKS+=	atomic_cas.3c atomic_cas_64.3c
MLINKS+=	atomic_cas.3c atomic_cas_8.3c
MLINKS+=	atomic_cas.3c atomic_cas_ptr.3c
MLINKS+=	atomic_cas.3c atomic_cas_uchar.3c
MLINKS+=	atomic_cas.3c atomic_cas_uint.3c
MLINKS+=	atomic_cas.3c atomic_cas_ulong.3c
MLINKS+=	atomic_cas.3c atomic_cas_ushort.3c
MLINKS+=	atomic_dec.3c atomic_dec_16.3c
MLINKS+=	atomic_dec.3c atomic_dec_16_nv.3c
MLINKS+=	atomic_dec.3c atomic_dec_32.3c
MLINKS+=	atomic_dec.3c atomic_dec_32_nv.3c
MLINKS+=	atomic_dec.3c atomic_dec_64.3c
MLINKS+=	atomic_dec.3c atomic_dec_64_nv.3c
MLINKS+=	atomic_dec.3c atomic_dec_8.3c
MLINKS+=	atomic_dec.3c atomic_dec_8_nv.3c
MLINKS+=	atomic_dec.3c atomic_dec_ptr.3c
MLINKS+=	atomic_dec.3c atomic_dec_ptr_nv.3c
MLINKS+=	atomic_dec.3c atomic_dec_uchar.3c
MLINKS+=	atomic_dec.3c atomic_dec_uchar_nv.3c
MLINKS+=	atomic_dec.3c atomic_dec_uint.3c
MLINKS+=	atomic_dec.3c atomic_dec_uint_nv.3c
MLINKS+=	atomic_dec.3c atomic_dec_ulong.3c
MLINKS+=	atomic_dec.3c atomic_dec_ulong_nv.3c
MLINKS+=	atomic_dec.3c atomic_dec_ushort.3c
MLINKS+=	atomic_dec.3c atomic_dec_ushort_nv.3c
MLINKS+=	atomic_inc.3c atomic_inc_16.3c
MLINKS+=	atomic_inc.3c atomic_inc_16_nv.3c
MLINKS+=	atomic_inc.3c atomic_inc_32.3c
MLINKS+=	atomic_inc.3c atomic_inc_32_nv.3c
MLINKS+=	atomic_inc.3c atomic_inc_64.3c
MLINKS+=	atomic_inc.3c atomic_inc_64_nv.3c
MLINKS+=	atomic_inc.3c atomic_inc_8.3c
MLINKS+=	atomic_inc.3c atomic_inc_8_nv.3c
MLINKS+=	atomic_inc.3c atomic_inc_ptr.3c
MLINKS+=	atomic_inc.3c atomic_inc_ptr_nv.3c
MLINKS+=	atomic_inc.3c atomic_inc_uchar.3c
MLINKS+=	atomic_inc.3c atomic_inc_uchar_nv.3c
MLINKS+=	atomic_inc.3c atomic_inc_uint.3c
MLINKS+=	atomic_inc.3c atomic_inc_uint_nv.3c
MLINKS+=	atomic_inc.3c atomic_inc_ulong.3c
MLINKS+=	atomic_inc.3c atomic_inc_ulong_nv.3c
MLINKS+=	atomic_inc.3c atomic_inc_ushort.3c
MLINKS+=	atomic_inc.3c atomic_inc_ushort_nv.3c
MLINKS+=	atomic_or.3c atomic_or_16.3c
MLINKS+=	atomic_or.3c atomic_or_16_nv.3c
MLINKS+=	atomic_or.3c atomic_or_32.3c
MLINKS+=	atomic_or.3c atomic_or_32_nv.3c
MLINKS+=	atomic_or.3c atomic_or_64.3c
MLINKS+=	atomic_or.3c atomic_or_64_nv.3c
MLINKS+=	atomic_or.3c atomic_or_8.3c
MLINKS+=	atomic_or.3c atomic_or_8_nv.3c
MLINKS+=	atomic_or.3c atomic_or_uchar.3c
MLINKS+=	atomic_or.3c atomic_or_uchar_nv.3c
MLINKS+=	atomic_or.3c atomic_or_uint.3c
MLINKS+=	atomic_or.3c atomic_or_uint_nv.3c
MLINKS+=	atomic_or.3c atomic_or_ulong.3c
MLINKS+=	atomic_or.3c atomic_or_ulong_nv.3c
MLINKS+=	atomic_or.3c atomic_or_ushort.3c
MLINKS+=	atomic_or.3c atomic_or_ushort_nv.3c
MLINKS+=	atomic_swap.3c atomic_swap_16.3c
MLINKS+=	atomic_swap.3c atomic_swap_32.3c
MLINKS+=	atomic_swap.3c atomic_swap_64.3c
MLINKS+=	atomic_swap.3c atomic_swap_8.3c
MLINKS+=	atomic_swap.3c atomic_swap_ptr.3c
MLINKS+=	atomic_swap.3c atomic_swap_uchar.3c
MLINKS+=	atomic_swap.3c atomic_swap_uint.3c
MLINKS+=	atomic_swap.3c atomic_swap_ulong.3c
MLINKS+=	atomic_swap.3c atomic_swap_ushort.3c
MLINKS+=	bstring.3c bcmp.3c
MLINKS+=	bstring.3c bcopy.3c
MLINKS+=	bstring.3c bzero.3c
MLINKS+=	bstring.3c explicit_bzero.3c
MLINKS+=	btowc.3c btowc_l.3c
MLINKS+=	realpath.3c canonicalize_file_name.3c
MLINKS+=	catopen.3c catclose.3c
MLINKS+=	cfgetispeed.3c cfgetospeed.3c
MLINKS+=	cfsetispeed.3c cfsetospeed.3c
MLINKS+=	clock_settime.3c clock_getres.3c
MLINKS+=	clock_settime.3c clock_gettime.3c
MLINKS+=	closefrom.3c fdwalk.3c
MLINKS+=	cnd.3c cnd_broadcast.3c
MLINKS+=	cnd.3c cnd_destroy.3c
MLINKS+=	cnd.3c cnd_init.3c
MLINKS+=	cnd.3c cnd_signal.3c
MLINKS+=	cnd.3c cnd_timedwait.3c
MLINKS+=	cnd.3c cnd_wait.3c
MLINKS+=	cond_init.3c cond_broadcast.3c
MLINKS+=	cond_init.3c cond_destroy.3c
MLINKS+=	cond_init.3c cond_reltimedwait.3c
MLINKS+=	cond_init.3c cond_signal.3c
MLINKS+=	cond_init.3c cond_timedwait.3c
MLINKS+=	cond_init.3c cond_wait.3c
MLINKS+=	cset.3c csetcol.3c
MLINKS+=	cset.3c csetlen.3c
MLINKS+=	cset.3c csetno.3c
MLINKS+=	cset.3c wcsetno.3c
MLINKS+=	ctermid.3c ctermid_r.3c
MLINKS+=	ctime.3c asctime.3c
MLINKS+=	ctime.3c asctime_r.3c
MLINKS+=	ctime.3c ctime_r.3c
MLINKS+=	ctime.3c gmtime.3c
MLINKS+=	ctime.3c gmtime_r.3c
MLINKS+=	ctime.3c localtime.3c
MLINKS+=	ctime.3c localtime_r.3c
MLINKS+=	ctime.3c tzset.3c
MLINKS+=	ctype.3c isalnum.3c
MLINKS+=	ctype.3c isalnum_l.3c
MLINKS+=	ctype.3c isalpha.3c
MLINKS+=	ctype.3c isalpha_l.3c
MLINKS+=	ctype.3c isascii.3c
MLINKS+=	ctype.3c isblank.3c
MLINKS+=	ctype.3c isblank_l.3c
MLINKS+=	ctype.3c iscntrl.3c
MLINKS+=	ctype.3c iscntrl_l.3c
MLINKS+=	ctype.3c isdigit.3c
MLINKS+=	ctype.3c isdigit_l.3c
MLINKS+=	ctype.3c isgraph.3c
MLINKS+=	ctype.3c isgraph_l.3c
MLINKS+=	ctype.3c islower.3c
MLINKS+=	ctype.3c islower_l.3c
MLINKS+=	ctype.3c isprint.3c
MLINKS+=	ctype.3c isprint_l.3c
MLINKS+=	ctype.3c ispunct.3c
MLINKS+=	ctype.3c ispunct_l.3c
MLINKS+=	ctype.3c isspace.3c
MLINKS+=	ctype.3c isspace_l.3c
MLINKS+=	ctype.3c isupper.3c
MLINKS+=	ctype.3c isupper_l.3c
MLINKS+=	ctype.3c isxdigit.3c
MLINKS+=	ctype.3c isxdigit_l.3c
MLINKS+=	decimal_to_floating.3c decimal_to_double.3c
MLINKS+=	decimal_to_floating.3c decimal_to_extended.3c
MLINKS+=	decimal_to_floating.3c decimal_to_quadruple.3c
MLINKS+=	decimal_to_floating.3c decimal_to_single.3c
MLINKS+=	div.3c ldiv.3c
MLINKS+=	div.3c lldiv.3c
MLINKS+=	dladdr.3c dladdr1.3c
MLINKS+=	dlopen.3c dlmopen.3c
MLINKS+=	door_bind.3c door_unbind.3c
MLINKS+=	door_getparam.3c door_setparam.3c
MLINKS+=	drand48.3c erand48.3c
MLINKS+=	drand48.3c jrand48.3c
MLINKS+=	drand48.3c lcong48.3c
MLINKS+=	drand48.3c lrand48.3c
MLINKS+=	drand48.3c mrand48.3c
MLINKS+=	drand48.3c nrand48.3c
MLINKS+=	drand48.3c seed48.3c
MLINKS+=	drand48.3c srand48.3c
MLINKS+=	dup2.3c dup3.3c
MLINKS+=	econvert.3c fconvert.3c
MLINKS+=	econvert.3c gconvert.3c
MLINKS+=	econvert.3c qeconvert.3c
MLINKS+=	econvert.3c qfconvert.3c
MLINKS+=	econvert.3c qgconvert.3c
MLINKS+=	econvert.3c seconvert.3c
MLINKS+=	econvert.3c sfconvert.3c
MLINKS+=	econvert.3c sgconvert.3c
MLINKS+=	ecvt.3c fcvt.3c
MLINKS+=	ecvt.3c gcvt.3c
MLINKS+=	end.3c _edata.3c
MLINKS+=	end.3c _end.3c
MLINKS+=	end.3c _etext.3c
MLINKS+=	end.3c edata.3c
MLINKS+=	end.3c etext.3c
MLINKS+=	endian.3c be16toh.3c
MLINKS+=	endian.3c be32toh.3c
MLINKS+=	endian.3c be64toh.3c
MLINKS+=	endian.3c betoh16.3c
MLINKS+=	endian.3c betoh32.3c
MLINKS+=	endian.3c betoh64.3c
MLINKS+=	endian.3c htobe16.3c
MLINKS+=	endian.3c htobe32.3c
MLINKS+=	endian.3c htobe64.3c
MLINKS+=	endian.3c htole16.3c
MLINKS+=	endian.3c htole32.3c
MLINKS+=	endian.3c htole64.3c
MLINKS+=	endian.3c le16toh.3c
MLINKS+=	endian.3c le32toh.3c
MLINKS+=	endian.3c le64toh.3c
MLINKS+=	endian.3c letoh16.3c
MLINKS+=	endian.3c letoh32.3c
MLINKS+=	endian.3c letoh64.3c
MLINKS+=	epoll_create.3c epoll_create1.3c
MLINKS+=	epoll_wait.3c epoll_pwait.3c
MLINKS+=	euclen.3c euccol.3c
MLINKS+=	euclen.3c eucscol.3c
MLINKS+=	exit.3c _exithandle.3c
MLINKS+=	ferror.3c clearerr.3c
MLINKS+=	ferror.3c feof.3c
MLINKS+=	ferror.3c fileno.3c
MLINKS+=	ffs.3c ffsl.3c
MLINKS+=	ffs.3c ffsll.3c
MLINKS+=	ffs.3c fls.3c
MLINKS+=	ffs.3c flsl.3c
MLINKS+=	ffs.3c flsll.3c
MLINKS+=	fgetattr.3c fsetattr.3c
MLINKS+=	fgetattr.3c getattrat.3c
MLINKS+=	fgetattr.3c setattrat.3c
MLINKS+=	fgetc.3c getc.3c
MLINKS+=	fgetc.3c getc_unlocked.3c
MLINKS+=	fgetc.3c getchar.3c
MLINKS+=	fgetc.3c getchar_unlocked.3c
MLINKS+=	fgetc.3c getw.3c
MLINKS+=	fgetwc.3c fgetwc_l.3c
MLINKS+=	floating_to_decimal.3c double_to_decimal.3c
MLINKS+=	floating_to_decimal.3c extended_to_decimal.3c
MLINKS+=	floating_to_decimal.3c quadruple_to_decimal.3c
MLINKS+=	floating_to_decimal.3c single_to_decimal.3c
MLINKS+=	flockfile.3c ftrylockfile.3c
MLINKS+=	flockfile.3c funlockfile.3c
MLINKS+=	fpgetround.3c fpgetmask.3c
MLINKS+=	fpgetround.3c fpgetsticky.3c
MLINKS+=	fpgetround.3c fpsetmask.3c
MLINKS+=	fpgetround.3c fpsetround.3c
MLINKS+=	fpgetround.3c fpsetsticky.3c
MLINKS+=	fputc.3c putc.3c
MLINKS+=	fputc.3c putc_unlocked.3c
MLINKS+=	fputc.3c putchar.3c
MLINKS+=	fputc.3c putchar_unlocked.3c
MLINKS+=	fputc.3c putw.3c
MLINKS+=	fputwc.3c putwc.3c
MLINKS+=	fputwc.3c putwchar.3c
MLINKS+=	fseek.3c fseeko.3c
MLINKS+=	ftell.3c ftello.3c
MLINKS+=	ftw.3c nftw.3c
MLINKS+=	fwprintf.3c swprintf.3c
MLINKS+=	fwprintf.3c wprintf.3c
MLINKS+=	fwscanf.3c swscanf.3c
MLINKS+=	fwscanf.3c vfwscanf.3c
MLINKS+=	fwscanf.3c vswscanf.3c
MLINKS+=	fwscanf.3c vwscanf.3c
MLINKS+=	fwscanf.3c wscanf.3c
MLINKS+=	getcpuid.3c gethomelgroup.3c
MLINKS+=	getgrnam.3c endgrent.3c
MLINKS+=	getgrnam.3c fgetgrent.3c
MLINKS+=	getgrnam.3c fgetgrent_r.3c
MLINKS+=	getgrnam.3c getgrent.3c
MLINKS+=	getgrnam.3c getgrent_r.3c
MLINKS+=	getgrnam.3c getgrgid.3c
MLINKS+=	getgrnam.3c getgrgid_r.3c
MLINKS+=	getgrnam.3c getgrnam_r.3c
MLINKS+=	getgrnam.3c setgrent.3c
MLINKS+=	gethostname.3c sethostname.3c
MLINKS+=	gethrtime.3c gethrvtime.3c
MLINKS+=	getline.3c getdelim.3c
MLINKS+=	getlogin.3c getlogin_r.3c
MLINKS+=	getmntent.3c getextmntent.3c
MLINKS+=	getmntent.3c getmntany.3c
MLINKS+=	getmntent.3c hasmntopt.3c
MLINKS+=	getmntent.3c putmntent.3c
MLINKS+=	getmntent.3c resetmnttab.3c
MLINKS+=	getnetgrent.3c endnetgrent.3c
MLINKS+=	getnetgrent.3c getnetgrent_r.3c
MLINKS+=	getnetgrent.3c innetgr.3c
MLINKS+=	getnetgrent.3c setnetgrent.3c
MLINKS+=	get_nprocs.3c get_nprocs_conf.3c
MLINKS+=	getpass.3c getpassphrase.3c
MLINKS+=	getpriority.3c setpriority.3c
MLINKS+=	getprogname.3c setprogname.3c
MLINKS+=	getpwnam.3c endpwent.3c
MLINKS+=	getpwnam.3c getpwent.3c
MLINKS+=	getpwnam.3c getpwnam_r.3c
MLINKS+=	getpwnam.3c getpwuid.3c
MLINKS+=	getpwnam.3c getpwuid_r.3c
MLINKS+=	getpwnam.3c setpwent.3c
MLINKS+=	gets.3c fgets.3c
MLINKS+=	getspnam.3c endspent.3c
MLINKS+=	getspnam.3c fgetspent.3c
MLINKS+=	getspnam.3c fgetspent_r.3c
MLINKS+=	getspnam.3c getspent.3c
MLINKS+=	getspnam.3c getspent_r.3c
MLINKS+=	getspnam.3c getspnam_r.3c
MLINKS+=	getspnam.3c setspent.3c
MLINKS+=	gettext.3c bind_textdomain_codeset.3c
MLINKS+=	gettext.3c bindtextdomain.3c
MLINKS+=	gettext.3c dcgettext.3c
MLINKS+=	gettext.3c dcngettext.3c
MLINKS+=	gettext.3c dgettext.3c
MLINKS+=	gettext.3c dngettext.3c
MLINKS+=	gettext.3c ngettext.3c
MLINKS+=	gettext.3c textdomain.3c
MLINKS+=	gettimeofday.3c settimeofday.3c
MLINKS+=	getusershell.3c endusershell.3c
MLINKS+=	getusershell.3c setusershell.3c
MLINKS+=	getutent.3c endutent.3c
MLINKS+=	getutent.3c getutid.3c
MLINKS+=	getutent.3c getutline.3c
MLINKS+=	getutent.3c pututline.3c
MLINKS+=	getutent.3c setutent.3c
MLINKS+=	getutent.3c utmpname.3c
MLINKS+=	getutxent.3c endutxent.3c
MLINKS+=	getutxent.3c getutmp.3c
MLINKS+=	getutxent.3c getutmpx.3c
MLINKS+=	getutxent.3c getutxid.3c
MLINKS+=	getutxent.3c getutxline.3c
MLINKS+=	getutxent.3c pututxline.3c
MLINKS+=	getutxent.3c setutxent.3c
MLINKS+=	getutxent.3c updwtmp.3c
MLINKS+=	getutxent.3c updwtmpx.3c
MLINKS+=	getutxent.3c utmpxname.3c
MLINKS+=	getvfsent.3c getvfsany.3c
MLINKS+=	getvfsent.3c getvfsfile.3c
MLINKS+=	getvfsent.3c getvfsspec.3c
MLINKS+=	getwc.3c getwc_l.3c
MLINKS+=	getwchar.3c getwchar_l.3c
MLINKS+=	getws.3c fgetws.3c
MLINKS+=	getzoneid.3c getzoneidbyname.3c
MLINKS+=	getzoneid.3c getzonenamebyid.3c
MLINKS+=	glob.3c globfree.3c
MLINKS+=	hsearch.3c hcreate.3c
MLINKS+=	hsearch.3c hdestroy.3c
MLINKS+=	index.3c rindex.3c
MLINKS+=	insque.3c remque.3c
MLINKS+=	isnand.3c finite.3c
MLINKS+=	isnand.3c fpclass.3c
MLINKS+=	isnand.3c isnanf.3c
MLINKS+=	isnand.3c unordered.3c
MLINKS+=	iswalpha.3c isenglish.3c
MLINKS+=	iswalpha.3c isideogram.3c
MLINKS+=	iswalpha.3c isnumber.3c
MLINKS+=	iswalpha.3c isphonogram.3c
MLINKS+=	iswalpha.3c isspecial.3c
MLINKS+=	iswalpha.3c iswalnum.3c
MLINKS+=	iswalpha.3c iswalnum_l.3c
MLINKS+=	iswalpha.3c iswalpha_l.3c
MLINKS+=	iswalpha.3c iswascii.3c
MLINKS+=	iswalpha.3c iswblank.3c
MLINKS+=	iswalpha.3c iswblank_l.3c
MLINKS+=	iswalpha.3c iswcntrl.3c
MLINKS+=	iswalpha.3c iswcntrl_l.3c
MLINKS+=	iswalpha.3c iswdigit.3c
MLINKS+=	iswalpha.3c iswdigit_l.3c
MLINKS+=	iswalpha.3c iswgraph.3c
MLINKS+=	iswalpha.3c iswgraph_l.3c
MLINKS+=	iswalpha.3c iswhexnumber.3c
MLINKS+=	iswalpha.3c iswhexnumber_l.3c
MLINKS+=	iswalpha.3c iswideogram.3c
MLINKS+=	iswalpha.3c iswideogram_l.3c
MLINKS+=	iswalpha.3c iswlower.3c
MLINKS+=	iswalpha.3c iswlower_l.3c
MLINKS+=	iswalpha.3c iswnumber.3c
MLINKS+=	iswalpha.3c iswnumber_l.3c
MLINKS+=	iswalpha.3c iswphonogram.3c
MLINKS+=	iswalpha.3c iswphonogram_l.3c
MLINKS+=	iswalpha.3c iswprint.3c
MLINKS+=	iswalpha.3c iswprint_l.3c
MLINKS+=	iswalpha.3c iswpunct.3c
MLINKS+=	iswalpha.3c iswpunct_l.3c
MLINKS+=	iswalpha.3c iswspace.3c
MLINKS+=	iswalpha.3c iswspace_l.3c
MLINKS+=	iswalpha.3c iswspecial.3c
MLINKS+=	iswalpha.3c iswspecial_l.3c
MLINKS+=	iswalpha.3c iswupper.3c
MLINKS+=	iswalpha.3c iswupper_l.3c
MLINKS+=	iswalpha.3c iswxdigit.3c
MLINKS+=	iswalpha.3c iswxdigit_l.3c
MLINKS+=	iswctype.3c iswctype_l.3c
MLINKS+=	lckpwdf.3c ulckpwdf.3c
MLINKS+=	lsearch.3c lfind.3c
MLINKS+=	makecontext.3c swapcontext.3c
MLINKS+=	makedev.3c major.3c
MLINKS+=	makedev.3c minor.3c
MLINKS+=	mblen.3c mblen_l.3c
MLINKS+=	mbrlen.3c mbrlen_l.3c
MLINKS+=	mbrtowc.3c mbrtowc_l.3c
MLINKS+=	mbsinit.3c mbsinit_l.3c
MLINKS+=	mbsrtowcs.3c mbsnrtowcs.3c
MLINKS+=	mbsrtowcs.3c mbsnrtowcs_l.3c
MLINKS+=	mbsrtowcs.3c mbsrtowcs_l.3c
MLINKS+=	mbsrtowcs.3c mbstowcs.3c
MLINKS+=	mbsrtowcs.3c mbstowcs_l.3c
MLINKS+=	mbtowc.3c mbtowc_l.3c
MLINKS+=	membar_ops.3c membar_consumer.3c
MLINKS+=	membar_ops.3c membar_enter.3c
MLINKS+=	membar_ops.3c membar_exit.3c
MLINKS+=	membar_ops.3c membar_producer.3c
MLINKS+=	memory.3c memccpy.3c
MLINKS+=	memory.3c memchr.3c
MLINKS+=	memory.3c memcmp.3c
MLINKS+=	memory.3c memcpy.3c
MLINKS+=	memory.3c memmem.3c
MLINKS+=	memory.3c memmove.3c
MLINKS+=	memory.3c memset.3c
MLINKS+=	mkfifo.3c mkfifoat.3c
MLINKS+=	mkstemp.3c mkdtemp.3c
MLINKS+=	mkstemp.3c mkostemp.3c
MLINKS+=	mkstemp.3c mkostemps.3c
MLINKS+=	mkstemp.3c mkstemps.3c
MLINKS+=	mlock.3c munlock.3c
MLINKS+=	mlockall.3c munlockall.3c
MLINKS+=	mq_receive.3c mq_reltimedreceive_np.3c
MLINKS+=	mq_receive.3c mq_timedreceive.3c
MLINKS+=	mq_send.3c mq_reltimedsend_np.3c
MLINKS+=	mq_send.3c mq_timedsend.3c
MLINKS+=	mtx.3c mtx_destroy.3c
MLINKS+=	mtx.3c mtx_init.3c
MLINKS+=	mtx.3c mtx_lock.3c
MLINKS+=	mtx.3c mtx_timedlock.3c
MLINKS+=	mtx.3c mtx_trylock.3c
MLINKS+=	mtx.3c mtx_unlock.3c
MLINKS+=	mutex_init.3c mutex_consistent.3c
MLINKS+=	mutex_init.3c mutex_destroy.3c
MLINKS+=	mutex_init.3c mutex_lock.3c
MLINKS+=	mutex_init.3c mutex_trylock.3c
MLINKS+=	mutex_init.3c mutex_unlock.3c
MLINKS+=	nanosleep.3c thrd_sleep.3c
MLINKS+=	ndbm.3c dbm_clearerr.3c
MLINKS+=	ndbm.3c dbm_close.3c
MLINKS+=	ndbm.3c dbm_delete.3c
MLINKS+=	ndbm.3c dbm_error.3c
MLINKS+=	ndbm.3c dbm_fetch.3c
MLINKS+=	ndbm.3c dbm_firstkey.3c
MLINKS+=	ndbm.3c dbm_nextkey.3c
MLINKS+=	ndbm.3c dbm_open.3c
MLINKS+=	ndbm.3c dbm_store.3c
MLINKS+=	newlocale.3c duplocale.3c
MLINKS+=	newlocale.3c freelocale.3c
MLINKS+=	nl_langinfo.3c nl_langinfo_l.3c
MLINKS+=	opendir.3c fdopendir.3c
MLINKS+=	perror.3c errno.3c
MLINKS+=	popen.3c pclose.3c
MLINKS+=	port_associate.3c port_dissociate.3c
MLINKS+=	port_get.3c port_getn.3c
MLINKS+=	port_send.3c port_sendn.3c
MLINKS+=	posix_spawn.3c posix_spawnp.3c
MLINKS+=	posix_spawn_file_actions_addclose.3c posix_spawn_file_actions_addopen.3c
MLINKS+=	posix_spawn_file_actions_destroy.3c posix_spawn_file_actions_init.3c
MLINKS+=	posix_spawnattr_destroy.3c posix_spawnattr_init.3c
MLINKS+=	posix_spawnattr_getflags.3c posix_spawnattr_setflags.3c
MLINKS+=	posix_spawnattr_getpgroup.3c posix_spawnattr_setpgroup.3c
MLINKS+=	posix_spawnattr_getschedparam.3c posix_spawnattr_setschedparam.3c
MLINKS+=	posix_spawnattr_getschedpolicy.3c posix_spawnattr_setschedpolicy.3c
MLINKS+=	posix_spawnattr_getsigdefault.3c posix_spawnattr_setsigdefault.3c
MLINKS+=	posix_spawnattr_getsigignore_np.3c posix_spawnattr_setsigignore_np.3c
MLINKS+=	posix_spawnattr_getsigmask.3c posix_spawnattr_setsigmask.3c
MLINKS+=	printf.3c asprintf.3c
MLINKS+=	printf.3c fprintf.3c
MLINKS+=	printf.3c snprintf.3c
MLINKS+=	printf.3c sprintf.3c
MLINKS+=	priv_addset.3c priv_allocset.3c
MLINKS+=	priv_addset.3c priv_basicset.3c
MLINKS+=	priv_addset.3c priv_copyset.3c
MLINKS+=	priv_addset.3c priv_delset.3c
MLINKS+=	priv_addset.3c priv_emptyset.3c
MLINKS+=	priv_addset.3c priv_fillset.3c
MLINKS+=	priv_addset.3c priv_freeset.3c
MLINKS+=	priv_addset.3c priv_intersect.3c
MLINKS+=	priv_addset.3c priv_inverse.3c
MLINKS+=	priv_addset.3c priv_isemptyset.3c
MLINKS+=	priv_addset.3c priv_isequalset.3c
MLINKS+=	priv_addset.3c priv_isfullset.3c
MLINKS+=	priv_addset.3c priv_ismember.3c
MLINKS+=	priv_addset.3c priv_issubset.3c
MLINKS+=	priv_addset.3c priv_union.3c
MLINKS+=	priv_set.3c priv_ineffect.3c
MLINKS+=	priv_str_to_set.3c priv_getbyname.3c
MLINKS+=	priv_str_to_set.3c priv_getbynum.3c
MLINKS+=	priv_str_to_set.3c priv_getsetbyname.3c
MLINKS+=	priv_str_to_set.3c priv_getsetbynum.3c
MLINKS+=	priv_str_to_set.3c priv_gettext.3c
MLINKS+=	priv_str_to_set.3c priv_set_to_str.3c
MLINKS+=	psignal.3c psiginfo.3c
MLINKS+=	pthread_attr_getdetachstate.3c pthread_attr_setdetachstate.3c
MLINKS+=	pthread_attr_getguardsize.3c pthread_attr_setguardsize.3c
MLINKS+=	pthread_attr_getinheritsched.3c pthread_attr_setinheritsched.3c
MLINKS+=	pthread_attr_getschedparam.3c pthread_attr_setschedparam.3c
MLINKS+=	pthread_attr_getschedpolicy.3c pthread_attr_setschedpolicy.3c
MLINKS+=	pthread_attr_getscope.3c pthread_attr_setscope.3c
MLINKS+=	pthread_attr_getstack.3c pthread_attr_setstack.3c
MLINKS+=	pthread_attr_getstackaddr.3c pthread_attr_setstackaddr.3c
MLINKS+=	pthread_attr_getstacksize.3c pthread_attr_setstacksize.3c
MLINKS+=	pthread_attr_init.3c pthread_attr_destroy.3c
MLINKS+=	pthread_barrier_destroy.3c pthread_barrier_init.3c
MLINKS+=	pthread_barrierattr_destroy.3c pthread_barrierattr_init.3c
MLINKS+=	pthread_barrierattr_getpshared.3c pthread_barrierattr_setpshared.3c
MLINKS+=	pthread_cond_init.3c pthread_cond_destroy.3c
MLINKS+=	pthread_cond_signal.3c pthread_cond_broadcast.3c
MLINKS+=	pthread_cond_wait.3c pthread_cond_reltimedwait_np.3c
MLINKS+=	pthread_cond_wait.3c pthread_cond_timedwait.3c
MLINKS+=	pthread_condattr_getclock.3c pthread_condattr_setclock.3c
MLINKS+=	pthread_condattr_getpshared.3c pthread_condattr_setpshared.3c
MLINKS+=	pthread_condattr_init.3c pthread_condattr_destroy.3c
MLINKS+=	pthread_getconcurrency.3c pthread_setconcurrency.3c
MLINKS+=	pthread_getschedparam.3c pthread_setschedparam.3c
MLINKS+=	pthread_getspecific.3c pthread_setspecific.3c
MLINKS+=	pthread_key_create.3c pthread_key_create_once_np.3c
MLINKS+=	pthread_mutex_getprioceiling.3c pthread_mutex_setprioceiling.3c
MLINKS+=	pthread_mutex_init.3c pthread_mutex_destroy.3c
MLINKS+=	pthread_mutex_lock.3c pthread_mutex_trylock.3c
MLINKS+=	pthread_mutex_lock.3c pthread_mutex_unlock.3c
MLINKS+=	pthread_mutex_timedlock.3c pthread_mutex_reltimedlock_np.3c
MLINKS+=	pthread_mutexattr_getprioceiling.3c pthread_mutexattr_setprioceiling.3c
MLINKS+=	pthread_mutexattr_getprotocol.3c pthread_mutexattr_setprotocol.3c
MLINKS+=	pthread_mutexattr_getpshared.3c pthread_mutexattr_setpshared.3c
MLINKS+=	pthread_mutexattr_getrobust.3c pthread_mutexattr_setrobust.3c
MLINKS+=	pthread_mutexattr_gettype.3c pthread_mutexattr_settype.3c
MLINKS+=	pthread_mutexattr_init.3c pthread_mutexattr_destroy.3c
MLINKS+=	pthread_rwlock_init.3c pthread_rwlock_destroy.3c
MLINKS+=	pthread_rwlock_rdlock.3c pthread_rwlock_tryrdlock.3c
MLINKS+=	pthread_rwlock_timedrdlock.3c pthread_rwlock_reltimedrdlock_np.3c
MLINKS+=	pthread_rwlock_timedwrlock.3c pthread_rwlock_reltimedwrlock_np.3c
MLINKS+=	pthread_rwlock_wrlock.3c pthread_rwlock_trywrlock.3c
MLINKS+=	pthread_rwlockattr_getpshared.3c pthread_rwlockattr_setpshared.3c
MLINKS+=	pthread_rwlockattr_init.3c pthread_rwlockattr_destroy.3c
MLINKS+=	pthread_spin_destroy.3c pthread_spin_init.3c
MLINKS+=	pthread_spin_lock.3c pthread_spin_trylock.3c
MLINKS+=	puts.3c fputs.3c
MLINKS+=	rand.3c rand_r.3c
MLINKS+=	rand.3c srand.3c
MLINKS+=	random.3c initstate.3c
MLINKS+=	random.3c setstate.3c
MLINKS+=	random.3c srandom.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_get_enforced_value.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_get_firing_time.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_get_global_action.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_get_global_flags.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_get_local_action.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_get_local_flags.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_get_privilege.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_get_recipient_pid.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_get_value.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_set_local_action.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_set_local_flags.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_set_privilege.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_set_recipient_pid.3c
MLINKS+=	rctlblk_set_value.3c rctlblk_size.3c
MLINKS+=	re_comp.3c re_exec.3c
MLINKS+=	regcmp.3c regex.3c
MLINKS+=	regcomp.3c regerror.3c
MLINKS+=	regcomp.3c regexec.3c
MLINKS+=	regcomp.3c regfree.3c
MLINKS+=	rwlock.3c rw_rdlock.3c
MLINKS+=	rwlock.3c rw_tryrdlock.3c
MLINKS+=	rwlock.3c rw_trywrlock.3c
MLINKS+=	rwlock.3c rw_unlock.3c
MLINKS+=	rwlock.3c rw_wrlock.3c
MLINKS+=	rwlock.3c rwlock_destroy.3c
MLINKS+=	rwlock.3c rwlock_init.3c
MLINKS+=	scandir.3c alphasort.3c
MLINKS+=	scanf.3c fscanf.3c
MLINKS+=	scanf.3c sscanf.3c
MLINKS+=	scanf.3c vfscanf.3c
MLINKS+=	scanf.3c vscanf.3c
MLINKS+=	scanf.3c vsscanf.3c
MLINKS+=	sched_get_priority_max.3c sched_get_priority_min.3c
MLINKS+=	schedctl_init.3c schedctl_exit.3c
MLINKS+=	schedctl_init.3c schedctl_lookup.3c
MLINKS+=	schedctl_init.3c schedctl_start.3c
MLINKS+=	schedctl_init.3c schedctl_stop.3c
MLINKS+=	select.3c FD_CLR.3c
MLINKS+=	select.3c FD_ISSET.3c
MLINKS+=	select.3c FD_SET.3c
MLINKS+=	select.3c FD_ZERO.3c
MLINKS+=	select.3c pselect.3c
MLINKS+=	sem_timedwait.3c sem_reltimedwait_np.3c
MLINKS+=	sem_wait.3c sem_trywait.3c
MLINKS+=	semaphore.3c sema_destroy.3c
MLINKS+=	semaphore.3c sema_init.3c
MLINKS+=	semaphore.3c sema_post.3c
MLINKS+=	semaphore.3c sema_trywait.3c
MLINKS+=	semaphore.3c sema_wait.3c
MLINKS+=	setbuf.3c setvbuf.3c
MLINKS+=	setbuffer.3c setlinebuf.3c
MLINKS+=	setjmp.3c longjmp.3c
MLINKS+=	setjmp.3c siglongjmp.3c
MLINKS+=	setjmp.3c sigsetjmp.3c
MLINKS+=	signal.3c sighold.3c
MLINKS+=	signal.3c sigignore.3c
MLINKS+=	signal.3c sigpause.3c
MLINKS+=	signal.3c sigrelse.3c
MLINKS+=	signal.3c sigset.3c
MLINKS+=	sigsetops.3c sigaddset.3c
MLINKS+=	sigsetops.3c sigdelset.3c
MLINKS+=	sigsetops.3c sigemptyset.3c
MLINKS+=	sigsetops.3c sigfillset.3c
MLINKS+=	sigsetops.3c sigismember.3c
MLINKS+=	sigwaitinfo.3c sigtimedwait.3c
MLINKS+=	ssignal.3c gsignal.3c
MLINKS+=	stdio.3c stderr.3c
MLINKS+=	stdio.3c stdin.3c
MLINKS+=	stdio.3c stdout.3c
MLINKS+=	str2sig.3c sig2str.3c
MLINKS+=	strcoll.3c strcoll_l.3c
MLINKS+=	strerror.3c strerror_l.3c
MLINKS+=	strerror.3c strerror_r.3c
MLINKS+=	strfmon.3c strfmon_l.3c
MLINKS+=	strftime.3c ascftime.3c
MLINKS+=	strftime.3c cftime.3c
MLINKS+=	strftime.3c strftime_l.3c
MLINKS+=	string.3c stpcpy.3c
MLINKS+=	string.3c stpncpy.3c
MLINKS+=	string.3c strcasecmp.3c
MLINKS+=	string.3c strcasecmp_l.3c
MLINKS+=	string.3c strcasestr.3c
MLINKS+=	string.3c strcasestr_l.3c
MLINKS+=	string.3c strcat.3c
MLINKS+=	string.3c strchr.3c
MLINKS+=	string.3c strchrnul.3c
MLINKS+=	string.3c strcmp.3c
MLINKS+=	string.3c strcpy.3c
MLINKS+=	string.3c strcspn.3c
MLINKS+=	string.3c strdup.3c
MLINKS+=	string.3c strdupa.3c
MLINKS+=	string.3c strlcat.3c
MLINKS+=	string.3c strlcpy.3c
MLINKS+=	string.3c strlen.3c
MLINKS+=	string.3c strncasecmp.3c
MLINKS+=	string.3c strncasecmp_l.3c
MLINKS+=	string.3c strncat.3c
MLINKS+=	string.3c strncmp.3c
MLINKS+=	string.3c strncpy.3c
MLINKS+=	string.3c strndup.3c
MLINKS+=	string.3c strndupa.3c
MLINKS+=	string.3c strnlen.3c
MLINKS+=	string.3c strnstr.3c
MLINKS+=	string.3c strpbrk.3c
MLINKS+=	string.3c strrchr.3c
MLINKS+=	string.3c strsep.3c
MLINKS+=	string.3c strspn.3c
MLINKS+=	string.3c strstr.3c
MLINKS+=	string.3c strtok.3c
MLINKS+=	string.3c strtok_r.3c
MLINKS+=	string_to_decimal.3c file_to_decimal.3c
MLINKS+=	string_to_decimal.3c func_to_decimal.3c
MLINKS+=	strptime.3c strptime_l.3c
MLINKS+=	strtod.3c atof.3c
MLINKS+=	strtod.3c strtof.3c
MLINKS+=	strtod.3c strtold.3c
MLINKS+=	strtoimax.3c strtoumax.3c
MLINKS+=	strtol.3c atoi.3c
MLINKS+=	strtol.3c atol.3c
MLINKS+=	strtol.3c atoll.3c
MLINKS+=	strtol.3c lltostr.3c
MLINKS+=	strtol.3c strtoll.3c
MLINKS+=	strtol.3c ulltostr.3c
MLINKS+=	strtoul.3c strtoull.3c
MLINKS+=	strtows.3c wstostr.3c
MLINKS+=	strxfrm.3c strxfrm_l.3c
MLINKS+=	syslog.3c closelog.3c
MLINKS+=	syslog.3c openlog.3c
MLINKS+=	syslog.3c setlogmask.3c
MLINKS+=	thr_getconcurrency.3c thr_setconcurrency.3c
MLINKS+=	thr_getprio.3c thr_setprio.3c
MLINKS+=	thr_keycreate.3c thr_getspecific.3c
MLINKS+=	thr_keycreate.3c thr_keycreate_once.3c
MLINKS+=	thr_keycreate.3c thr_setspecific.3c
MLINKS+=	thr_suspend.3c thr_continue.3c
MLINKS+=	mktime.3c timegm.3c
MLINKS+=	timer_settime.3c timer_getoverrun.3c
MLINKS+=	timer_settime.3c timer_gettime.3c
MLINKS+=	timeradd.3c timerclear.3c
MLINKS+=	timeradd.3c timercmp.3c
MLINKS+=	timeradd.3c timerisset.3c
MLINKS+=	timeradd.3c timersub.3c
MLINKS+=	timerfd_create.3c timerfd_gettime.3c
MLINKS+=	timerfd_create.3c timerfd_settime.3c
MLINKS+=	tmpnam.3c tempnam.3c
MLINKS+=	tmpnam.3c tmpnam_r.3c
MLINKS+=	tolower.3c tolower_l.3c
MLINKS+=	toupper.3c toupper_l.3c
MLINKS+=	towlower.3c towlower_l.3c
MLINKS+=	towupper.3c towupper_l.3c
MLINKS+=	truncate.3c ftruncate.3c
MLINKS+=	tsearch.3c tdelete.3c
MLINKS+=	tsearch.3c tfind.3c
MLINKS+=	tsearch.3c twalk.3c
MLINKS+=	tss.3c tss_create.3c
MLINKS+=	tss.3c tss_delete.3c
MLINKS+=	tss.3c tss_get.3c
MLINKS+=	tss.3c tss_set.3c
MLINKS+=	ttyname.3c ttyname_r.3c
MLINKS+=	uconv_u16tou32.3c uconv_u16tou8.3c
MLINKS+=	uconv_u16tou32.3c uconv_u32tou16.3c
MLINKS+=	uconv_u16tou32.3c uconv_u32tou8.3c
MLINKS+=	uconv_u16tou32.3c uconv_u8tou16.3c
MLINKS+=	uconv_u16tou32.3c uconv_u8tou32.3c
MLINKS+=	ucred.3c ucred_free.3c
MLINKS+=	ucred.3c ucred_get.3c
MLINKS+=	ucred.3c ucred_getegid.3c
MLINKS+=	ucred.3c ucred_geteuid.3c
MLINKS+=	ucred.3c ucred_getgroups.3c
MLINKS+=	ucred.3c ucred_getpflags.3c
MLINKS+=	ucred.3c ucred_getpid.3c
MLINKS+=	ucred.3c ucred_getprivset.3c
MLINKS+=	ucred.3c ucred_getprojid.3c
MLINKS+=	ucred.3c ucred_getrgid.3c
MLINKS+=	ucred.3c ucred_getruid.3c
MLINKS+=	ucred.3c ucred_getsgid.3c
MLINKS+=	ucred.3c ucred_getsuid.3c
MLINKS+=	ucred.3c ucred_getzoneid.3c
MLINKS+=	ucred.3c ucred_size.3c
MLINKS+=	vfwprintf.3c vswprintf.3c
MLINKS+=	vfwprintf.3c vwprintf.3c
MLINKS+=	vprintf.3c vasprintf.3c
MLINKS+=	vprintf.3c vfprintf.3c
MLINKS+=	vprintf.3c vsnprintf.3c
MLINKS+=	vprintf.3c vsprintf.3c
MLINKS+=	wait3.3c wait4.3c
MLINKS+=	walkcontext.3c addrtosymstr.3c
MLINKS+=	walkcontext.3c backtrace.3c
MLINKS+=	walkcontext.3c backtrace_symbols.3c
MLINKS+=	walkcontext.3c backtrace_symbols_fd.3c
MLINKS+=	walkcontext.3c printstack.3c
MLINKS+=	wcpcpy.3c wcpncpy.3c
MLINKS+=	wcrtomb.3c wcrtomb_l.3c
MLINKS+=	wcscasecmp.3c wcscasecmp_l.3c
MLINKS+=	wcscasecmp.3c wcsncasecmp.3c
MLINKS+=	wcscasecmp.3c wcsncasecmp_l.3c
MLINKS+=	wcscoll.3c wcscoll_l.3c
MLINKS+=	wcscoll.3c wscoll.3c
MLINKS+=	wcslen.3c wcsnlen.3c
MLINKS+=	wcsrtombs.3c wcsnrtombs.3c
MLINKS+=	wcsrtombs.3c wcsnrtombs_l.3c
MLINKS+=	wcsrtombs.3c wcsrtombs_l.3c
MLINKS+=	wcstod.3c watof.3c
MLINKS+=	wcstod.3c wcstof.3c
MLINKS+=	wcstod.3c wcstold.3c
MLINKS+=	wcstod.3c wstod.3c
MLINKS+=	wcstoimax.3c wcstoumax.3c
MLINKS+=	wcstol.3c watoi.3c
MLINKS+=	wcstol.3c watol.3c
MLINKS+=	wcstol.3c watoll.3c
MLINKS+=	wcstol.3c wcstoll.3c
MLINKS+=	wcstol.3c wstol.3c
MLINKS+=	wcstoul.3c wcstoull.3c
MLINKS+=	wcstring.3c wcscat.3c
MLINKS+=	wcstring.3c wcschr.3c
MLINKS+=	wcstring.3c wcscmp.3c
MLINKS+=	wcstring.3c wcscpy.3c
MLINKS+=	wcstring.3c wcscspn.3c
MLINKS+=	wcstring.3c wcsncat.3c
MLINKS+=	wcstring.3c wcsncmp.3c
MLINKS+=	wcstring.3c wcsncpy.3c
MLINKS+=	wcstring.3c wcspbrk.3c
MLINKS+=	wcstring.3c wcsrchr.3c
MLINKS+=	wcstring.3c wcsspn.3c
MLINKS+=	wcstring.3c wcstok.3c
MLINKS+=	wcstring.3c wcswcs.3c
MLINKS+=	wcstring.3c windex.3c
MLINKS+=	wcstring.3c wrindex.3c
MLINKS+=	wcstring.3c wscat.3c
MLINKS+=	wcstring.3c wschr.3c
MLINKS+=	wcstring.3c wscmp.3c
MLINKS+=	wcstring.3c wscpy.3c
MLINKS+=	wcstring.3c wscspn.3c
MLINKS+=	wcstring.3c wslen.3c
MLINKS+=	wcstring.3c wsncat.3c
MLINKS+=	wcstring.3c wsncmp.3c
MLINKS+=	wcstring.3c wsncpy.3c
MLINKS+=	wcstring.3c wspbrk.3c
MLINKS+=	wcstring.3c wsrchr.3c
MLINKS+=	wcstring.3c wsspn.3c
MLINKS+=	wcstring.3c wstok.3c
MLINKS+=	wstring.3c wscasecmp.3c
MLINKS+=	wstring.3c wscol.3c
MLINKS+=	wstring.3c wsdup.3c
MLINKS+=	wstring.3c wsncasecmp.3c
MLINKS+=	wcswidth.3c wcswidth_l.3c
MLINKS+=	wcsxfrm.3c wsxfrm.3c
MLINKS+=	wctob.3c wctob_l.3c
MLINKS+=	wctomb.3c wctomb_l.3c
MLINKS+=	wctrans.3c towctrans.3c
MLINKS+=	wctrans.3c towctrans_l.3c
MLINKS+=	wctrans.3c wctrans_l.3c
MLINKS+=	wctype.3c wctype_l.3c
MLINKS+=	wcwidth.3c wcwidth_l.3c
MLINKS+=	wordexp.3c wordfree.3c

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
