#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = acl/cmd_tests
SHRSRC = ACL.utils CMD_TESTS.flist README
TCS = getfacl_pos01 runtests setfacl_neg01 setfacl_neg02 \
	setfacl_pos01 setfacl_pos02 setfacl_pos03 \
	setfacl_pos05 setfacl_pos06 setfacl_pos07 \
	setfacl_pos09
TCLSRC =

include ../../Makefile.test
