MAN = sdp_add_origin.3commputil \
      sdp_clone_session.3commputil \
      sdp_delete_all_field.3commputil \
      sdp_delete_media.3commputil \
      sdp_find_attribute.3commputil \
      sdp_find_media.3commputil \
      sdp_find_media_rtpmap.3commputil \
      sdp_new_session.3commputil \
      sdp_parse.3commputil \
      sdp_session_to_str.3commputil

MLINKS+=	sdp_add_origin.3commputil sdp_add_attribute.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_bandwidth.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_connection.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_email.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_information.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_key.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_media.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_name.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_phone.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_repeat.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_time.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_uri.3commputil
MLINKS+=	sdp_add_origin.3commputil sdp_add_zone.3commputil
MLINKS+=	sdp_delete_all_field.3commputil sdp_delete_all_media_field.3commputil
MLINKS+=	sdp_delete_media.3commputil sdp_delete_attribute.3commputil
MLINKS+=	sdp_new_session.3commputil sdp_free_session.3commputil

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
