MAN = pool_associate.3pool \
      pool_component_info.3pool \
      pool_component_to_elem.3pool \
      pool_conf_alloc.3pool \
      pool_dynamic_location.3pool \
      pool_error.3pool \
      pool_get_binding.3pool \
      pool_get_pool.3pool \
      pool_get_property.3pool \
      pool_resource_create.3pool \
      pool_value_alloc.3pool \
      pool_walk_components.3pool

MLINKS+=	pool_associate.3pool pool_create.3pool
MLINKS+=	pool_associate.3pool pool_destroy.3pool
MLINKS+=	pool_associate.3pool pool_dissociate.3pool
MLINKS+=	pool_associate.3pool pool_info.3pool
MLINKS+=	pool_associate.3pool pool_query_pool_resources.3pool
MLINKS+=	pool_component_info.3pool pool_get_owning_resource.3pool
MLINKS+=	pool_component_to_elem.3pool pool_conf_to_elem.3pool
MLINKS+=	pool_component_to_elem.3pool pool_resource_to_elem.3pool
MLINKS+=	pool_component_to_elem.3pool pool_to_elem.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_close.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_commit.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_export.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_free.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_info.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_location.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_open.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_remove.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_rollback.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_status.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_update.3pool
MLINKS+=	pool_conf_alloc.3pool pool_conf_validate.3pool
MLINKS+=	pool_dynamic_location.3pool pool_get_status.3pool
MLINKS+=	pool_dynamic_location.3pool pool_resource_type_list.3pool
MLINKS+=	pool_dynamic_location.3pool pool_set_status.3pool
MLINKS+=	pool_dynamic_location.3pool pool_static_location.3pool
MLINKS+=	pool_dynamic_location.3pool pool_version.3pool
MLINKS+=	pool_error.3pool pool_strerror.3pool
MLINKS+=	pool_get_binding.3pool pool_get_resource_binding.3pool
MLINKS+=	pool_get_binding.3pool pool_set_binding.3pool
MLINKS+=	pool_get_pool.3pool pool_get_resource.3pool
MLINKS+=	pool_get_pool.3pool pool_query_components.3pool
MLINKS+=	pool_get_pool.3pool pool_query_pools.3pool
MLINKS+=	pool_get_pool.3pool pool_query_resources.3pool
MLINKS+=	pool_get_property.3pool pool_put_property.3pool
MLINKS+=	pool_get_property.3pool pool_rm_property.3pool
MLINKS+=	pool_get_property.3pool pool_walk_properties.3pool
MLINKS+=	pool_resource_create.3pool pool_query_resource_components.3pool
MLINKS+=	pool_resource_create.3pool pool_resource_destroy.3pool
MLINKS+=	pool_resource_create.3pool pool_resource_info.3pool
MLINKS+=	pool_resource_create.3pool pool_resource_transfer.3pool
MLINKS+=	pool_resource_create.3pool pool_resource_xtransfer.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_free.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_get_bool.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_get_double.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_get_int64.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_get_name.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_get_string.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_get_type.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_get_uint64.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_set_bool.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_set_double.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_set_int64.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_set_name.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_set_string.3pool
MLINKS+=	pool_value_alloc.3pool pool_value_set_uint64.3pool
MLINKS+=	pool_walk_components.3pool pool_walk_pools.3pool
MLINKS+=	pool_walk_components.3pool pool_walk_resources.3pool

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
