#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = delegation/twoclients/delegreturn
STFDESC = stf_description
PROGS = clntb_acl01 clntb_acl02 clntb_chmod01 clntb_chmod02 \
	clntb_read clntb_remove01 clntb_remove02 \
	clntb_rename01 clntb_rename02 clntb_write01 \
	clntb_write02 delegreturn2 exec_clntb_run \
	exec_clntb_write mkassert

include ../../../Makefile.test
