MAN = au_open.3bsm \
      au_preselect.3bsm \
      au_to.3bsm \
      au_user_mask.3bsm \
      getacinfo.3bsm \
      getauclassent.3bsm \
      getauditflags.3bsm \
      getauevent.3bsm \
      getauusernam.3bsm \
      getddent.3bsm \
      getfauditflags.3bsm

MLINKS+=	au_open.3bsm au_close.3bsm
MLINKS+=	au_open.3bsm au_write.3bsm
MLINKS+=	au_to.3bsm au_to_arg.3bsm
MLINKS+=	au_to.3bsm au_to_arg32.3bsm
MLINKS+=	au_to.3bsm au_to_arg64.3bsm
MLINKS+=	au_to.3bsm au_to_attr.3bsm
MLINKS+=	au_to.3bsm au_to_cmd.3bsm
MLINKS+=	au_to.3bsm au_to_data.3bsm
MLINKS+=	au_to.3bsm au_to_groups.3bsm
MLINKS+=	au_to.3bsm au_to_in_addr.3bsm
MLINKS+=	au_to.3bsm au_to_ipc.3bsm
MLINKS+=	au_to.3bsm au_to_iport.3bsm
MLINKS+=	au_to.3bsm au_to_me.3bsm
MLINKS+=	au_to.3bsm au_to_newgroups.3bsm
MLINKS+=	au_to.3bsm au_to_opaque.3bsm
MLINKS+=	au_to.3bsm au_to_path.3bsm
MLINKS+=	au_to.3bsm au_to_process.3bsm
MLINKS+=	au_to.3bsm au_to_process_ex.3bsm
MLINKS+=	au_to.3bsm au_to_return.3bsm
MLINKS+=	au_to.3bsm au_to_return32.3bsm
MLINKS+=	au_to.3bsm au_to_return64.3bsm
MLINKS+=	au_to.3bsm au_to_socket.3bsm
MLINKS+=	au_to.3bsm au_to_subject.3bsm
MLINKS+=	au_to.3bsm au_to_subject_ex.3bsm
MLINKS+=	au_to.3bsm au_to_text.3bsm
MLINKS+=	getacinfo.3bsm endac.3bsm
MLINKS+=	getacinfo.3bsm getacdir.3bsm
MLINKS+=	getacinfo.3bsm getacflg.3bsm
MLINKS+=	getacinfo.3bsm getacmin.3bsm
MLINKS+=	getacinfo.3bsm getacna.3bsm
MLINKS+=	getacinfo.3bsm setac.3bsm
MLINKS+=	getauclassent.3bsm endauclass.3bsm
MLINKS+=	getauclassent.3bsm getauclassent_r.3bsm
MLINKS+=	getauclassent.3bsm getauclassnam.3bsm
MLINKS+=	getauclassent.3bsm getauclassnam_r.3bsm
MLINKS+=	getauclassent.3bsm setauclass.3bsm
MLINKS+=	getauditflags.3bsm getauditflagsbin.3bsm
MLINKS+=	getauditflags.3bsm getauditflagschar.3bsm
MLINKS+=	getauevent.3bsm endauevent.3bsm
MLINKS+=	getauevent.3bsm getauevent_r.3bsm
MLINKS+=	getauevent.3bsm getauevnam.3bsm
MLINKS+=	getauevent.3bsm getauevnam_r.3bsm
MLINKS+=	getauevent.3bsm getauevnonam.3bsm
MLINKS+=	getauevent.3bsm getauevnum.3bsm
MLINKS+=	getauevent.3bsm getauevnum_r.3bsm
MLINKS+=	getauevent.3bsm setauevent.3bsm
MLINKS+=	getauusernam.3bsm endauuser.3bsm
MLINKS+=	getauusernam.3bsm getauuserent.3bsm
MLINKS+=	getauusernam.3bsm getauuserent_r.3bsm
MLINKS+=	getauusernam.3bsm getauusernam_r.3bsm
MLINKS+=	getauusernam.3bsm setauuser.3bsm
MLINKS+=	getddent.3bsm endddent.3bsm
MLINKS+=	getddent.3bsm getddnam.3bsm
MLINKS+=	getddent.3bsm setddent.3bsm
MLINKS+=	getddent.3bsm setddfile.3bsm

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
