MAN = au_open.3bsm \
      au_preselect.3bsm \
      au_to.3bsm \
      au_user_mask.3bsm \
      getauclassent.3bsm \
      getauditflags.3bsm \
      getauevent.3bsm \
      getfauditflags.3bsm

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
