#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = acl/trivial
STFDESC = stf_description
PROGS = acl_chmod_pos001 acl_compress_pos001 acl_cp_neg001 \
	acl_cp_neg002 acl_cp_pos001 acl_find_neg001 acl_find_pos001 \
	acl_ls_neg001 acl_ls_pos001 acl_mv_pos001 acl_pack_pos001 \
	acl_pax_pos001 acl_pax_pos002 acl_pax_pos003 \
	acl_pax_pos004 acl_pax_pos005 acl_pax_pos006 \
	acl_tar_neg001 acl_tar_pos001
	
include ../../Makefile.test
