#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = svccfg/inventory
DESC = inventory_001.xml inventory_002.xml inventory_001.out \
	stf_description
TCS = inventory_001 inventory_002 inventory_003 \
	inventory_004 inventory_005 inventory_006 \
	svccfg_inventory_setup

include ../../Makefile.test
