.\" The contents of this file are subject to the terms of the Common
.\" Development and Distribution License (the "License").  You may not use
.\" this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or
.\" http://www.opensolaris.org/os/licensing.  See the License for the
.\" specific language governing permissions and limitations under the
.\" License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each file
.\" and include the License file at usr/src/OPENSOLARIS.LICENSE.  If
.\" applicable, add the following below this CDDL HEADER, with the fields
.\" enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" Copyright (c) 2003, Sun Microsystems, Inc.  All Rights Reserved
.\" Copyright 2026 OmniOS Community Edition (OmniOSce) Association.
.\"
.Dd August 8, 2026
.Dt PFEXEC 1
.Os
.Sh NAME
.Nm pfexec ,
.Nm pfsh ,
.Nm pfcsh ,
.Nm pfksh
.Nd execute a command in a profile
.Sh SYNOPSIS
.Nm pfexec
.Ar command
.Nm pfexec
.Fl P Ar privspec
.Ar command
.Op Ar arg Ns ...
.Nm pfexec
.Fl k
.Nm pfsh
.Op Ar options
.Op Ar argument Ns ...
.Nm pfcsh
.Op Ar options
.Op Ar argument Ns ...
.Nm pfksh
.Op Ar options
.Op Ar argument Ns ...
.Sh DESCRIPTION
The
.Nm pfexec
program is used to execute commands with the attributes specified by the
user's profiles in the
.Xr exec_attr 5
database.
It is invoked by the profile shells,
.Nm pfsh ,
.Nm pfcsh ,
and
.Nm pfksh
which are linked to the Bourne shell, C shell, and Korn shell, respectively.
.Pp
Profiles are searched in the order specified in the user's entry in the
.Xr user_attr 5
database.
If the same command appears in more than one profile, the profile shell uses
the first matching entry.
.Pp
The second form,
.Nm pfexec Fl P Ar privspec ,
allows a user to obtain the additional privileges awarded to the user's
profiles in
.Xr prof_attr 5 .
The privileges specification on the command line is parsed using
.Xr priv_str_to_set 3C .
The resulting privileges are intersected with the union of the privileges
specified using the
.Dq Sy privs
keyword in
.Xr prof_attr 5
for all the user's profiles and added to the inheritable set before executing
the command.
.Pp
If the command matches an entry in a profile assigned to the user's
authenticated profile list
.Po the
.Dq Sy auth_profiles
keyword in
.Xr user_attr 5
.Pc ,
the user is first required to authenticate on the controlling terminal, by
default with their own password.
A process without a controlling terminal cannot use the authenticated profile
list.
Successful authentication is recorded in the new process and is inherited
until the real user ID changes, so authenticating once for a command which is
itself a profile shell provides an authenticated session.
The authentication conversation may additionally be cached for a limited time
if the
.Dq Sy pfexec
PAM service is configured with a caching module such as
.Xr pam_timestamp 7 .
.Pp
The third form,
.Nm pfexec Fl k ,
discards any cached authentication state held for the invoking user and
controlling terminal.
.Pp
For
.Nm pfexec
to function correctly, the
.Sy pfexecd
daemon must be running in the current zone.
This is normally managed by the
.Dq Sy svc:/system/pfexec:default
SMF service
.Pq see Xr smf 7 .
.Sh USAGE
.Nm pfexec
is used to execute commands with predefined process attributes, such as
specific user or group IDs.
.Pp
Refer to the
.Xr sh 1 ,
.Xr csh 1 ,
and
.Xr ksh 1
man pages for complete usage descriptions of the profile shells.
.Sh EXIT STATUS
The following exit values are returned:
.Bl -tag -width Ds
.It 0
Successful completion.
.It 1
An error occurred.
.El
.Sh EXAMPLES
.Sy Example 1 No Obtaining additional user privileges
.Bd -literal -offset 4n
% pfexec -P all chown user file
.Ed
.Pp
This command runs
.Sy chown user file
with all privileges assigned to the current user, not necessarily all
privileges.
.Sh SEE ALSO
.Xr csh 1 ,
.Xr ksh 1 ,
.Xr profiles 1 ,
.Xr sh 1 ,
.Xr priv_str_to_set 3C ,
.Xr exec_attr 5 ,
.Xr prof_attr 5 ,
.Xr user_attr 5 ,
.Xr attributes 7 ,
.Xr pam_timestamp 7 ,
.Xr smf 7
