.\" Copyright (c) 1982-2007 AT&T Knowledge Ventures
.\" To view license terms, see http://www.opensource.org/licenses/cpl1.0.txt
.\" Portions Copyright (c) 2009, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright 2021 OmniOS Community Edition (OmniOSce) Association.
.Dd Feb 9, 2021
.Dt REV 1
.Os
.Sh NAME
.Nm rev
.Nd reverse the characters or lines of one or more files
.Sh SYNOPSIS
.Nm
.Op Fl l
.Oo Ar file Oc Ns ...
.Sh DESCRIPTION
.Sh OPTIONS
.Nm
copies one or more files to standard output, reversing the order of
characters on every line of the file, or reversing the order of lines of the
file if
.Fl l
is specified.
The following options are supported:
.Bl -tag -width Ar
.It Fl l Ns \&, Fl \-line
Reverse the order of the lines of the file, instead of characters.
.El
.Sh OPERANDS
The following operands are supported:
.Bl -tag -width Ar
.It Ar file
Specifies the name of the file to use as input.
.Pp
If
.Ar file
is not specified or is
.Sy \- ,
.Nm
copies from standard input starting at the current offset.
.El
.Sh EXIT STATUS
The following exit values are returned:
.Bl -tag -width Ds
.It Sy 0
All files copied successfully.
.It Sy >0
One or more files did not copy.
.El
.Sh INTERFACE STABILITY
.Sy Committed .
.Sh SEE ALSO
.Xr cat 1 ,
.Xr ksh93 1 ,
.Xr tail 1 ,
.Xr attributes 5
