#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TPLDIR = svccfg/templates
TEST = $(TPLDIR)/prop_pattern_cardinality
DESC = config.env stf_description prop_pattern_cardinality.xml
TCS = prop_pattern_cardinality_001 prop_pattern_cardinality_002 \
	prop_pattern_cardinality_003 prop_pattern_cardinality_004 \
	prop_pattern_cardinality_005 prop_pattern_cardinality_006 \
	prop_pattern_cardinality_007 prop_pattern_cardinality_008 \
	prop_pattern_cardinality_009 prop_pattern_cardinality_010 \
	prop_pattern_cardinality_011 prop_pattern_cardinality_012 \
	prop_pattern_cardinality_013 prop_pattern_cardinality_014 \
	prop_pattern_cardinality_015

include ../../../Makefile.test
