MAN = papiAttributeListAddValue.3papi \
      papiJobSubmit.3papi \
      papiLibrarySupportedCall.3papi \
      papiPrintersList.3papi \
      papiServiceCreate.3papi \
      papiStatusString.3papi

MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListAddBoolean.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListAddCollection.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListAddDatetime.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListAddInteger.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListAddMetadata.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListAddRange.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListAddResolution.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListAddString.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListDelete.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListFind.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListFree.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListFromString.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetBoolean.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetCollection.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetDatetime.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetInteger.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetMetadata.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetNext.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetRange.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetResolution.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetString.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListGetValue.3papi
MLINKS+=	papiAttributeListAddValue.3papi papiAttributeListToString.3papi
MLINKS+=	papiJobSubmit.3papi papiJobCancel.3papi
MLINKS+=	papiJobSubmit.3papi papiJobFree.3papi
MLINKS+=	papiJobSubmit.3papi papiJobGetAttributeList.3papi
MLINKS+=	papiJobSubmit.3papi papiJobGetId.3papi
MLINKS+=	papiJobSubmit.3papi papiJobGetJobTicket.3papi
MLINKS+=	papiJobSubmit.3papi papiJobGetPrinterName.3papi
MLINKS+=	papiJobSubmit.3papi papiJobHold.3papi
MLINKS+=	papiJobSubmit.3papi papiJobListFree.3papi
MLINKS+=	papiJobSubmit.3papi papiJobModify.3papi
MLINKS+=	papiJobSubmit.3papi papiJobMove.3papi
MLINKS+=	papiJobSubmit.3papi papiJobPromote.3papi
MLINKS+=	papiJobSubmit.3papi papiJobQuery.3papi
MLINKS+=	papiJobSubmit.3papi papiJobRelease.3papi
MLINKS+=	papiJobSubmit.3papi papiJobRestart.3papi
MLINKS+=	papiJobSubmit.3papi papiJobStreamClose.3papi
MLINKS+=	papiJobSubmit.3papi papiJobStreamOpen.3papi
MLINKS+=	papiJobSubmit.3papi papiJobStreamWrite.3papi
MLINKS+=	papiJobSubmit.3papi papiJobSubmitByReference.3papi
MLINKS+=	papiJobSubmit.3papi papiJobValidate.3papi
MLINKS+=	papiLibrarySupportedCall.3papi papiLibrarySupportedCalls.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterAdd.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterDisable.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterEnable.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterFree.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterGetAttributeList.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterListFree.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterListJobs.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterModify.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterPause.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterPurgeJobs.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterQuery.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterRemove.3papi
MLINKS+=	papiPrintersList.3papi papiPrinterResume.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceDestroy.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceGetAppData.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceGetAttributeList.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceGetEncryption.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceGetPassword.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceGetServiceName.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceGetStatusMessage.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceGetUserName.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceSetAppData.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceSetAuthCB.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceSetEncryption.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceSetPassword.3papi
MLINKS+=	papiServiceCreate.3papi papiServiceSetUserName.3papi

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
