MAN = papiAttributeListAddValue.3papi \
      papiJobSubmit.3papi \
      papiLibrarySupportedCall.3papi \
      papiPrintersList.3papi \
      papiServiceCreate.3papi \
      papiStatusString.3papi


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
