#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TPLDIR = svccfg/templates
TEST = $(TPLDIR)/pg_pattern_type
DESC = config.env stf_description pg_pattern_type.xml
TCS = pg_pattern_type_001 pg_pattern_type_002 pg_pattern_type_003 \
	pg_pattern_type_004 pg_pattern_type_005 pg_pattern_type_006 \
	pg_pattern_type_007

include ../../../Makefile.test
