MAN = acct.h.3head \
      aio.h.3head \
      ar.h.3head \
      archives.h.3head \
      assert.h.3head \
      complex.h.3head \
      cpio.h.3head \
      dirent.h.3head \
      endian.h.3head \
      errno.h.3head \
      fcntl.h.3head \
      fenv.h.3head \
      float.h.3head \
      floatingpoint.h.3head \
      fmtmsg.h.3head \
      fnmatch.h.3head \
      ftw.h.3head \
      glob.h.3head \
      grp.h.3head \
      iconv.h.3head \
      if.h.3head \
      in.h.3head \
      inet.h.3head \
      inttypes.h.3head \
      ipc.h.3head \
      iso646.h.3head \
      langinfo.h.3head \
      libgen.h.3head \
      libintl.h.3head \
      limits.h.3head \
      locale.h.3head \
      math.h.3head \
      mman.h.3head \
      monetary.h.3head \
      mqueue.h.3head \
      msg.h.3head \
      ndbm.h.3head \
      netdb.h.3head \
      nl_types.h.3head \
      poll.h.3head \
      pthread.h.3head \
      pwd.h.3head \
      regex.h.3head \
      resource.h.3head \
      sched.h.3head \
      search.h.3head \
      select.h.3head \
      sem.h.3head \
      semaphore.h.3head \
      setjmp.h.3head \
      shm.h.3head \
      siginfo.h.3head \
      signal.h.3head \
      socket.h.3head \
      spawn.h.3head \
      stat.h.3head \
      statvfs.h.3head \
      stdbool.h.3head \
      stddef.h.3head \
      stdint.h.3head \
      stdio.h.3head \
      stdlib.h.3head \
      string.h.3head \
      strings.h.3head \
      stropts.h.3head \
      syslog.h.3head \
      tar.h.3head \
      tcp.h.3head \
      termios.h.3head \
      tgmath.h.3head \
      time.h.3head \
      timeb.h.3head \
      times.h.3head \
      types.h.3head \
      types32.h.3head \
      ucontext.h.3head \
      uio.h.3head \
      ulimit.h.3head \
      un.h.3head \
      unistd.h.3head \
      utime.h.3head \
      utmpx.h.3head \
      utsname.h.3head \
      values.h.3head \
      wait.h.3head \
      wchar.h.3head \
      wctype.h.3head \
      wordexp.h.3head \
      xlocale.h.3head

MLINKS+=	acct.h.3head acct.3head
MLINKS+=	aio.h.3head aio.3head
MLINKS+=	ar.h.3head ar.3head
MLINKS+=	archives.h.3head archives.3head
MLINKS+=	assert.h.3head assert.3head
MLINKS+=	complex.h.3head complex.3head
MLINKS+=	cpio.h.3head cpio.3head
MLINKS+=	dirent.h.3head dirent.3head
MLINKS+=	errno.h.3head errno.3head
MLINKS+=	fcntl.h.3head fcntl.3head
MLINKS+=	fenv.h.3head fenv.3head
MLINKS+=	float.h.3head float.3head
MLINKS+=	floatingpoint.h.3head floatingpoint.3head
MLINKS+=	fmtmsg.h.3head fmtmsg.3head
MLINKS+=	fnmatch.h.3head fnmatch.3head
MLINKS+=	ftw.h.3head ftw.3head
MLINKS+=	glob.h.3head glob.3head
MLINKS+=	grp.h.3head grp.3head
MLINKS+=	iconv.h.3head iconv.3head
MLINKS+=	if.h.3head if.3head
MLINKS+=	in.h.3head in.3head
MLINKS+=	inet.h.3head inet.3head
MLINKS+=	inttypes.h.3head inttypes.3head
MLINKS+=	ipc.h.3head ipc.3head
MLINKS+=	iso646.h.3head iso646.3head
MLINKS+=	langinfo.h.3head langinfo.3head
MLINKS+=	libgen.h.3head libgen.3head
MLINKS+=	libintl.h.3head libintl.3head
MLINKS+=	limits.h.3head limits.3head
MLINKS+=	locale.h.3head locale.3head
MLINKS+=	math.h.3head math.3head
MLINKS+=	mman.h.3head mman.3head
MLINKS+=	monetary.h.3head monetary.3head
MLINKS+=	mqueue.h.3head mqueue.3head
MLINKS+=	msg.h.3head msg.3head
MLINKS+=	ndbm.h.3head ndbm.3head
MLINKS+=	netdb.h.3head netdb.3head
MLINKS+=	nl_types.h.3head nl_types.3head
MLINKS+=	poll.h.3head poll.3head
MLINKS+=	pthread.h.3head pthread.3head
MLINKS+=	pwd.h.3head pwd.3head
MLINKS+=	regex.h.3head regex.3head
MLINKS+=	resource.h.3head resource.3head
MLINKS+=	sched.h.3head sched.3head
MLINKS+=	search.h.3head search.3head
MLINKS+=	select.h.3head select.3head
MLINKS+=	sem.h.3head sem.3head
MLINKS+=	semaphore.h.3head semaphore.3head
MLINKS+=	setjmp.h.3head setjmp.3head
MLINKS+=	shm.h.3head shm.3head
MLINKS+=	siginfo.h.3head siginfo.3head
MLINKS+=	signal.h.3head signal.3head
MLINKS+=	socket.h.3head socket.3head
MLINKS+=	spawn.h.3head spawn.3head
MLINKS+=	stat.h.3head stat.3head
MLINKS+=	statvfs.h.3head statvfs.3head
MLINKS+=	stdbool.h.3head stdbool.3head
MLINKS+=	stddef.h.3head stddef.3head
MLINKS+=	stdint.h.3head stdint.3head
MLINKS+=	stdio.h.3head stdio.3head
MLINKS+=	stdlib.h.3head stdlib.3head
MLINKS+=	string.h.3head string.3head
MLINKS+=	strings.h.3head strings.3head
MLINKS+=	stropts.h.3head stropts.3head
MLINKS+=	syslog.h.3head syslog.3head
MLINKS+=	tar.h.3head tar.3head
MLINKS+=	tcp.h.3head tcp.3head
MLINKS+=	termios.h.3head termios.3head
MLINKS+=	tgmath.h.3head tgmath.3head
MLINKS+=	time.h.3head time.3head
MLINKS+=	timeb.h.3head timeb.3head
MLINKS+=	times.h.3head times.3head
MLINKS+=	types.h.3head types.3head
MLINKS+=	types32.h.3head types32.3head
MLINKS+=	ucontext.h.3head ucontext.3head
MLINKS+=	uio.h.3head uio.3head
MLINKS+=	ulimit.h.3head ulimit.3head
MLINKS+=	un.h.3head un.3head
MLINKS+=	unistd.h.3head unistd.3head
MLINKS+=	utime.h.3head utime.3head
MLINKS+=	utmpx.h.3head utmpx.3head
MLINKS+=	utsname.h.3head utsname.3head
MLINKS+=	values.h.3head values.3head
MLINKS+=	wait.h.3head wait.3head
MLINKS+=	wchar.h.3head wchar.3head
MLINKS+=	wctype.h.3head wctype.3head
MLINKS+=	wordexp.h.3head wordexp.3head
MLINKS+=	xlocale.h.3head xlocale.3head

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
