#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = svc.startd/methods
DESC = stf_description
TCS =

include ../../Makefile.test

.PARALLEL: $(SUBDIRS)

SUBDIRS = assertion_001 assertion_002 assertion_003 assertion_004 \
	assertion_005 assertion_006 assertion_007 assertion_008 \
	assertion_009 assertion_010 assertion_011 assertion_012 \
	assertion_013 assertion_014 assertion_015 assertion_016 \
	assertion_017 assertion_018 assertion_019 assertion_020 \
	assertion_021 assertion_022 assertion_023 assertion_024 \
	assertion_025 assertion_026 assertion_027 assertion_028 \
	assertion_029 assertion_030 assertion_033 assertion_034 \
	assertion_035 assertion_036 assertion_037 assertion_038 \
	assertion_039 assertion_040 assertion_041 assertion_042 \
	assertion_043 assertion_044

include $(SRC)/test/Makefile.com
