.\"
.\" The contents of this file are subject to the terms of the Common
.\" Development and Distribution License (the "License").  You may not use
.\" this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or
.\" http://www.opensolaris.org/os/licensing.  See the License for the
.\" specific language governing permissions and limitations under the
.\" License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each file
.\" and include the License file at usr/src/OPENSOLARIS.LICENSE.  If
.\" applicable, add the following below this CDDL HEADER, with the fields
.\" enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" Copyright (c) 2009, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright 2026 OmniOS Community Edition (OmniOSce) Association.
.\"
.Dd October 3, 2026
.Dt CRYPT_BSDBF 7
.Os
.Sh NAME
.Nm crypt_bsdbf
.Nd password hashing module using Blowfish cryptographic algorithm
.Sh SYNOPSIS
.Pa /usr/lib/security/$ISA/crypt_bsdbf.so
.Sh DESCRIPTION
The
.Nm
module is a one-way password hashing module for use with
.Xr crypt 3C
that uses the Blowfish cryptographic algorithm.
The algorithm identifiers for
.Xr crypt.conf 5
and
.Xr policy.conf 5
are
.Sy 2a
and
.Sy 2b .
The module generates
.Sy 2b
salts for either identifier and verifies hashes of both types.
.Pp
The maximum password length for
.Nm
is 72 characters.
.Sh MT-LEVEL
.Sy MT-Safe
.Sh SEE ALSO
.Xr passwd 1 ,
.Xr crypt 3C ,
.Xr crypt_genhash_impl 3C ,
.Xr crypt_gensalt 3C ,
.Xr crypt_gensalt_impl 3C ,
.Xr getpassphrase 3C ,
.Xr crypt.conf 5 ,
.Xr passwd 5 ,
.Xr policy.conf 5 ,
.Xr attributes 7
