MAN = getprojent.3project \
      project_walk.3project \
      setproject.3project

MLINKS+=	getprojent.3project endprojent.3project
MLINKS+=	getprojent.3project fgetprojent.3project
MLINKS+=	getprojent.3project getdefaultproj.3project
MLINKS+=	getprojent.3project getprojbyid.3project
MLINKS+=	getprojent.3project getprojbyname.3project
MLINKS+=	getprojent.3project getprojidbyname.3project
MLINKS+=	getprojent.3project inproj.3project
MLINKS+=	getprojent.3project setprojent.3project

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
