#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TPLDIR = svccfg/templates
TEST = $(TPLDIR)/prop_pattern_description
DESC = config.env stf_description prop_pattern_description.xml \
	prop_pattern_loctext.xml
TCS = prop_pattern_description_001 prop_pattern_description_002 \
	prop_pattern_description_003 prop_pattern_description_004 \
	prop_pattern_description_005 prop_pattern_description_006 \
	prop_pattern_description_007 prop_pattern_description_008 \
	prop_pattern_description_009 prop_pattern_description_010 \
	prop_pattern_description_011

include ../../../Makefile.test
