#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = basic_ops/setattr
SHRSRC = SETATTR.env SETATTR.flist
TCS = runtests
TCLSRC = setattr_neg01 setattr_neg02 setattr_neg03 setattr_neg04 \
	setattr_neg06 setattr_pos01 setattr_pos02 setattr_pos03

include ../../Makefile.test
