#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = acl/nontrivial
STFDESC = stf_description
PROGS = acl_chmod_compact_pos001 acl_chmod_delete_pos001 \
	acl_chmod_inherit_pos001 acl_chmod_neg001 \
	acl_chmod_rwacl_pos001 acl_chmod_rwx_pos001 \
	acl_chmod_rwx_pos002 acl_chmod_rwx_pos003 \
	acl_chmod_rwx_pos004 acl_chmod_xattr_pos001 \
	acl_chmod_xattr_pos002 acl_cp_pos001 acl_cp_pos002 \
	acl_cpio_pos001 acl_cpio_pos002 acl_find_pos001 \
	acl_ls_pos001 acl_mv_pos001 acl_tar_pos001 acl_tar_pos002
	
include ../../Makefile.test
