MAN = ASSERT.9f \
      Intro.9f \
      OTHERQ.9f \
      RD.9f \
      SAMESTR.9f \
      STRUCT_DECL.9f \
      WR.9f \
      adjmsg.9f \
      allocb.9f \
      atomic_add.9f \
      atomic_and.9f \
      atomic_bits.9f \
      atomic_cas.9f \
      atomic_dec.9f \
      atomic_inc.9f \
      atomic_ops.9f \
      atomic_or.9f \
      atomic_swap.9f \
      avl.9f \
      backq.9f \
      bcanput.9f \
      bcmp.9f \
      bcopy.9f \
      bioclone.9f \
      biodone.9f \
      bioerror.9f \
      biofini.9f \
      bioinit.9f \
      biomodified.9f \
      bioreset.9f \
      biosize.9f \
      biowait.9f \
      bp_copyin.9f \
      bp_copyout.9f \
      bp_mapin.9f \
      bp_mapout.9f \
      btop.9f \
      btopr.9f \
      bufcall.9f \
      bzero.9f \
      canput.9f \
      canputnext.9f \
      clrbuf.9f \
      cmn_err.9f \
      condvar.9f \
      copyb.9f \
      copyin.9f \
      copymsg.9f \
      copyout.9f \
      datamsg.9f \
      ddi_add_event_handler.9f \
      ddi_add_intr.9f \
      ddi_add_softintr.9f \
      ddi_binding_name.9f \
      ddi_btop.9f \
      ddi_can_receive_sig.9f \
      ddi_cb_register.9f \
      ddi_check_acc_handle.9f \
      ddi_copyin.9f \
      ddi_copyout.9f \
      ddi_create_minor_node.9f \
      ddi_cred.9f \
      ddi_dev_is_needed.9f \
      ddi_dev_is_sid.9f \
      ddi_dev_nintrs.9f \
      ddi_dev_nregs.9f \
      ddi_dev_regsize.9f \
      ddi_dev_report_fault.9f \
      ddi_device_copy.9f \
      ddi_device_zero.9f \
      ddi_devid_compare.9f \
      ddi_dma_addr_bind_handle.9f \
      ddi_dma_alloc_handle.9f \
      ddi_dma_buf_bind_handle.9f \
      ddi_dma_burstsizes.9f \
      ddi_dma_free_handle.9f \
      ddi_dma_getwin.9f \
      ddi_dma_mem_alloc.9f \
      ddi_dma_mem_free.9f \
      ddi_dma_nextcookie.9f \
      ddi_dma_numwin.9f \
      ddi_dma_set_sbus64.9f \
      ddi_dma_sync.9f \
      ddi_dma_unbind_handle.9f \
      ddi_dmae.9f \
      ddi_driver_major.9f \
      ddi_driver_name.9f \
      ddi_enter_critical.9f \
      ddi_ffs.9f \
      ddi_fm_acc_err_clear.9f \
      ddi_fm_acc_err_get.9f \
      ddi_fm_ereport_post.9f \
      ddi_fm_handler_register.9f \
      ddi_fm_init.9f \
      ddi_fm_service_impact.9f \
      ddi_get8.9f \
      ddi_get_cred.9f \
      ddi_get_devstate.9f \
      ddi_get_driver_private.9f \
      ddi_get_eventcookie.9f \
      ddi_get_instance.9f \
      ddi_get_kt_did.9f \
      ddi_get_lbolt.9f \
      ddi_get_parent.9f \
      ddi_get_pid.9f \
      ddi_get_time.9f \
      ddi_getiminor.9f \
      ddi_in_panic.9f \
      ddi_intr_add_handler.9f \
      ddi_intr_add_softint.9f \
      ddi_intr_alloc.9f \
      ddi_intr_dup_handler.9f \
      ddi_intr_enable.9f \
      ddi_intr_get_cap.9f \
      ddi_intr_get_hilevel_pri.9f \
      ddi_intr_get_nintrs.9f \
      ddi_intr_get_pending.9f \
      ddi_intr_get_pri.9f \
      ddi_intr_get_supported_types.9f \
      ddi_intr_hilevel.9f \
      ddi_intr_set_mask.9f \
      ddi_intr_set_nreq.9f \
      ddi_io_get8.9f \
      ddi_io_put8.9f \
      ddi_io_rep_get8.9f \
      ddi_io_rep_put8.9f \
      ddi_log_sysevent.9f \
      ddi_map_regs.9f \
      ddi_mem_get8.9f \
      ddi_mem_put8.9f \
      ddi_mem_rep_get8.9f \
      ddi_mem_rep_put8.9f \
      ddi_mmap_get_model.9f \
      ddi_model_convert_from.9f \
      ddi_modopen.9f \
      ddi_no_info.9f \
      ddi_node_name.9f \
      ddi_peek.9f \
      ddi_periodic_add.9f \
      ddi_periodic_delete.9f \
      ddi_poke.9f \
      ddi_prop_create.9f \
      ddi_prop_exists.9f \
      ddi_prop_get_int.9f \
      ddi_prop_lookup.9f \
      ddi_prop_op.9f \
      ddi_prop_update.9f \
      ddi_put8.9f \
      ddi_regs_map_free.9f \
      ddi_regs_map_setup.9f \
      ddi_remove_event_handler.9f \
      ddi_remove_minor_node.9f \
      ddi_removing_power.9f \
      ddi_rep_get8.9f \
      ddi_rep_put8.9f \
      ddi_report_dev.9f \
      ddi_root_node.9f \
      ddi_segmap.9f \
      ddi_slaveonly.9f \
      ddi_soft_state.9f \
      ddi_strtol.9f \
      ddi_strtoll.9f \
      ddi_strtoul.9f \
      ddi_umem_alloc.9f \
      ddi_umem_iosetup.9f \
      ddi_umem_lock.9f \
      delay.9f \
      devfs_clean.9f \
      devmap_default_access.9f \
      devmap_devmem_setup.9f \
      devmap_do_ctxmgt.9f \
      devmap_set_ctx_timeout.9f \
      devmap_setup.9f \
      devmap_unload.9f \
      disksort.9f \
      dlbindack.9f \
      drv_getparm.9f \
      drv_hztousec.9f \
      drv_priv.9f \
      drv_usectohz.9f \
      drv_usecwait.9f \
      dupb.9f \
      dupmsg.9f \
      enableok.9f \
      esballoc.9f \
      esbbcall.9f \
      firmload.9f \
      flushband.9f \
      flushq.9f \
      freeb.9f \
      freemsg.9f \
      freerbuf.9f \
      freezestr.9f \
      get_pktiopb.9f \
      geterror.9f \
      gethrtime.9f \
      getmajor.9f \
      getminor.9f \
      getq.9f \
      getrbuf.9f \
      gld.9f \
      hook_alloc.9f \
      hook_free.9f \
      id32_alloc.9f \
      id_space.9f \
      inb.9f \
      insq.9f \
      kiconv.9f \
      kiconv_close.9f \
      kiconv_open.9f \
      kiconvstr.9f \
      kmem_alloc.9f \
      kmem_cache_create.9f \
      kstat_create.9f \
      kstat_delete.9f \
      kstat_install.9f \
      kstat_named_init.9f \
      kstat_queue.9f \
      ldi_add_event_handler.9f \
      ldi_aread.9f \
      ldi_devmap.9f \
      ldi_dump.9f \
      ldi_ev_finalize.9f \
      ldi_ev_get_cookie.9f \
      ldi_ev_get_type.9f \
      ldi_ev_notify.9f \
      ldi_ev_register_callbacks.9f \
      ldi_ev_remove_callbacks.9f \
      ldi_get_dev.9f \
      ldi_get_eventcookie.9f \
      ldi_get_size.9f \
      ldi_ident_from_dev.9f \
      ldi_ioctl.9f \
      ldi_open_by_dev.9f \
      ldi_poll.9f \
      ldi_prop_exists.9f \
      ldi_prop_get_int.9f \
      ldi_prop_lookup_int_array.9f \
      ldi_putmsg.9f \
      ldi_read.9f \
      ldi_remove_event_handler.9f \
      ldi_strategy.9f \
      linkb.9f \
      list_create.9f \
      mac_alloc.9f \
      mac_hcksum_get.9f \
      mac_init_ops.9f \
      mac_link_update.9f \
      mac_lso_get.9f \
      mac_maxsdu_update.9f \
      mac_prop_info.9f \
      mac_register.9f \
      mac_rx.9f \
      mac_tx_update.9f \
      makecom.9f \
      makedevice.9f \
      max.9f \
      mcopyin.9f \
      mcopymsg.9f \
      mcopyout.9f \
      membar_ops.9f \
      memchr.9f \
      merror.9f \
      mexchange.9f \
      min.9f \
      mioc2ack.9f \
      miocack.9f \
      miocnak.9f \
      miocpullup.9f \
      mkiocb.9f \
      mod_install.9f \
      msgdsize.9f \
      msgpullup.9f \
      msgsize.9f \
      mt-streams.9f \
      mutex.9f \
      net_event_notify_register.9f \
      net_getifname.9f \
      net_getlifaddr.9f \
      net_getmtu.9f \
      net_getnetid.9f \
      net_getpmtuenabled.9f \
      net_hook_register.9f \
      net_hook_unregister.9f \
      net_inject.9f \
      net_inject_alloc.9f \
      net_inject_free.9f \
      net_instance_alloc.9f \
      net_instance_free.9f \
      net_instance_notify_register.9f \
      net_instance_register.9f \
      net_instance_unregister.9f \
      net_ispartialchecksum.9f \
      net_isvalidchecksum.9f \
      net_kstat_create.9f \
      net_kstat_delete.9f \
      net_lifgetnext.9f \
      net_netidtozonid.9f \
      net_phygetnext.9f \
      net_phylookup.9f \
      net_protocol_lookup.9f \
      net_protocol_notify_register.9f \
      net_protocol_release.9f \
      net_protocol_walk.9f \
      net_routeto.9f \
      net_zoneidtonetid.9f \
      netinfo.9f \
      nochpoll.9f \
      nodev.9f \
      noenable.9f \
      nulldev.9f \
      nvlist_add_boolean.9f \
      nvlist_alloc.9f \
      nvlist_lookup_boolean.9f \
      nvlist_lookup_nvpair.9f \
      nvlist_next_nvpair.9f \
      nvlist_remove.9f \
      nvpair_value_byte.9f \
      outb.9f \
      pci_config_get8.9f \
      pci_config_setup.9f \
      pci_ereport_setup.9f \
      pci_report_pmcap.9f \
      pci_save_config_regs.9f \
      physio.9f \
      pm_busy_component.9f \
      pm_power_has_changed.9f \
      pm_raise_power.9f \
      pm_trans_check.9f \
      pollhead_clean.9f \
      pollwakeup.9f \
      priv_getbyname.9f \
      priv_policy.9f \
      proc_signal.9f \
      ptob.9f \
      pullupmsg.9f \
      put.9f \
      putbq.9f \
      putctl.9f \
      putctl1.9f \
      putnext.9f \
      putnextctl.9f \
      putnextctl1.9f \
      putq.9f \
      qassociate.9f \
      qbufcall.9f \
      qenable.9f \
      qprocson.9f \
      qreply.9f \
      qsize.9f \
      qtimeout.9f \
      qunbufcall.9f \
      quntimeout.9f \
      qwait.9f \
      qwriter.9f \
      rmalloc.9f \
      rmalloc_wait.9f \
      rmallocmap.9f \
      rmfree.9f \
      rmvb.9f \
      rmvq.9f \
      rwlock.9f \
      scsi_abort.9f \
      scsi_alloc_consistent_buf.9f \
      scsi_cname.9f \
      scsi_destroy_pkt.9f \
      scsi_dmaget.9f \
      scsi_errmsg.9f \
      scsi_ext_sense_fields.9f \
      scsi_find_sense_descr.9f \
      scsi_free_consistent_buf.9f \
      scsi_get_device_type_scsi_options.9f \
      scsi_get_device_type_string.9f \
      scsi_hba_attach_setup.9f \
      scsi_hba_init.9f \
      scsi_hba_lookup_capstr.9f \
      scsi_hba_pkt_alloc.9f \
      scsi_hba_pkt_comp.9f \
      scsi_hba_probe.9f \
      scsi_hba_tran_alloc.9f \
      scsi_ifgetcap.9f \
      scsi_init_pkt.9f \
      scsi_log.9f \
      scsi_pktalloc.9f \
      scsi_poll.9f \
      scsi_probe.9f \
      scsi_reset.9f \
      scsi_reset_notify.9f \
      scsi_sense_key.9f \
      scsi_setup_cdb.9f \
      scsi_slave.9f \
      scsi_sync_pkt.9f \
      scsi_transport.9f \
      scsi_unprobe.9f \
      scsi_validate_sense.9f \
      scsi_vu_errmsg.9f \
      semaphore.9f \
      sprintf.9f \
      stoi.9f \
      string.9f \
      strlog.9f \
      strqget.9f \
      strqset.9f \
      swab.9f \
      taskq.9f \
      testb.9f \
      timeout.9f \
      u8_strcmp.9f \
      u8_textprep_str.9f \
      u8_validate.9f \
      uconv_u16tou32.9f \
      uiomove.9f \
      unbufcall.9f \
      unlinkb.9f \
      untimeout.9f \
      ureadc.9f \
      usb_alloc_request.9f \
      usb_client_attach.9f \
      usb_clr_feature.9f \
      usb_create_pm_components.9f \
      usb_get_addr.9f \
      usb_get_alt_if.9f \
      usb_get_cfg.9f \
      usb_get_current_frame_number.9f \
      usb_get_dev_data.9f \
      usb_get_max_pkts_per_isoc_request.9f \
      usb_get_status.9f \
      usb_get_string_descr.9f \
      usb_handle_remote_wakeup.9f \
      usb_lookup_ep_data.9f \
      usb_parse_data.9f \
      usb_pipe_bulk_xfer.9f \
      usb_pipe_close.9f \
      usb_pipe_ctrl_xfer.9f \
      usb_pipe_drain_reqs.9f \
      usb_pipe_get_max_bulk_transfer_size.9f \
      usb_pipe_get_state.9f \
      usb_pipe_intr_xfer.9f \
      usb_pipe_isoc_xfer.9f \
      usb_pipe_open.9f \
      usb_pipe_reset.9f \
      usb_pipe_set_private.9f \
      usb_register_hotplug_cbs.9f \
      usb_reset_device.9f \
      uwritec.9f \
      va_arg.9f

MLINKS+=	ASSERT.9f assert.9f
MLINKS+=	Intro.9f intro.9f
MLINKS+=	OTHERQ.9f otherq.9f
MLINKS+=	RD.9f rd.9f
MLINKS+=	SAMESTR.9f samestr.9f
MLINKS+=	STRUCT_DECL.9f SIZEOF_PTR.9f
MLINKS+=	STRUCT_DECL.9f SIZEOF_STRUCT.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_BUF.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_FADDR.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_FGET.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_FGETP.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_FSET.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_FSETP.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_HANDLE.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_INIT.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_SET_HANDLE.9f
MLINKS+=	STRUCT_DECL.9f STRUCT_SIZE.9f
MLINKS+=	WR.9f wr.9f
MLINKS+=	atomic_add.9f atomic_add_16.9f
MLINKS+=	atomic_add.9f atomic_add_16_nv.9f
MLINKS+=	atomic_add.9f atomic_add_32.9f
MLINKS+=	atomic_add.9f atomic_add_32_nv.9f
MLINKS+=	atomic_add.9f atomic_add_64.9f
MLINKS+=	atomic_add.9f atomic_add_64_nv.9f
MLINKS+=	atomic_add.9f atomic_add_8.9f
MLINKS+=	atomic_add.9f atomic_add_8_nv.9f
MLINKS+=	atomic_add.9f atomic_add_char.9f
MLINKS+=	atomic_add.9f atomic_add_char_nv.9f
MLINKS+=	atomic_add.9f atomic_add_int.9f
MLINKS+=	atomic_add.9f atomic_add_int_nv.9f
MLINKS+=	atomic_add.9f atomic_add_long.9f
MLINKS+=	atomic_add.9f atomic_add_long_nv.9f
MLINKS+=	atomic_add.9f atomic_add_ptr.9f
MLINKS+=	atomic_add.9f atomic_add_ptr_nv.9f
MLINKS+=	atomic_add.9f atomic_add_short.9f
MLINKS+=	atomic_add.9f atomic_add_short_nv.9f
MLINKS+=	atomic_and.9f atomic_and_16.9f
MLINKS+=	atomic_and.9f atomic_and_16_nv.9f
MLINKS+=	atomic_and.9f atomic_and_32.9f
MLINKS+=	atomic_and.9f atomic_and_32_nv.9f
MLINKS+=	atomic_and.9f atomic_and_64.9f
MLINKS+=	atomic_and.9f atomic_and_64_nv.9f
MLINKS+=	atomic_and.9f atomic_and_8.9f
MLINKS+=	atomic_and.9f atomic_and_8_nv.9f
MLINKS+=	atomic_and.9f atomic_and_uchar.9f
MLINKS+=	atomic_and.9f atomic_and_uchar_nv.9f
MLINKS+=	atomic_and.9f atomic_and_uint.9f
MLINKS+=	atomic_and.9f atomic_and_uint_nv.9f
MLINKS+=	atomic_and.9f atomic_and_ulong.9f
MLINKS+=	atomic_and.9f atomic_and_ulong_nv.9f
MLINKS+=	atomic_and.9f atomic_and_ushort.9f
MLINKS+=	atomic_and.9f atomic_and_ushort_nv.9f
MLINKS+=	atomic_bits.9f atomic_clear_long_excl.9f
MLINKS+=	atomic_bits.9f atomic_set_long_excl.9f
MLINKS+=	atomic_cas.9f atomic_cas_16.9f
MLINKS+=	atomic_cas.9f atomic_cas_32.9f
MLINKS+=	atomic_cas.9f atomic_cas_64.9f
MLINKS+=	atomic_cas.9f atomic_cas_8.9f
MLINKS+=	atomic_cas.9f atomic_cas_ptr.9f
MLINKS+=	atomic_cas.9f atomic_cas_uchar.9f
MLINKS+=	atomic_cas.9f atomic_cas_uint.9f
MLINKS+=	atomic_cas.9f atomic_cas_ulong.9f
MLINKS+=	atomic_cas.9f atomic_cas_ushort.9f
MLINKS+=	atomic_dec.9f atomic_dec_16.9f
MLINKS+=	atomic_dec.9f atomic_dec_16_nv.9f
MLINKS+=	atomic_dec.9f atomic_dec_32.9f
MLINKS+=	atomic_dec.9f atomic_dec_32_nv.9f
MLINKS+=	atomic_dec.9f atomic_dec_64.9f
MLINKS+=	atomic_dec.9f atomic_dec_64_nv.9f
MLINKS+=	atomic_dec.9f atomic_dec_8.9f
MLINKS+=	atomic_dec.9f atomic_dec_8_nv.9f
MLINKS+=	atomic_dec.9f atomic_dec_ptr.9f
MLINKS+=	atomic_dec.9f atomic_dec_ptr_nv.9f
MLINKS+=	atomic_dec.9f atomic_dec_uchar.9f
MLINKS+=	atomic_dec.9f atomic_dec_uchar_nv.9f
MLINKS+=	atomic_dec.9f atomic_dec_uint.9f
MLINKS+=	atomic_dec.9f atomic_dec_uint_nv.9f
MLINKS+=	atomic_dec.9f atomic_dec_ulong.9f
MLINKS+=	atomic_dec.9f atomic_dec_ulong_nv.9f
MLINKS+=	atomic_dec.9f atomic_dec_ushort.9f
MLINKS+=	atomic_dec.9f atomic_dec_ushort_nv.9f
MLINKS+=	atomic_inc.9f atomic_inc_16.9f
MLINKS+=	atomic_inc.9f atomic_inc_16_nv.9f
MLINKS+=	atomic_inc.9f atomic_inc_32.9f
MLINKS+=	atomic_inc.9f atomic_inc_32_nv.9f
MLINKS+=	atomic_inc.9f atomic_inc_64.9f
MLINKS+=	atomic_inc.9f atomic_inc_64_nv.9f
MLINKS+=	atomic_inc.9f atomic_inc_8.9f
MLINKS+=	atomic_inc.9f atomic_inc_8_nv.9f
MLINKS+=	atomic_inc.9f atomic_inc_ptr.9f
MLINKS+=	atomic_inc.9f atomic_inc_ptr_nv.9f
MLINKS+=	atomic_inc.9f atomic_inc_uchar.9f
MLINKS+=	atomic_inc.9f atomic_inc_uchar_nv.9f
MLINKS+=	atomic_inc.9f atomic_inc_uint.9f
MLINKS+=	atomic_inc.9f atomic_inc_uint_nv.9f
MLINKS+=	atomic_inc.9f atomic_inc_ulong.9f
MLINKS+=	atomic_inc.9f atomic_inc_ulong_nv.9f
MLINKS+=	atomic_inc.9f atomic_inc_ushort.9f
MLINKS+=	atomic_inc.9f atomic_inc_ushort_nv.9f
MLINKS+=	atomic_or.9f atomic_or_16.9f
MLINKS+=	atomic_or.9f atomic_or_16_nv.9f
MLINKS+=	atomic_or.9f atomic_or_32.9f
MLINKS+=	atomic_or.9f atomic_or_32_nv.9f
MLINKS+=	atomic_or.9f atomic_or_64.9f
MLINKS+=	atomic_or.9f atomic_or_64_nv.9f
MLINKS+=	atomic_or.9f atomic_or_8.9f
MLINKS+=	atomic_or.9f atomic_or_8_nv.9f
MLINKS+=	atomic_or.9f atomic_or_uchar.9f
MLINKS+=	atomic_or.9f atomic_or_uchar_nv.9f
MLINKS+=	atomic_or.9f atomic_or_uint.9f
MLINKS+=	atomic_or.9f atomic_or_uint_nv.9f
MLINKS+=	atomic_or.9f atomic_or_ulong.9f
MLINKS+=	atomic_or.9f atomic_or_ulong_nv.9f
MLINKS+=	atomic_or.9f atomic_or_ushort.9f
MLINKS+=	atomic_or.9f atomic_or_ushort_nv.9f
MLINKS+=	atomic_swap.9f atomic_swap_16.9f
MLINKS+=	atomic_swap.9f atomic_swap_32.9f
MLINKS+=	atomic_swap.9f atomic_swap_64.9f
MLINKS+=	atomic_swap.9f atomic_swap_8.9f
MLINKS+=	atomic_swap.9f atomic_swap_ptr.9f
MLINKS+=	atomic_swap.9f atomic_swap_uchar.9f
MLINKS+=	atomic_swap.9f atomic_swap_uint.9f
MLINKS+=	atomic_swap.9f atomic_swap_ulong.9f
MLINKS+=	atomic_swap.9f atomic_swap_ushort.9f
MLINKS+=	avl.9f avl_add.9f
MLINKS+=	avl.9f avl_create.9f
MLINKS+=	avl.9f avl_destroy.9f
MLINKS+=	avl.9f avl_destroy_nodes.9f
MLINKS+=	avl.9f avl_find.9f
MLINKS+=	avl.9f avl_first.9f
MLINKS+=	avl.9f avl_insert.9f
MLINKS+=	avl.9f avl_insert_here.9f
MLINKS+=	avl.9f avl_is_empty.9f
MLINKS+=	avl.9f avl_last.9f
MLINKS+=	avl.9f avl_nearest.9f
MLINKS+=	avl.9f avl_numnodes.9f
MLINKS+=	avl.9f avl_remove.9f
MLINKS+=	avl.9f avl_swap.9f
MLINKS+=	avl.9f AVL_NEXT.9f
MLINKS+=	avl.9f AVL_PREV.9f
MLINKS+=	cmn_err.9f dev_err.9f
MLINKS+=	cmn_err.9f vcmn_err.9f
MLINKS+=	cmn_err.9f vzcmn_err.9f
MLINKS+=	cmn_err.9f zcmn_err.9f
MLINKS+=	condvar.9f cv_broadcast.9f
MLINKS+=	condvar.9f cv_destroy.9f
MLINKS+=	condvar.9f cv_init.9f
MLINKS+=	condvar.9f cv_reltimedwait.9f
MLINKS+=	condvar.9f cv_reltimedwait_sig.9f
MLINKS+=	condvar.9f cv_signal.9f
MLINKS+=	condvar.9f cv_timedwait.9f
MLINKS+=	condvar.9f cv_timedwait_sig.9f
MLINKS+=	condvar.9f cv_wait.9f
MLINKS+=	condvar.9f cv_wait_sig.9f
MLINKS+=	ddi_add_intr.9f ddi_get_iblock_cookie.9f
MLINKS+=	ddi_add_intr.9f ddi_remove_intr.9f
MLINKS+=	ddi_add_softintr.9f ddi_get_soft_iblock_cookie.9f
MLINKS+=	ddi_add_softintr.9f ddi_remove_softintr.9f
MLINKS+=	ddi_add_softintr.9f ddi_trigger_softintr.9f
MLINKS+=	ddi_binding_name.9f ddi_get_name.9f
MLINKS+=	ddi_btop.9f ddi_btopr.9f
MLINKS+=	ddi_btop.9f ddi_ptob.9f
MLINKS+=	ddi_cb_register.9f ddi_cb_unregister.9f
MLINKS+=	ddi_check_acc_handle.9f ddi_check_dma_handle.9f
MLINKS+=	canputnext.9f bcanputnext.9f
MLINKS+=	ddi_cred.9f crgetgid.9f
MLINKS+=	ddi_cred.9f crgetgroups.9f
MLINKS+=	ddi_cred.9f crgetngroups.9f
MLINKS+=	ddi_cred.9f crgetrgid.9f
MLINKS+=	ddi_cred.9f crgetruid.9f
MLINKS+=	ddi_cred.9f crgetsgid.9f
MLINKS+=	ddi_cred.9f crgetsuid.9f
MLINKS+=	ddi_cred.9f crgetuid.9f
MLINKS+=	ddi_cred.9f crgetzoneid.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_free.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_get.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_init.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_register.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_sizeof.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_str_decode.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_str_encode.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_str_free.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_unregister.9f
MLINKS+=	ddi_devid_compare.9f ddi_devid_valid.9f
MLINKS+=	ddi_dmae.9f ddi_dmae_1stparty.9f
MLINKS+=	ddi_dmae.9f ddi_dmae_alloc.9f
MLINKS+=	ddi_dmae.9f ddi_dmae_disable.9f
MLINKS+=	ddi_dmae.9f ddi_dmae_enable.9f
MLINKS+=	ddi_dmae.9f ddi_dmae_getattr.9f
MLINKS+=	ddi_dmae.9f ddi_dmae_getcnt.9f
MLINKS+=	ddi_dmae.9f ddi_dmae_prog.9f
MLINKS+=	ddi_dmae.9f ddi_dmae_release.9f
MLINKS+=	ddi_dmae.9f ddi_dmae_stop.9f
MLINKS+=	ddi_enter_critical.9f ddi_exit_critical.9f
MLINKS+=	ddi_ffs.9f ddi_fls.9f
MLINKS+=	ddi_fm_acc_err_clear.9f ddi_fm_dma_err_clear.9f
MLINKS+=	ddi_fm_acc_err_get.9f ddi_fm_dma_err_get.9f
MLINKS+=	ddi_fm_handler_register.9f ddi_fm_handler_unregister.9f
MLINKS+=	ddi_fm_init.9f ddi_fm_capable.9f
MLINKS+=	ddi_fm_init.9f ddi_fm_fini.9f
MLINKS+=	ddi_get8.9f ddi_get16.9f
MLINKS+=	ddi_get8.9f ddi_get32.9f
MLINKS+=	ddi_get8.9f ddi_get64.9f
MLINKS+=	ddi_get8.9f ddi_getb.9f
MLINKS+=	ddi_get8.9f ddi_getl.9f
MLINKS+=	ddi_get8.9f ddi_getll.9f
MLINKS+=	ddi_get8.9f ddi_getw.9f
MLINKS+=	ddi_get_driver_private.9f ddi_set_driver_private.9f
MLINKS+=	ddi_get_lbolt.9f ddi_get_lbolt64.9f
MLINKS+=	ddi_intr_add_handler.9f ddi_intr_remove_handler.9f
MLINKS+=	ddi_intr_add_softint.9f ddi_intr_get_softint_pri.9f
MLINKS+=	ddi_intr_add_softint.9f ddi_intr_remove_softint.9f
MLINKS+=	ddi_intr_add_softint.9f ddi_intr_set_softint_pri.9f
MLINKS+=	ddi_intr_add_softint.9f ddi_intr_trigger_softint.9f
MLINKS+=	ddi_intr_alloc.9f ddi_intr_free.9f
MLINKS+=	ddi_intr_enable.9f ddi_intr_block_disable.9f
MLINKS+=	ddi_intr_enable.9f ddi_intr_block_enable.9f
MLINKS+=	ddi_intr_enable.9f ddi_intr_disable.9f
MLINKS+=	ddi_intr_get_cap.9f ddi_intr_set_cap.9f
MLINKS+=	ddi_intr_get_nintrs.9f ddi_intr_get_navail.9f
MLINKS+=	ddi_intr_get_pri.9f ddi_intr_set_pri.9f
MLINKS+=	ddi_intr_set_mask.9f ddi_intr_clr_mask.9f
MLINKS+=	ddi_io_get8.9f ddi_io_get16.9f
MLINKS+=	ddi_io_get8.9f ddi_io_get32.9f
MLINKS+=	ddi_io_get8.9f ddi_io_getb.9f
MLINKS+=	ddi_io_get8.9f ddi_io_getl.9f
MLINKS+=	ddi_io_get8.9f ddi_io_getw.9f
MLINKS+=	ddi_io_put8.9f ddi_io_put16.9f
MLINKS+=	ddi_io_put8.9f ddi_io_put32.9f
MLINKS+=	ddi_io_put8.9f ddi_io_putb.9f
MLINKS+=	ddi_io_put8.9f ddi_io_putl.9f
MLINKS+=	ddi_io_put8.9f ddi_io_putw.9f
MLINKS+=	ddi_io_rep_get8.9f ddi_io_rep_get16.9f
MLINKS+=	ddi_io_rep_get8.9f ddi_io_rep_get32.9f
MLINKS+=	ddi_io_rep_get8.9f ddi_io_rep_getb.9f
MLINKS+=	ddi_io_rep_get8.9f ddi_io_rep_getl.9f
MLINKS+=	ddi_io_rep_get8.9f ddi_io_rep_getw.9f
MLINKS+=	ddi_io_rep_put8.9f ddi_io_rep_put16.9f
MLINKS+=	ddi_io_rep_put8.9f ddi_io_rep_put32.9f
MLINKS+=	ddi_io_rep_put8.9f ddi_io_rep_putb.9f
MLINKS+=	ddi_io_rep_put8.9f ddi_io_rep_putl.9f
MLINKS+=	ddi_io_rep_put8.9f ddi_io_rep_putw.9f
MLINKS+=	ddi_map_regs.9f ddi_unmap_regs.9f
MLINKS+=	ddi_mem_get8.9f ddi_mem_get16.9f
MLINKS+=	ddi_mem_get8.9f ddi_mem_get32.9f
MLINKS+=	ddi_mem_get8.9f ddi_mem_get64.9f
MLINKS+=	ddi_mem_get8.9f ddi_mem_getb.9f
MLINKS+=	ddi_mem_get8.9f ddi_mem_getl.9f
MLINKS+=	ddi_mem_get8.9f ddi_mem_getll.9f
MLINKS+=	ddi_mem_get8.9f ddi_mem_getw.9f
MLINKS+=	ddi_mem_put8.9f ddi_mem_put16.9f
MLINKS+=	ddi_mem_put8.9f ddi_mem_put32.9f
MLINKS+=	ddi_mem_put8.9f ddi_mem_put64.9f
MLINKS+=	ddi_mem_put8.9f ddi_mem_putb.9f
MLINKS+=	ddi_mem_put8.9f ddi_mem_putl.9f
MLINKS+=	ddi_mem_put8.9f ddi_mem_putll.9f
MLINKS+=	ddi_mem_put8.9f ddi_mem_putw.9f
MLINKS+=	ddi_mem_rep_get8.9f ddi_mem_rep_get16.9f
MLINKS+=	ddi_mem_rep_get8.9f ddi_mem_rep_get32.9f
MLINKS+=	ddi_mem_rep_get8.9f ddi_mem_rep_get64.9f
MLINKS+=	ddi_mem_rep_get8.9f ddi_mem_rep_getb.9f
MLINKS+=	ddi_mem_rep_get8.9f ddi_mem_rep_getl.9f
MLINKS+=	ddi_mem_rep_get8.9f ddi_mem_rep_getll.9f
MLINKS+=	ddi_mem_rep_get8.9f ddi_mem_rep_getw.9f
MLINKS+=	ddi_mem_rep_put8.9f ddi_mem_rep_put16.9f
MLINKS+=	ddi_mem_rep_put8.9f ddi_mem_rep_put32.9f
MLINKS+=	ddi_mem_rep_put8.9f ddi_mem_rep_put64.9f
MLINKS+=	ddi_mem_rep_put8.9f ddi_mem_rep_putb.9f
MLINKS+=	ddi_mem_rep_put8.9f ddi_mem_rep_putl.9f
MLINKS+=	ddi_mem_rep_put8.9f ddi_mem_rep_putll.9f
MLINKS+=	ddi_mem_rep_put8.9f ddi_mem_rep_putw.9f
MLINKS+=	ddi_modopen.9f ddi_modclose.9f
MLINKS+=	ddi_modopen.9f ddi_modsym.9f
MLINKS+=	ddi_peek.9f ddi_peek16.9f
MLINKS+=	ddi_peek.9f ddi_peek32.9f
MLINKS+=	ddi_peek.9f ddi_peek64.9f
MLINKS+=	ddi_peek.9f ddi_peek8.9f
MLINKS+=	ddi_peek.9f ddi_peekc.9f
MLINKS+=	ddi_peek.9f ddi_peekd.9f
MLINKS+=	ddi_peek.9f ddi_peekl.9f
MLINKS+=	ddi_peek.9f ddi_peeks.9f
MLINKS+=	ddi_poke.9f ddi_poke16.9f
MLINKS+=	ddi_poke.9f ddi_poke32.9f
MLINKS+=	ddi_poke.9f ddi_poke64.9f
MLINKS+=	ddi_poke.9f ddi_poke8.9f
MLINKS+=	ddi_poke.9f ddi_pokec.9f
MLINKS+=	ddi_poke.9f ddi_poked.9f
MLINKS+=	ddi_poke.9f ddi_pokel.9f
MLINKS+=	ddi_poke.9f ddi_pokes.9f
MLINKS+=	ddi_prop_create.9f ddi_prop_modify.9f
MLINKS+=	ddi_prop_create.9f ddi_prop_remove.9f
MLINKS+=	ddi_prop_create.9f ddi_prop_remove_all.9f
MLINKS+=	ddi_prop_create.9f ddi_prop_undefine.9f
MLINKS+=	ddi_prop_get_int.9f ddi_prop_get_int64.9f
MLINKS+=	ddi_prop_lookup.9f ddi_prop_free.9f
MLINKS+=	ddi_prop_lookup.9f ddi_prop_lookup_byte_array.9f
MLINKS+=	ddi_prop_lookup.9f ddi_prop_lookup_int64_array.9f
MLINKS+=	ddi_prop_lookup.9f ddi_prop_lookup_int_array.9f
MLINKS+=	ddi_prop_lookup.9f ddi_prop_lookup_string.9f
MLINKS+=	ddi_prop_lookup.9f ddi_prop_lookup_string_array.9f
MLINKS+=	ddi_prop_op.9f ddi_getlongprop.9f
MLINKS+=	ddi_prop_op.9f ddi_getlongprop_buf.9f
MLINKS+=	ddi_prop_op.9f ddi_getprop.9f
MLINKS+=	ddi_prop_op.9f ddi_getproplen.9f
MLINKS+=	ddi_prop_update.9f ddi_prop_update_byte_array.9f
MLINKS+=	ddi_prop_update.9f ddi_prop_update_int.9f
MLINKS+=	ddi_prop_update.9f ddi_prop_update_int64.9f
MLINKS+=	ddi_prop_update.9f ddi_prop_update_int64_array.9f
MLINKS+=	ddi_prop_update.9f ddi_prop_update_int_array.9f
MLINKS+=	ddi_prop_update.9f ddi_prop_update_string.9f
MLINKS+=	ddi_prop_update.9f ddi_prop_update_string_array.9f
MLINKS+=	ddi_put8.9f ddi_put16.9f
MLINKS+=	ddi_put8.9f ddi_put32.9f
MLINKS+=	ddi_put8.9f ddi_put64.9f
MLINKS+=	ddi_put8.9f ddi_putb.9f
MLINKS+=	ddi_put8.9f ddi_putl.9f
MLINKS+=	ddi_put8.9f ddi_putll.9f
MLINKS+=	ddi_put8.9f ddi_putw.9f
MLINKS+=	ddi_rep_get8.9f ddi_rep_get16.9f
MLINKS+=	ddi_rep_get8.9f ddi_rep_get32.9f
MLINKS+=	ddi_rep_get8.9f ddi_rep_get64.9f
MLINKS+=	ddi_rep_get8.9f ddi_rep_getb.9f
MLINKS+=	ddi_rep_get8.9f ddi_rep_getl.9f
MLINKS+=	ddi_rep_get8.9f ddi_rep_getll.9f
MLINKS+=	ddi_rep_get8.9f ddi_rep_getw.9f
MLINKS+=	ddi_rep_put8.9f ddi_rep_put16.9f
MLINKS+=	ddi_rep_put8.9f ddi_rep_put32.9f
MLINKS+=	ddi_rep_put8.9f ddi_rep_put64.9f
MLINKS+=	ddi_rep_put8.9f ddi_rep_putb.9f
MLINKS+=	ddi_rep_put8.9f ddi_rep_putl.9f
MLINKS+=	ddi_rep_put8.9f ddi_rep_putll.9f
MLINKS+=	ddi_rep_put8.9f ddi_rep_putw.9f
MLINKS+=	ddi_segmap.9f ddi_segmap_setup.9f
MLINKS+=	ddi_soft_state.9f ddi_get_soft_state.9f
MLINKS+=	ddi_soft_state.9f ddi_soft_state_fini.9f
MLINKS+=	ddi_soft_state.9f ddi_soft_state_free.9f
MLINKS+=	ddi_soft_state.9f ddi_soft_state_init.9f
MLINKS+=	ddi_soft_state.9f ddi_soft_state_zalloc.9f
MLINKS+=	ddi_strtoll.9f ddi_strtoull.9f
MLINKS+=	ddi_umem_alloc.9f ddi_umem_free.9f
MLINKS+=	ddi_umem_lock.9f ddi_umem_unlock.9f
MLINKS+=	devmap_devmem_setup.9f devmap_umem_setup.9f
MLINKS+=	devmap_setup.9f ddi_devmap_segmap.9f
MLINKS+=	devmap_unload.9f devmap_load.9f
MLINKS+=	dlbindack.9f dlerrorack.9f
MLINKS+=	dlbindack.9f dlokack.9f
MLINKS+=	dlbindack.9f dlphysaddrack.9f
MLINKS+=	dlbindack.9f dluderrorind.9f
MLINKS+=	esballoc.9f desballoc.9f
MLINKS+=	freezestr.9f unfreezestr.9f
MLINKS+=	firmload.9f firmware_close.9f
MLINKS+=	firmload.9f firmware_free.9f
MLINKS+=	firmload.9f firmware_get_size.9f
MLINKS+=	firmload.9f firmware_malloc.9f
MLINKS+=	firmload.9f firmware_open.9f
MLINKS+=	firmload.9f firmware_read.9f
MLINKS+=	get_pktiopb.9f free_pktiopb.9f
MLINKS+=	gld.9f gld_intr.9f
MLINKS+=	gld.9f gld_mac_alloc.9f
MLINKS+=	gld.9f gld_mac_free.9f
MLINKS+=	gld.9f gld_recv.9f
MLINKS+=	gld.9f gld_register.9f
MLINKS+=	gld.9f gld_sched.9f
MLINKS+=	gld.9f gld_unregister.9f
MLINKS+=	id_space.9f id_space_create.9f
MLINKS+=	id_space.9f id_space_destroy.9f
MLINKS+=	id_space.9f id_space_extend.9f
MLINKS+=	id_space.9f id_alloc.9f
MLINKS+=	id_space.9f id_alloc_nosleep.9f
MLINKS+=	id_space.9f id_allocff.9f
MLINKS+=	id_space.9f id_allocff_nosleep.9f
MLINKS+=	id_space.9f id_alloc_specific_nosleep.9f
MLINKS+=	id_space.9f id_free.9f
MLINKS+=	id32_alloc.9f id32_free.9f
MLINKS+=	id32_alloc.9f id32_lookup.9f
MLINKS+=	inb.9f inl.9f
MLINKS+=	inb.9f inw.9f
MLINKS+=	inb.9f repinsb.9f
MLINKS+=	inb.9f repinsd.9f
MLINKS+=	inb.9f repinsw.9f
MLINKS+=	kmem_alloc.9f kmem_free.9f
MLINKS+=	kmem_alloc.9f kmem_zalloc.9f
MLINKS+=	kmem_cache_create.9f kmem_cache_alloc.9f
MLINKS+=	kmem_cache_create.9f kmem_cache_destroy.9f
MLINKS+=	kmem_cache_create.9f kmem_cache_free.9f
MLINKS+=	kmem_cache_create.9f kmem_cache_set_move.9f
MLINKS+=	kstat_named_init.9f kstat_named_setstr.9f
MLINKS+=	kstat_queue.9f kstat_runq_back_to_waitq.9f
MLINKS+=	kstat_queue.9f kstat_runq_enter.9f
MLINKS+=	kstat_queue.9f kstat_runq_exit.9f
MLINKS+=	kstat_queue.9f kstat_waitq_enter.9f
MLINKS+=	kstat_queue.9f kstat_waitq_exit.9f
MLINKS+=	kstat_queue.9f kstat_waitq_to_runq.9f
MLINKS+=	ldi_aread.9f ldi_awrite.9f
MLINKS+=	ldi_get_dev.9f ldi_get_devid.9f
MLINKS+=	ldi_get_dev.9f ldi_get_minor_name.9f
MLINKS+=	ldi_get_dev.9f ldi_get_otyp.9f
MLINKS+=	ldi_ident_from_dev.9f ldi_ident_from_dip.9f
MLINKS+=	ldi_ident_from_dev.9f ldi_ident_from_stream.9f
MLINKS+=	ldi_ident_from_dev.9f ldi_ident_release.9f
MLINKS+=	ldi_open_by_dev.9f ldi_close.9f
MLINKS+=	ldi_open_by_dev.9f ldi_open_by_devid.9f
MLINKS+=	ldi_open_by_dev.9f ldi_open_by_name.9f
MLINKS+=	ldi_prop_get_int.9f ldi_prop_get_int64.9f
MLINKS+=	ldi_prop_lookup_int_array.9f ldi_prop_lookup_byte_array.9f
MLINKS+=	ldi_prop_lookup_int_array.9f ldi_prop_lookup_int64_array.9f
MLINKS+=	ldi_prop_lookup_int_array.9f ldi_prop_lookup_string.9f
MLINKS+=	ldi_prop_lookup_int_array.9f ldi_prop_lookup_string_array.9f
MLINKS+=	ldi_putmsg.9f ldi_getmsg.9f
MLINKS+=	ldi_read.9f ldi_write.9f
MLINKS+=	list_create.9f list_destroy.9f
MLINKS+=	list_create.9f list_head.9f
MLINKS+=	list_create.9f list_insert_after.9f
MLINKS+=	list_create.9f list_insert_before.9f
MLINKS+=	list_create.9f list_insert_head.9f
MLINKS+=	list_create.9f list_insert_tail.9f
MLINKS+=	list_create.9f list_is_empty.9f
MLINKS+=	list_create.9f list_link_active.9f
MLINKS+=	list_create.9f list_link_init.9f
MLINKS+=	list_create.9f list_link_replace.9f
MLINKS+=	list_create.9f list_move_tail.9f
MLINKS+=	list_create.9f list_next.9f
MLINKS+=	list_create.9f list_prev.9f
MLINKS+=	list_create.9f list_remove.9f
MLINKS+=	list_create.9f list_remove_head.9f
MLINKS+=	list_create.9f list_remove_tail.9f
MLINKS+=	list_create.9f list_tail.9f
MLINKS+=	mac_alloc.9f mac_free.9f
MLINKS+=	mac_hcksum_get.9f mac_hcksum_set.9f
MLINKS+=	mac_init_ops.9f mac_fini_ops.9f
MLINKS+=	mac_prop_info.9f mac_prop_info_set_default_link_flowctrl.9f
MLINKS+=	mac_prop_info.9f mac_prop_info_set_default_str.9f
MLINKS+=	mac_prop_info.9f mac_prop_info_set_default_uint8.9f
MLINKS+=	mac_prop_info.9f mac_prop_info_set_default_uint32.9f
MLINKS+=	mac_prop_info.9f mac_prop_info_set_default_uint64.9f
MLINKS+=	mac_prop_info.9f mac_prop_info_set_perm.9f
MLINKS+=	mac_prop_info.9f mac_prop_info_set_range_uint32.9f
MLINKS+=	mac_register.9f mac_unregister.9f
MLINKS+=	makecom.9f makecom_g0.9f
MLINKS+=	makecom.9f makecom_g0_s.9f
MLINKS+=	makecom.9f makecom_g1.9f
MLINKS+=	makecom.9f makecom_g5.9f
MLINKS+=	membar_ops.9f membar_consumer.9f
MLINKS+=	membar_ops.9f membar_enter.9f
MLINKS+=	membar_ops.9f membar_exit.9f
MLINKS+=	membar_ops.9f membar_producer.9f
MLINKS+=	memchr.9f memcmp.9f
MLINKS+=	memchr.9f memcpy.9f
MLINKS+=	memchr.9f memmove.9f
MLINKS+=	memchr.9f memset.9f
MLINKS+=	mod_install.9f mod_info.9f
MLINKS+=	mod_install.9f mod_modname.9f
MLINKS+=	mod_install.9f mod_remove.9f
MLINKS+=	mutex.9f mutex_destroy.9f
MLINKS+=	mutex.9f mutex_enter.9f
MLINKS+=	mutex.9f mutex_exit.9f
MLINKS+=	mutex.9f mutex_init.9f
MLINKS+=	mutex.9f mutex_owned.9f
MLINKS+=	mutex.9f mutex_tryenter.9f
MLINKS+=	net_event_notify_register.9f net_event_notify_unregister.9f
MLINKS+=	net_instance_notify_register.9f net_instance_notify_unregister.9f
MLINKS+=	net_protocol_notify_register.9f net_instance_protocol_unregister.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_boolean_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_boolean_value.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_byte.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_byte_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_int16.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_int16_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_int32.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_int32_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_int64.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_int64_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_int8.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_int8_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_nvlist.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_nvlist_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_nvpair.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_string.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_string_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_uint16.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_uint16_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_uint32.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_uint32_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_uint64.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_uint64_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_uint8.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_add_uint8_array.9f
MLINKS+=	nvlist_add_boolean.9f nvlist_t.9f
MLINKS+=	nvlist_alloc.9f nv_alloc_fini.9f
MLINKS+=	nvlist_alloc.9f nv_alloc_init.9f
MLINKS+=	nvlist_alloc.9f nvlist_dup.9f
MLINKS+=	nvlist_alloc.9f nvlist_free.9f
MLINKS+=	nvlist_alloc.9f nvlist_merge.9f
MLINKS+=	nvlist_alloc.9f nvlist_pack.9f
MLINKS+=	nvlist_alloc.9f nvlist_size.9f
MLINKS+=	nvlist_alloc.9f nvlist_unpack.9f
MLINKS+=	nvlist_alloc.9f nvlist_xalloc.9f
MLINKS+=	nvlist_alloc.9f nvlist_xdup.9f
MLINKS+=	nvlist_alloc.9f nvlist_xpack.9f
MLINKS+=	nvlist_alloc.9f nvlist_xunpack.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_boolean_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_boolean_value.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_byte.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_byte_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_int16.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_int16_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_int32.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_int32_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_int64.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_int64_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_int8.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_int8_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_nvlist.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_nvlist_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_pairs.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_string.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_string_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_uint16.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_uint16_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_uint32.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_uint32_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_uint64.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_uint64_array.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_uint8.9f
MLINKS+=	nvlist_lookup_boolean.9f nvlist_lookup_uint8_array.9f
MLINKS+=	nvlist_lookup_nvpair.9f nvlist_exists.9f
MLINKS+=	nvlist_next_nvpair.9f nvpair_name.9f
MLINKS+=	nvlist_next_nvpair.9f nvpair_type.9f
MLINKS+=	nvlist_remove.9f nvlist_remove_all.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_boolean_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_byte_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_int16.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_int16_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_int32.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_int32_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_int64.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_int64_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_int8.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_int8_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_nvlist.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_nvlist_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_string.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_string_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_uint16.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_uint16_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_uint32.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_uint32_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_uint64.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_uint64_array.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_uint8.9f
MLINKS+=	nvpair_value_byte.9f nvpair_value_uint8_array.9f
MLINKS+=	outb.9f outl.9f
MLINKS+=	outb.9f outw.9f
MLINKS+=	outb.9f repoutsb.9f
MLINKS+=	outb.9f repoutsd.9f
MLINKS+=	outb.9f repoutsw.9f
MLINKS+=	pci_config_get8.9f pci_config_get16.9f
MLINKS+=	pci_config_get8.9f pci_config_get32.9f
MLINKS+=	pci_config_get8.9f pci_config_get64.9f
MLINKS+=	pci_config_get8.9f pci_config_getb.9f
MLINKS+=	pci_config_get8.9f pci_config_getl.9f
MLINKS+=	pci_config_get8.9f pci_config_getll.9f
MLINKS+=	pci_config_get8.9f pci_config_getw.9f
MLINKS+=	pci_config_get8.9f pci_config_put16.9f
MLINKS+=	pci_config_get8.9f pci_config_put32.9f
MLINKS+=	pci_config_get8.9f pci_config_put64.9f
MLINKS+=	pci_config_get8.9f pci_config_put8.9f
MLINKS+=	pci_config_get8.9f pci_config_putb.9f
MLINKS+=	pci_config_get8.9f pci_config_putl.9f
MLINKS+=	pci_config_get8.9f pci_config_putll.9f
MLINKS+=	pci_config_get8.9f pci_config_putw.9f
MLINKS+=	pci_config_setup.9f pci_config_teardown.9f
MLINKS+=	pci_ereport_setup.9f pci_ereport_post.9f
MLINKS+=	pci_ereport_setup.9f pci_ereport_teardown.9f
MLINKS+=	pci_save_config_regs.9f pci_restore_config_regs.9f
MLINKS+=	physio.9f minphys.9f
MLINKS+=	pm_busy_component.9f pm_idle_component.9f
MLINKS+=	pm_raise_power.9f pm_lower_power.9f
MLINKS+=	priv_policy.9f priv_policy_choice.9f
MLINKS+=	priv_policy.9f priv_policy_only.9f
MLINKS+=	proc_signal.9f proc_ref.9f
MLINKS+=	proc_signal.9f proc_unref.9f
MLINKS+=	qprocson.9f qprocsoff.9f
MLINKS+=	qwait.9f qwait_sig.9f
MLINKS+=	rmallocmap.9f rmallocmap_wait.9f
MLINKS+=	rmallocmap.9f rmfreemap.9f
MLINKS+=	rwlock.9f rw_destroy.9f
MLINKS+=	rwlock.9f rw_downgrade.9f
MLINKS+=	rwlock.9f rw_enter.9f
MLINKS+=	rwlock.9f rw_exit.9f
MLINKS+=	rwlock.9f rw_init.9f
MLINKS+=	rwlock.9f rw_read_locked.9f
MLINKS+=	rwlock.9f rw_tryenter.9f
MLINKS+=	rwlock.9f rw_tryupgrade.9f
MLINKS+=	scsi_cname.9f scsi_dname.9f
MLINKS+=	scsi_cname.9f scsi_mname.9f
MLINKS+=	scsi_cname.9f scsi_rname.9f
MLINKS+=	scsi_cname.9f scsi_sname.9f
MLINKS+=	scsi_dmaget.9f scsi_dmafree.9f
MLINKS+=	scsi_ext_sense_fields.9f scsi_sense_cmdspecific_uint64.9f
MLINKS+=	scsi_ext_sense_fields.9f scsi_sense_info_uint64.9f
MLINKS+=	scsi_hba_attach_setup.9f scsi_hba_detach.9f
MLINKS+=	scsi_hba_init.9f scsi_hba_fini.9f
MLINKS+=	scsi_hba_pkt_alloc.9f scsi_hba_pkt_free.9f
MLINKS+=	scsi_hba_tran_alloc.9f scsi_hba_tran_free.9f
MLINKS+=	scsi_ifgetcap.9f scsi_ifsetcap.9f
MLINKS+=	scsi_pktalloc.9f scsi_pktfree.9f
MLINKS+=	scsi_pktalloc.9f scsi_resalloc.9f
MLINKS+=	scsi_pktalloc.9f scsi_resfree.9f
MLINKS+=	scsi_sense_key.9f scsi_sense_asc.9f
MLINKS+=	scsi_sense_key.9f scsi_sense_ascq.9f
MLINKS+=	scsi_unprobe.9f scsi_unslave.9f
MLINKS+=	semaphore.9f sema_destroy.9f
MLINKS+=	semaphore.9f sema_init.9f
MLINKS+=	semaphore.9f sema_p.9f
MLINKS+=	semaphore.9f sema_p_sig.9f
MLINKS+=	semaphore.9f sema_tryp.9f
MLINKS+=	semaphore.9f sema_v.9f
MLINKS+=	sprintf.9f snprintf.9f
MLINKS+=	sprintf.9f vsprintf.9f
MLINKS+=	sprintf.9f vsnprintf.9f
MLINKS+=	stoi.9f numtos.9f
MLINKS+=	string.9f ddi_strdup.9f
MLINKS+=	string.9f strcasecmp.9f
MLINKS+=	string.9f strcat.9f
MLINKS+=	string.9f strchr.9f
MLINKS+=	string.9f strcmp.9f
MLINKS+=	string.9f strcpy.9f
MLINKS+=	string.9f strdup.9f
MLINKS+=	string.9f strfree.9f
MLINKS+=	string.9f strlcat.9f
MLINKS+=	string.9f strlcpy.9f
MLINKS+=	string.9f strlen.9f
MLINKS+=	string.9f strncasecmp.9f
MLINKS+=	string.9f strncat.9f
MLINKS+=	string.9f strncmp.9f
MLINKS+=	string.9f strncpy.9f
MLINKS+=	string.9f strnlen.9f
MLINKS+=	string.9f strrchr.9f
MLINKS+=	string.9f strspn.9f
MLINKS+=	taskq.9f ddi_taskq_create.9f
MLINKS+=	taskq.9f ddi_taskq_destroy.9f
MLINKS+=	taskq.9f ddi_taskq_dispatch.9f
MLINKS+=	taskq.9f ddi_taskq_resume.9f
MLINKS+=	taskq.9f ddi_taskq_suspend.9f
MLINKS+=	taskq.9f ddi_taskq_wait.9f
MLINKS+=	taskq.9f taskq_suspended.9f
MLINKS+=	uconv_u16tou32.9f uconv_u16tou8.9f
MLINKS+=	uconv_u16tou32.9f uconv_u32tou16.9f
MLINKS+=	uconv_u16tou32.9f uconv_u32tou8.9f
MLINKS+=	uconv_u16tou32.9f uconv_u8tou16.9f
MLINKS+=	uconv_u16tou32.9f uconv_u8tou32.9f
MLINKS+=	usb_alloc_request.9f usb_alloc_bulk_req.9f
MLINKS+=	usb_alloc_request.9f usb_alloc_ctrl_req.9f
MLINKS+=	usb_alloc_request.9f usb_alloc_intr_req.9f
MLINKS+=	usb_alloc_request.9f usb_alloc_isoc_req.9f
MLINKS+=	usb_alloc_request.9f usb_free_bulk_req.9f
MLINKS+=	usb_alloc_request.9f usb_free_ctrl_req.9f
MLINKS+=	usb_alloc_request.9f usb_free_intr_req.9f
MLINKS+=	usb_alloc_request.9f usb_free_isoc_req.9f
MLINKS+=	usb_client_attach.9f usb_client_detach.9f
MLINKS+=	usb_get_alt_if.9f usb_get_if_number.9f
MLINKS+=	usb_get_alt_if.9f usb_owns_device.9f
MLINKS+=	usb_get_alt_if.9f usb_set_alt_if.9f
MLINKS+=	usb_get_cfg.9f usb_set_cfg.9f
MLINKS+=	usb_get_dev_data.9f usb_free_descr_tree.9f
MLINKS+=	usb_get_dev_data.9f usb_free_dev_data.9f
MLINKS+=	usb_get_dev_data.9f usb_print_descr_tree.9f
MLINKS+=	usb_pipe_ctrl_xfer.9f usb_pipe_ctrl_xfer_wait.9f
MLINKS+=	usb_pipe_intr_xfer.9f usb_pipe_stop_intr_polling.9f
MLINKS+=	usb_pipe_isoc_xfer.9f usb_pipe_stop_isoc_polling.9f
MLINKS+=	usb_pipe_set_private.9f usb_pipe_get_private.9f
MLINKS+=	usb_register_hotplug_cbs.9f usb_unregister_hotplug_cbs.9f
MLINKS+=	va_arg.9f va_copy.9f
MLINKS+=	va_arg.9f va_end.9f
MLINKS+=	va_arg.9f va_start.9f

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
