MAN = di_binding_name.3devinfo \
      di_child_node.3devinfo \
      di_devfs_path.3devinfo \
      di_devlink_dup.3devinfo \
      di_devlink_init.3devinfo \
      di_devlink_path.3devinfo \
      di_devlink_walk.3devinfo \
      di_init.3devinfo \
      di_link_next_by_node.3devinfo \
      di_link_spectype.3devinfo \
      di_lnode_name.3devinfo \
      di_lnode_next.3devinfo \
      di_minor_devt.3devinfo \
      di_minor_next.3devinfo \
      di_node_private_set.3devinfo \
      di_path_bus_addr.3devinfo \
      di_path_client_next_path.3devinfo \
      di_path_prop_bytes.3devinfo \
      di_path_prop_lookup_bytes.3devinfo \
      di_path_prop_next.3devinfo \
      di_prom_init.3devinfo \
      di_prom_prop_data.3devinfo \
      di_prom_prop_lookup_bytes.3devinfo \
      di_prop_bytes.3devinfo \
      di_prop_lookup_bytes.3devinfo \
      di_prop_next.3devinfo \
      di_walk_link.3devinfo \
      di_walk_lnode.3devinfo \
      di_walk_minor.3devinfo \
      di_walk_node.3devinfo

MLINKS+=	di_binding_name.3devinfo di_bus_addr.3devinfo
MLINKS+=	di_binding_name.3devinfo di_compatible_names.3devinfo
MLINKS+=	di_binding_name.3devinfo di_devid.3devinfo
MLINKS+=	di_binding_name.3devinfo di_driver_major.3devinfo
MLINKS+=	di_binding_name.3devinfo di_driver_name.3devinfo
MLINKS+=	di_binding_name.3devinfo di_driver_ops.3devinfo
MLINKS+=	di_binding_name.3devinfo di_instance.3devinfo
MLINKS+=	di_binding_name.3devinfo di_node_name.3devinfo
MLINKS+=	di_binding_name.3devinfo di_nodeid.3devinfo
MLINKS+=	di_child_node.3devinfo di_drv_first_node.3devinfo
MLINKS+=	di_child_node.3devinfo di_drv_next_node.3devinfo
MLINKS+=	di_child_node.3devinfo di_parent_node.3devinfo
MLINKS+=	di_child_node.3devinfo di_sibling_node.3devinfo
MLINKS+=	di_devfs_path.3devinfo di_devfs_minor_path.3devinfo
MLINKS+=	di_devfs_path.3devinfo di_devfs_path_free.3devinfo
MLINKS+=	di_devfs_path.3devinfo di_path_client_devfs_path.3devinfo
MLINKS+=	di_devfs_path.3devinfo di_path_devfs_path.3devinfo
MLINKS+=	di_devlink_dup.3devinfo di_devlink_free.3devinfo
MLINKS+=	di_devlink_init.3devinfo di_devlink_fini.3devinfo
MLINKS+=	di_devlink_path.3devinfo di_devlink_content.3devinfo
MLINKS+=	di_devlink_path.3devinfo di_devlink_type.3devinfo
MLINKS+=	di_init.3devinfo di_fini.3devinfo
MLINKS+=	di_link_next_by_node.3devinfo di_link_next_by_lnode.3devinfo
MLINKS+=	di_link_spectype.3devinfo di_link_to_lnode.3devinfo
MLINKS+=	di_lnode_name.3devinfo di_lnode_devinfo.3devinfo
MLINKS+=	di_lnode_name.3devinfo di_lnode_devt.3devinfo
MLINKS+=	di_minor_devt.3devinfo di_minor_name.3devinfo
MLINKS+=	di_minor_devt.3devinfo di_minor_nodetype.3devinfo
MLINKS+=	di_minor_devt.3devinfo di_minor_spectype.3devinfo
MLINKS+=	di_node_private_set.3devinfo di_link_private_get.3devinfo
MLINKS+=	di_node_private_set.3devinfo di_link_private_set.3devinfo
MLINKS+=	di_node_private_set.3devinfo di_lnode_private_get.3devinfo
MLINKS+=	di_node_private_set.3devinfo di_lnode_private_set.3devinfo
MLINKS+=	di_node_private_set.3devinfo di_minor_private_get.3devinfo
MLINKS+=	di_node_private_set.3devinfo di_minor_private_set.3devinfo
MLINKS+=	di_node_private_set.3devinfo di_node_private_get.3devinfo
MLINKS+=	di_node_private_set.3devinfo di_path_private_get.3devinfo
MLINKS+=	di_node_private_set.3devinfo di_path_private_set.3devinfo
MLINKS+=	di_path_bus_addr.3devinfo di_path_client_node.3devinfo
MLINKS+=	di_path_bus_addr.3devinfo di_path_instance.3devinfo
MLINKS+=	di_path_bus_addr.3devinfo di_path_node_name.3devinfo
MLINKS+=	di_path_bus_addr.3devinfo di_path_phci_node.3devinfo
MLINKS+=	di_path_bus_addr.3devinfo di_path_state.3devinfo
MLINKS+=	di_path_client_next_path.3devinfo di_path_phci_next_path.3devinfo
MLINKS+=	di_path_prop_bytes.3devinfo di_path_prop_int64s.3devinfo
MLINKS+=	di_path_prop_bytes.3devinfo di_path_prop_ints.3devinfo
MLINKS+=	di_path_prop_bytes.3devinfo di_path_prop_name.3devinfo
MLINKS+=	di_path_prop_bytes.3devinfo di_path_prop_strings.3devinfo
MLINKS+=	di_path_prop_bytes.3devinfo di_path_prop_type.3devinfo
MLINKS+=	di_path_prop_lookup_bytes.3devinfo di_path_prop_lookup_int64s.3devinfo
MLINKS+=	di_path_prop_lookup_bytes.3devinfo di_path_prop_lookup_ints.3devinfo
MLINKS+=	di_path_prop_lookup_bytes.3devinfo di_path_prop_lookup_strings.3devinfo
MLINKS+=	di_prom_init.3devinfo di_prom_fini.3devinfo
MLINKS+=	di_prom_prop_data.3devinfo di_prom_prop_name.3devinfo
MLINKS+=	di_prom_prop_data.3devinfo di_prom_prop_next.3devinfo
MLINKS+=	di_prom_prop_lookup_bytes.3devinfo di_prom_prop_lookup_ints.3devinfo
MLINKS+=	di_prom_prop_lookup_bytes.3devinfo di_prom_prop_lookup_strings.3devinfo
MLINKS+=	di_prop_bytes.3devinfo di_prop_devt.3devinfo
MLINKS+=	di_prop_bytes.3devinfo di_prop_int64.3devinfo
MLINKS+=	di_prop_bytes.3devinfo di_prop_ints.3devinfo
MLINKS+=	di_prop_bytes.3devinfo di_prop_name.3devinfo
MLINKS+=	di_prop_bytes.3devinfo di_prop_strings.3devinfo
MLINKS+=	di_prop_bytes.3devinfo di_prop_type.3devinfo
MLINKS+=	di_prop_lookup_bytes.3devinfo di_prop_lookup_int64.3devinfo
MLINKS+=	di_prop_lookup_bytes.3devinfo di_prop_lookup_ints.3devinfo
MLINKS+=	di_prop_lookup_bytes.3devinfo di_prop_lookup_strings.3devinfo

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
