#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = named_attrs/attrops
SHRSRC = NAMED_ATTRS.flist
TCS = runtests
TCLSRC = named_attrs_neg06 named_attrs_neg07 named_attrs_pos01 \
	named_attrs_pos03 named_attrs_pos04 named_attrs_pos05 \
	READ_proc WRITE_proc

include ../../Makefile.test
