INCDIR=	/usr/platform/${CONFIG_PLATFORM}/include/vm
INCS=	hat_i86.h \
	hat_pte.h \
	hment.h \
	htable.h \
	kboot_mmu.h

.include <prog.mk>
.include <inc.mk>

REPOROOT = ${.CURDIR:H:H:H:H:H:H:H}
.include <${REPOROOT}/Makefile.cfgparam>
