MAN = cpl_complete_word.3tecla \
      ef_expand_file.3tecla \
      gl_get_line.3tecla \
      gl_io_mode.3tecla \
      libtecla_version.3tecla \
      pca_lookup_file.3tecla

MLINKS+=	cpl_complete_word.3tecla cfc_file_start.3tecla
MLINKS+=	cpl_complete_word.3tecla cfc_literal_escapes.3tecla
MLINKS+=	cpl_complete_word.3tecla cfc_set_check_fn.3tecla
MLINKS+=	cpl_complete_word.3tecla cpl_add_completion.3tecla
MLINKS+=	cpl_complete_word.3tecla cpl_check_exe.3tecla
MLINKS+=	cpl_complete_word.3tecla cpl_file_completions.3tecla
MLINKS+=	cpl_complete_word.3tecla cpl_last_error.3tecla
MLINKS+=	cpl_complete_word.3tecla cpl_list_completions.3tecla
MLINKS+=	cpl_complete_word.3tecla cpl_recall_matches.3tecla
MLINKS+=	cpl_complete_word.3tecla cpl_record_error.3tecla
MLINKS+=	cpl_complete_word.3tecla del_CplFileConf.3tecla
MLINKS+=	cpl_complete_word.3tecla del_WordCompletion.3tecla
MLINKS+=	cpl_complete_word.3tecla new_CplFileConf.3tecla
MLINKS+=	cpl_complete_word.3tecla new_WordCompletion.3tecla
MLINKS+=	ef_expand_file.3tecla del_ExpandFile.3tecla
MLINKS+=	ef_expand_file.3tecla ef_last_error.3tecla
MLINKS+=	ef_expand_file.3tecla ef_list_expansions.3tecla
MLINKS+=	ef_expand_file.3tecla new_ExpandFile.3tecla
MLINKS+=	gl_get_line.3tecla del_GetLine.3tecla
MLINKS+=	gl_get_line.3tecla gl_append_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_automatic_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_bind_keyseq.3tecla
MLINKS+=	gl_get_line.3tecla gl_catch_blocked.3tecla
MLINKS+=	gl_get_line.3tecla gl_change_terminal.3tecla
MLINKS+=	gl_get_line.3tecla gl_clear_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_completion_action.3tecla
MLINKS+=	gl_get_line.3tecla gl_configure_getline.3tecla
MLINKS+=	gl_get_line.3tecla gl_customize_completion.3tecla
MLINKS+=	gl_get_line.3tecla gl_display_text.3tecla
MLINKS+=	gl_get_line.3tecla gl_echo_mode.3tecla
MLINKS+=	gl_get_line.3tecla gl_erase_terminal.3tecla
MLINKS+=	gl_get_line.3tecla gl_error_message.3tecla
MLINKS+=	gl_get_line.3tecla gl_group_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_ignore_signal.3tecla
MLINKS+=	gl_get_line.3tecla gl_inactivity_timeout.3tecla
MLINKS+=	gl_get_line.3tecla gl_last_signal.3tecla
MLINKS+=	gl_get_line.3tecla gl_limit_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_list_signals.3tecla
MLINKS+=	gl_get_line.3tecla gl_load_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_lookup_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_prompt_style.3tecla
MLINKS+=	gl_get_line.3tecla gl_query_char.3tecla
MLINKS+=	gl_get_line.3tecla gl_range_of_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_read_char.3tecla
MLINKS+=	gl_get_line.3tecla gl_register_action.3tecla
MLINKS+=	gl_get_line.3tecla gl_replace_prompt.3tecla
MLINKS+=	gl_get_line.3tecla gl_resize_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_return_status.3tecla
MLINKS+=	gl_get_line.3tecla gl_save_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_set_term_size.3tecla
MLINKS+=	gl_get_line.3tecla gl_show_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_size_of_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_state_of_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_terminal_size.3tecla
MLINKS+=	gl_get_line.3tecla gl_toggle_history.3tecla
MLINKS+=	gl_get_line.3tecla gl_trap_signal.3tecla
MLINKS+=	gl_get_line.3tecla gl_watch_fd.3tecla
MLINKS+=	gl_get_line.3tecla new_GetLine.3tecla
MLINKS+=	gl_io_mode.3tecla gl_abandon_line.3tecla
MLINKS+=	gl_io_mode.3tecla gl_handle_signal.3tecla
MLINKS+=	gl_io_mode.3tecla gl_normal_io.3tecla
MLINKS+=	gl_io_mode.3tecla gl_pending_io.3tecla
MLINKS+=	gl_io_mode.3tecla gl_raw_io.3tecla
MLINKS+=	gl_io_mode.3tecla gl_tty_signals.3tecla
MLINKS+=	pca_lookup_file.3tecla del_PathCache.3tecla
MLINKS+=	pca_lookup_file.3tecla del_PcaPathConf.3tecla
MLINKS+=	pca_lookup_file.3tecla new_PathCache.3tecla
MLINKS+=	pca_lookup_file.3tecla new_PcaPathConf.3tecla
MLINKS+=	pca_lookup_file.3tecla pca_last_error.3tecla
MLINKS+=	pca_lookup_file.3tecla pca_path_completions.3tecla
MLINKS+=	pca_lookup_file.3tecla pca_scan_path.3tecla
MLINKS+=	pca_lookup_file.3tecla pca_set_check_fn.3tecla
MLINKS+=	pca_lookup_file.3tecla ppc_file_start.3tecla
MLINKS+=	pca_lookup_file.3tecla ppc_literal_escapes.3tecla

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
