.include <../../../../Makefile.cfgparam>

SUBDIR_${CONFIG_IWH}		=  iwh
SUBDIR_${CONFIG_IWI}		+= iwi
SUBDIR_${CONFIG_IWK}		+= iwk
SUBDIR_${CONFIG_IWN}		+= iwn
SUBDIR_${CONFIG_IWP}		+= iwp
SUBDIR_${CONFIG_ZYD}		+= zyd

SUBDIR = ${SUBDIR_y}

.include <bsd.subdir.mk>
