#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = svcadm/restart
DESC = functions.kshlib template.xml stf_description
TCS = svcadm_restart_001 svcadm_restart_002 svcadm_restart_003 \
	svcadm_restart_004 svcadm_restart_005 svcadm_restart_006 \
	svcadm_restart_007 svcadm_restart_008 svcadm_restart_009 \
	svcadm_restart_010 svcadm_restart_011

include ../../Makefile.test
