#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

PROFDIR = svccfg/security/security_profiles
TEST = $(PROFDIR)/svccfg_security_profiles_003
DESC = stf_description
TCS = cleanup_profiles_003 setup_profiles_003 svccfg_security_profiles_003 \
	stf_description

include ../../../../Makefile.test
