#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TPLDIR = svccfg/templates
TEST = $(TPLDIR)/prop_pattern_choices
DESC = config.env prop_pattern_choices.xml stf_description
TCS = prop_pattern_choices_001 prop_pattern_choices_002 prop_pattern_choices_003 \
	prop_pattern_choices_004 prop_pattern_choices_005 \
	prop_pattern_choices_006 prop_pattern_choices_007 \
	prop_pattern_choices_008 prop_pattern_choices_009 \
	prop_pattern_choices_010 prop_pattern_choices_011 \
	prop_pattern_choices_012 prop_pattern_choices_013 \
	prop_pattern_choices_014 prop_pattern_choices_015 \
	prop_pattern_choices_016 prop_pattern_choices_017 \
	prop_pattern_choices_018 prop_pattern_choices_019 \
	prop_pattern_choices_020 prop_pattern_choices_021 \
	prop_pattern_choices_022 prop_pattern_choices_023 \
	prop_pattern_choices_024 prop_pattern_choices_025 \
	prop_pattern_choices_026 prop_pattern_choices_027 \
	prop_pattern_choices_028 prop_pattern_choices_029 \
	prop_pattern_choices_030 prop_pattern_choices_031 \
	prop_pattern_choices_032

include ../../../Makefile.test
