#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = acl/srv_tests
SHRSRC = acl.flist data.cfg README
TCS = runtests 
TCLSRC = acl_dir_pos00 acl_dir_pos01 acl_dir_pos02 acl_dir_pos03 \
	acl_dir_pos04 acl_dir_pos05 acl_dir_pos06 acl_dir_pos07 \
	acl_dir_pos08 acl_dir_pos09 acl_dir_pos10 acl_dir_pos11 \
	acl_neg00 acl_neg01 acl_neg02 acl_neg03 acl_pos00 \
	acl_pos01 acl_pos02 acl_pos03 acl_pos04 \
	acl_pos05 acl_pos06

include ../../Makefile.test
