MAN = resolver.3resolv 

MLINKS+=	resolver.3resolv dn_comp.3resolv
MLINKS+=	resolver.3resolv dn_expand.3resolv
MLINKS+=	resolver.3resolv fp_resstat.3resolv
MLINKS+=	resolver.3resolv herror.3resolv
MLINKS+=	resolver.3resolv hstrerror.3resolv
MLINKS+=	resolver.3resolv res_getservers.3resolv
MLINKS+=	resolver.3resolv res_hostalias.3resolv
MLINKS+=	resolver.3resolv res_init.3resolv
MLINKS+=	resolver.3resolv res_mkquery.3resolv
MLINKS+=	resolver.3resolv res_nclose.3resolv
MLINKS+=	resolver.3resolv res_ndestroy.3resolv
MLINKS+=	resolver.3resolv res_ninit.3resolv
MLINKS+=	resolver.3resolv res_nmkquery.3resolv
MLINKS+=	resolver.3resolv res_nquery.3resolv
MLINKS+=	resolver.3resolv res_nquerydomain.3resolv
MLINKS+=	resolver.3resolv res_nsearch.3resolv
MLINKS+=	resolver.3resolv res_nsend.3resolv
MLINKS+=	resolver.3resolv res_nsendsigned.3resolv
MLINKS+=	resolver.3resolv res_query.3resolv
MLINKS+=	resolver.3resolv res_search.3resolv
MLINKS+=	resolver.3resolv res_send.3resolv
MLINKS+=	resolver.3resolv res_setservers.3resolv

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
