MAN = COLS.3xcurses \
      LINES.3xcurses \
      add_wch.3xcurses \
      add_wchnstr.3xcurses \
      addch.3xcurses \
      addchstr.3xcurses \
      addnstr.3xcurses \
      addnwstr.3xcurses \
      attr_get.3xcurses \
      attroff.3xcurses \
      baudrate.3xcurses \
      beep.3xcurses \
      bkgd.3xcurses \
      bkgrnd.3xcurses \
      border.3xcurses \
      border_set.3xcurses \
      can_change_color.3xcurses \
      cbreak.3xcurses \
      chgat.3xcurses \
      clear.3xcurses \
      clearok.3xcurses \
      clrtobot.3xcurses \
      clrtoeol.3xcurses \
      copywin.3xcurses \
      cur_term.3xcurses \
      curs_set.3xcurses \
      curscr.3xcurses \
      curses.3xcurses \
      def_prog_mode.3xcurses \
      del_curterm.3xcurses \
      delay_output.3xcurses \
      delch.3xcurses \
      deleteln.3xcurses \
      delscreen.3xcurses \
      delwin.3xcurses \
      derwin.3xcurses \
      doupdate.3xcurses \
      dupwin.3xcurses \
      echo.3xcurses \
      echo_wchar.3xcurses \
      echochar.3xcurses \
      endwin.3xcurses \
      erasechar.3xcurses \
      filter.3xcurses \
      flushinp.3xcurses \
      get_wch.3xcurses \
      getbegyx.3xcurses \
      getcchar.3xcurses \
      getch.3xcurses \
      getn_wstr.3xcurses \
      getnstr.3xcurses \
      getwin.3xcurses \
      halfdelay.3xcurses \
      has_ic.3xcurses \
      hline.3xcurses \
      hline_set.3xcurses \
      idcok.3xcurses \
      immedok.3xcurses \
      in_wch.3xcurses \
      in_wchnstr.3xcurses \
      inch.3xcurses \
      inchnstr.3xcurses \
      initscr.3xcurses \
      innstr.3xcurses \
      innwstr.3xcurses \
      ins_nwstr.3xcurses \
      ins_wch.3xcurses \
      insch.3xcurses \
      insdelln.3xcurses \
      insertln.3xcurses \
      insnstr.3xcurses \
      intrflush.3xcurses \
      is_linetouched.3xcurses \
      keyname.3xcurses \
      keypad.3xcurses \
      libcurses.3xcurses \
      longname.3xcurses \
      meta.3xcurses \
      move.3xcurses \
      mvcur.3xcurses \
      mvderwin.3xcurses \
      mvprintw.3xcurses \
      mvscanw.3xcurses \
      mvwin.3xcurses \
      napms.3xcurses \
      newpad.3xcurses \
      nl.3xcurses \
      nodelay.3xcurses \
      noqiflush.3xcurses \
      notimeout.3xcurses \
      overlay.3xcurses \
      pechochar.3xcurses \
      putp.3xcurses \
      redrawwin.3xcurses \
      resetty.3xcurses \
      ripoffline.3xcurses \
      scr_dump.3xcurses \
      scrl.3xcurses \
      set_term.3xcurses \
      setcchar.3xcurses \
      slk_attroff.3xcurses \
      standend.3xcurses \
      stdscr.3xcurses \
      syncok.3xcurses \
      termattrs.3xcurses \
      termname.3xcurses \
      tgetent.3xcurses \
      tigetflag.3xcurses \
      typeahead.3xcurses \
      unctrl.3xcurses \
      ungetch.3xcurses \
      use_env.3xcurses \
      vidattr.3xcurses \
      vw_printw.3xcurses \
      vw_scanw.3xcurses \
      vwprintw.3xcurses \
      vwscanw.3xcurses \
      wunctrl.3xcurses

MLINKS+=	add_wch.3xcurses mvadd_wch.3xcurses
MLINKS+=	add_wch.3xcurses mvwadd_wch.3xcurses
MLINKS+=	add_wch.3xcurses wadd_wch.3xcurses
MLINKS+=	add_wchnstr.3xcurses add_wchstr.3xcurses
MLINKS+=	add_wchnstr.3xcurses mvadd_wchnstr.3xcurses
MLINKS+=	add_wchnstr.3xcurses mvadd_wchstr.3xcurses
MLINKS+=	add_wchnstr.3xcurses mvwadd_wchnstr.3xcurses
MLINKS+=	add_wchnstr.3xcurses mvwadd_wchstr.3xcurses
MLINKS+=	add_wchnstr.3xcurses wadd_wchnstr.3xcurses
MLINKS+=	add_wchnstr.3xcurses wadd_wchstr.3xcurses
MLINKS+=	addch.3xcurses mvaddch.3xcurses
MLINKS+=	addch.3xcurses mvwaddch.3xcurses
MLINKS+=	addch.3xcurses waddch.3xcurses
MLINKS+=	addchstr.3xcurses addchnstr.3xcurses
MLINKS+=	addchstr.3xcurses mvaddchnstr.3xcurses
MLINKS+=	addchstr.3xcurses mvaddchstr.3xcurses
MLINKS+=	addchstr.3xcurses mvwaddchnstr.3xcurses
MLINKS+=	addchstr.3xcurses mvwaddchstr.3xcurses
MLINKS+=	addchstr.3xcurses waddchnstr.3xcurses
MLINKS+=	addchstr.3xcurses waddchstr.3xcurses
MLINKS+=	addnstr.3xcurses addstr.3xcurses
MLINKS+=	addnstr.3xcurses mvaddnstr.3xcurses
MLINKS+=	addnstr.3xcurses mvaddstr.3xcurses
MLINKS+=	addnstr.3xcurses mvwaddnstr.3xcurses
MLINKS+=	addnstr.3xcurses mvwaddstr.3xcurses
MLINKS+=	addnstr.3xcurses waddnstr.3xcurses
MLINKS+=	addnstr.3xcurses waddstr.3xcurses
MLINKS+=	addnwstr.3xcurses addwstr.3xcurses
MLINKS+=	addnwstr.3xcurses mvaddnwstr.3xcurses
MLINKS+=	addnwstr.3xcurses mvaddwstr.3xcurses
MLINKS+=	addnwstr.3xcurses mvwaddnwstr.3xcurses
MLINKS+=	addnwstr.3xcurses mvwaddwstr.3xcurses
MLINKS+=	addnwstr.3xcurses waddnwstr.3xcurses
MLINKS+=	addnwstr.3xcurses waddwstr.3xcurses
MLINKS+=	attr_get.3xcurses attr_off.3xcurses
MLINKS+=	attr_get.3xcurses attr_on.3xcurses
MLINKS+=	attr_get.3xcurses attr_set.3xcurses
MLINKS+=	attr_get.3xcurses color_set.3xcurses
MLINKS+=	attr_get.3xcurses wattr_get.3xcurses
MLINKS+=	attr_get.3xcurses wattr_off.3xcurses
MLINKS+=	attr_get.3xcurses wattr_on.3xcurses
MLINKS+=	attr_get.3xcurses wattr_set.3xcurses
MLINKS+=	attr_get.3xcurses wcolor_set.3xcurses
MLINKS+=	attroff.3xcurses attron.3xcurses
MLINKS+=	attroff.3xcurses attrset.3xcurses
MLINKS+=	attroff.3xcurses wattroff.3xcurses
MLINKS+=	attroff.3xcurses wattron.3xcurses
MLINKS+=	attroff.3xcurses wattrset.3xcurses
MLINKS+=	beep.3xcurses flash.3xcurses
MLINKS+=	bkgd.3xcurses bkgdset.3xcurses
MLINKS+=	bkgd.3xcurses getbkgd.3xcurses
MLINKS+=	bkgd.3xcurses wbkgd.3xcurses
MLINKS+=	bkgd.3xcurses wbkgdset.3xcurses
MLINKS+=	bkgrnd.3xcurses bkgrndset.3xcurses
MLINKS+=	bkgrnd.3xcurses getbkgrnd.3xcurses
MLINKS+=	bkgrnd.3xcurses wbkgrnd.3xcurses
MLINKS+=	bkgrnd.3xcurses wbkgrndset.3xcurses
MLINKS+=	bkgrnd.3xcurses wgetbkgrnd.3xcurses
MLINKS+=	border.3xcurses box.3xcurses
MLINKS+=	border.3xcurses wborder.3xcurses
MLINKS+=	border_set.3xcurses box_set.3xcurses
MLINKS+=	border_set.3xcurses wborder_set.3xcurses
MLINKS+=	can_change_color.3xcurses COLORS.3xcurses
MLINKS+=	can_change_color.3xcurses COLOR_PAIR.3xcurses
MLINKS+=	can_change_color.3xcurses COLOR_PAIRS.3xcurses
MLINKS+=	can_change_color.3xcurses PAIR_NUMBER.3xcurses
MLINKS+=	can_change_color.3xcurses color_content.3xcurses
MLINKS+=	can_change_color.3xcurses has_colors.3xcurses
MLINKS+=	can_change_color.3xcurses init_color.3xcurses
MLINKS+=	can_change_color.3xcurses init_pair.3xcurses
MLINKS+=	can_change_color.3xcurses pair_content.3xcurses
MLINKS+=	can_change_color.3xcurses start_color.3xcurses
MLINKS+=	cbreak.3xcurses nocbreak.3xcurses
MLINKS+=	cbreak.3xcurses noraw.3xcurses
MLINKS+=	cbreak.3xcurses raw.3xcurses
MLINKS+=	chgat.3xcurses mvchgat.3xcurses
MLINKS+=	chgat.3xcurses mvwchgat.3xcurses
MLINKS+=	chgat.3xcurses wchgat.3xcurses
MLINKS+=	clear.3xcurses erase.3xcurses
MLINKS+=	clear.3xcurses wclear.3xcurses
MLINKS+=	clear.3xcurses werase.3xcurses
MLINKS+=	clearok.3xcurses idlok.3xcurses
MLINKS+=	clearok.3xcurses leaveok.3xcurses
MLINKS+=	clearok.3xcurses scrollok.3xcurses
MLINKS+=	clearok.3xcurses setscrreg.3xcurses
MLINKS+=	clearok.3xcurses wsetscrreg.3xcurses
MLINKS+=	clrtobot.3xcurses wclrtobot.3xcurses
MLINKS+=	clrtoeol.3xcurses wclrtoeol.3xcurses
MLINKS+=	def_prog_mode.3xcurses def_shell_mode.3xcurses
MLINKS+=	def_prog_mode.3xcurses reset_prog_mode.3xcurses
MLINKS+=	def_prog_mode.3xcurses reset_shell_mode.3xcurses
MLINKS+=	del_curterm.3xcurses restartterm.3xcurses
MLINKS+=	del_curterm.3xcurses set_curterm.3xcurses
MLINKS+=	del_curterm.3xcurses setupterm.3xcurses
MLINKS+=	delch.3xcurses mvdelch.3xcurses
MLINKS+=	delch.3xcurses mvwdelch.3xcurses
MLINKS+=	delch.3xcurses wdelch.3xcurses
MLINKS+=	deleteln.3xcurses wdeleteln.3xcurses
MLINKS+=	derwin.3xcurses newwin.3xcurses
MLINKS+=	derwin.3xcurses subwin.3xcurses
MLINKS+=	doupdate.3xcurses refresh.3xcurses
MLINKS+=	doupdate.3xcurses wnoutrefresh.3xcurses
MLINKS+=	doupdate.3xcurses wrefresh.3xcurses
MLINKS+=	echo.3xcurses noecho.3xcurses
MLINKS+=	echo_wchar.3xcurses wecho_wchar.3xcurses
MLINKS+=	echochar.3xcurses wechochar.3xcurses
MLINKS+=	endwin.3xcurses isendwin.3xcurses
MLINKS+=	erasechar.3xcurses erasewchar.3xcurses
MLINKS+=	erasechar.3xcurses killchar.3xcurses
MLINKS+=	erasechar.3xcurses killwchar.3xcurses
MLINKS+=	get_wch.3xcurses mvget_wch.3xcurses
MLINKS+=	get_wch.3xcurses mvwget_wch.3xcurses
MLINKS+=	get_wch.3xcurses wget_wch.3xcurses
MLINKS+=	getbegyx.3xcurses getmaxyx.3xcurses
MLINKS+=	getbegyx.3xcurses getparyx.3xcurses
MLINKS+=	getbegyx.3xcurses getyx.3xcurses
MLINKS+=	getch.3xcurses mvgetch.3xcurses
MLINKS+=	getch.3xcurses mvwgetch.3xcurses
MLINKS+=	getch.3xcurses wgetch.3xcurses
MLINKS+=	getn_wstr.3xcurses get_wstr.3xcurses
MLINKS+=	getn_wstr.3xcurses mvget_wstr.3xcurses
MLINKS+=	getn_wstr.3xcurses mvgetn_wstr.3xcurses
MLINKS+=	getn_wstr.3xcurses mvwget_wstr.3xcurses
MLINKS+=	getn_wstr.3xcurses mvwgetn_wstr.3xcurses
MLINKS+=	getn_wstr.3xcurses wget_wstr.3xcurses
MLINKS+=	getn_wstr.3xcurses wgetn_wstr.3xcurses
MLINKS+=	getnstr.3xcurses getstr.3xcurses
MLINKS+=	getnstr.3xcurses mvgetnstr.3xcurses
MLINKS+=	getnstr.3xcurses mvgetstr.3xcurses
MLINKS+=	getnstr.3xcurses mvwgetnstr.3xcurses
MLINKS+=	getnstr.3xcurses mvwgetstr.3xcurses
MLINKS+=	getnstr.3xcurses wgetnstr.3xcurses
MLINKS+=	getnstr.3xcurses wgetstr.3xcurses
MLINKS+=	getwin.3xcurses putwin.3xcurses
MLINKS+=	has_ic.3xcurses has_il.3xcurses
MLINKS+=	hline.3xcurses mvhline.3xcurses
MLINKS+=	hline.3xcurses mvvline.3xcurses
MLINKS+=	hline.3xcurses mvwhline.3xcurses
MLINKS+=	hline.3xcurses mvwvline.3xcurses
MLINKS+=	hline.3xcurses vline.3xcurses
MLINKS+=	hline.3xcurses whline.3xcurses
MLINKS+=	hline.3xcurses wvline.3xcurses
MLINKS+=	hline_set.3xcurses mvhline_set.3xcurses
MLINKS+=	hline_set.3xcurses mvvline_set.3xcurses
MLINKS+=	hline_set.3xcurses mvwhline_set.3xcurses
MLINKS+=	hline_set.3xcurses mvwvline_set.3xcurses
MLINKS+=	hline_set.3xcurses vline_set.3xcurses
MLINKS+=	hline_set.3xcurses whline_set.3xcurses
MLINKS+=	hline_set.3xcurses wvline_set.3xcurses
MLINKS+=	in_wch.3xcurses mvin_wch.3xcurses
MLINKS+=	in_wch.3xcurses mvwin_wch.3xcurses
MLINKS+=	in_wch.3xcurses win_wch.3xcurses
MLINKS+=	in_wchnstr.3xcurses in_wchstr.3xcurses
MLINKS+=	in_wchnstr.3xcurses mvin_wchnstr.3xcurses
MLINKS+=	in_wchnstr.3xcurses mvin_wchstr.3xcurses
MLINKS+=	in_wchnstr.3xcurses mvwin_wchnstr.3xcurses
MLINKS+=	in_wchnstr.3xcurses mvwin_wchstr.3xcurses
MLINKS+=	in_wchnstr.3xcurses win_wchnstr.3xcurses
MLINKS+=	in_wchnstr.3xcurses win_wchstr.3xcurses
MLINKS+=	inch.3xcurses mvinch.3xcurses
MLINKS+=	inch.3xcurses mvwinch.3xcurses
MLINKS+=	inch.3xcurses winch.3xcurses
MLINKS+=	inchnstr.3xcurses inchstr.3xcurses
MLINKS+=	inchnstr.3xcurses mvinchnstr.3xcurses
MLINKS+=	inchnstr.3xcurses mvinchstr.3xcurses
MLINKS+=	inchnstr.3xcurses mvwinchnstr.3xcurses
MLINKS+=	inchnstr.3xcurses mvwinchstr.3xcurses
MLINKS+=	inchnstr.3xcurses winchnstr.3xcurses
MLINKS+=	inchnstr.3xcurses winchstr.3xcurses
MLINKS+=	initscr.3xcurses newterm.3xcurses
MLINKS+=	innstr.3xcurses instr.3xcurses
MLINKS+=	innstr.3xcurses mvinnstr.3xcurses
MLINKS+=	innstr.3xcurses mvinstr.3xcurses
MLINKS+=	innstr.3xcurses mvwinnstr.3xcurses
MLINKS+=	innstr.3xcurses mvwinstr.3xcurses
MLINKS+=	innstr.3xcurses winnstr.3xcurses
MLINKS+=	innstr.3xcurses winstr.3xcurses
MLINKS+=	innwstr.3xcurses inwstr.3xcurses
MLINKS+=	innwstr.3xcurses mvinnwstr.3xcurses
MLINKS+=	innwstr.3xcurses mvinwstr.3xcurses
MLINKS+=	innwstr.3xcurses mvwinnwstr.3xcurses
MLINKS+=	innwstr.3xcurses mvwinwstr.3xcurses
MLINKS+=	innwstr.3xcurses winnwstr.3xcurses
MLINKS+=	innwstr.3xcurses winwstr.3xcurses
MLINKS+=	ins_nwstr.3xcurses ins_wstr.3xcurses
MLINKS+=	ins_nwstr.3xcurses mvins_nwstr.3xcurses
MLINKS+=	ins_nwstr.3xcurses mvins_wstr.3xcurses
MLINKS+=	ins_nwstr.3xcurses mvwins_nwstr.3xcurses
MLINKS+=	ins_nwstr.3xcurses mvwins_wstr.3xcurses
MLINKS+=	ins_nwstr.3xcurses wins_nwstr.3xcurses
MLINKS+=	ins_nwstr.3xcurses wins_wstr.3xcurses
MLINKS+=	ins_wch.3xcurses mvins_wch.3xcurses
MLINKS+=	ins_wch.3xcurses mvwins_wch.3xcurses
MLINKS+=	ins_wch.3xcurses wins_wch.3xcurses
MLINKS+=	insch.3xcurses mvinsch.3xcurses
MLINKS+=	insch.3xcurses mvwinsch.3xcurses
MLINKS+=	insch.3xcurses winsch.3xcurses
MLINKS+=	insdelln.3xcurses winsdelln.3xcurses
MLINKS+=	insertln.3xcurses winsertln.3xcurses
MLINKS+=	insnstr.3xcurses insstr.3xcurses
MLINKS+=	insnstr.3xcurses mvinsnstr.3xcurses
MLINKS+=	insnstr.3xcurses mvinsstr.3xcurses
MLINKS+=	insnstr.3xcurses mvwinsnstr.3xcurses
MLINKS+=	insnstr.3xcurses mvwinsstr.3xcurses
MLINKS+=	insnstr.3xcurses winsnstr.3xcurses
MLINKS+=	insnstr.3xcurses winsstr.3xcurses
MLINKS+=	is_linetouched.3xcurses is_wintouched.3xcurses
MLINKS+=	is_linetouched.3xcurses touchline.3xcurses
MLINKS+=	is_linetouched.3xcurses touchwin.3xcurses
MLINKS+=	is_linetouched.3xcurses untouchwin.3xcurses
MLINKS+=	is_linetouched.3xcurses wtouchln.3xcurses
MLINKS+=	keyname.3xcurses key_name.3xcurses
MLINKS+=	move.3xcurses wmove.3xcurses
MLINKS+=	mvprintw.3xcurses mvwprintw.3xcurses
MLINKS+=	mvprintw.3xcurses printw.3xcurses
MLINKS+=	mvprintw.3xcurses wprintw.3xcurses
MLINKS+=	mvscanw.3xcurses mvwscanw.3xcurses
MLINKS+=	mvscanw.3xcurses scanw.3xcurses
MLINKS+=	mvscanw.3xcurses wscanw.3xcurses
MLINKS+=	newpad.3xcurses pnoutrefresh.3xcurses
MLINKS+=	newpad.3xcurses prefresh.3xcurses
MLINKS+=	newpad.3xcurses subpad.3xcurses
MLINKS+=	nl.3xcurses nonl.3xcurses
MLINKS+=	noqiflush.3xcurses qiflush.3xcurses
MLINKS+=	notimeout.3xcurses timeout.3xcurses
MLINKS+=	notimeout.3xcurses wtimeout.3xcurses
MLINKS+=	overlay.3xcurses overwrite.3xcurses
MLINKS+=	pechochar.3xcurses pecho_wchar.3xcurses
MLINKS+=	putp.3xcurses tputs.3xcurses
MLINKS+=	redrawwin.3xcurses wredrawln.3xcurses
MLINKS+=	resetty.3xcurses savetty.3xcurses
MLINKS+=	scr_dump.3xcurses scr_init.3xcurses
MLINKS+=	scr_dump.3xcurses scr_restore.3xcurses
MLINKS+=	scr_dump.3xcurses scr_set.3xcurses
MLINKS+=	scrl.3xcurses scroll.3xcurses
MLINKS+=	scrl.3xcurses wscrl.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_attr_off.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_attr_on.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_attr_set.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_attron.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_attrset.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_clear.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_color.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_init.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_label.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_noutrefresh.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_refresh.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_restore.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_set.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_touch.3xcurses
MLINKS+=	slk_attroff.3xcurses slk_wset.3xcurses
MLINKS+=	standend.3xcurses standout.3xcurses
MLINKS+=	standend.3xcurses wstandend.3xcurses
MLINKS+=	standend.3xcurses wstandout.3xcurses
MLINKS+=	syncok.3xcurses wcursyncup.3xcurses
MLINKS+=	syncok.3xcurses wsyncdown.3xcurses
MLINKS+=	syncok.3xcurses wsyncup.3xcurses
MLINKS+=	termattrs.3xcurses term_attrs.3xcurses
MLINKS+=	tgetent.3xcurses tgetflag.3xcurses
MLINKS+=	tgetent.3xcurses tgetnum.3xcurses
MLINKS+=	tgetent.3xcurses tgetstr.3xcurses
MLINKS+=	tgetent.3xcurses tgoto.3xcurses
MLINKS+=	tigetflag.3xcurses tigetnum.3xcurses
MLINKS+=	tigetflag.3xcurses tigetstr.3xcurses
MLINKS+=	tigetflag.3xcurses tparm.3xcurses
MLINKS+=	ungetch.3xcurses unget_wch.3xcurses
MLINKS+=	vidattr.3xcurses vid_attr.3xcurses
MLINKS+=	vidattr.3xcurses vid_puts.3xcurses
MLINKS+=	vidattr.3xcurses vidputs.3xcurses

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
