MAN = libpicl.3picl \
      picl_find_node.3picl \
      picl_get_first_prop.3picl \
      picl_get_frutree_parent.3picl \
      picl_get_next_by_row.3picl \
      picl_get_node_by_path.3picl \
      picl_get_prop_by_name.3picl \
      picl_get_propinfo.3picl \
      picl_get_propinfo_by_name.3picl \
      picl_get_propval.3picl \
      picl_get_root.3picl \
      picl_initialize.3picl \
      picl_set_propval.3picl \
      picl_shutdown.3picl \
      picl_strerror.3picl \
      picl_wait.3picl \
      picl_walk_tree_by_class.3picl


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
