#
# Copyright 2015 Nexenta Systems, Inc. All rights reserved.
#

include ../Makefile.com
include ../../Makefile.lib.64

LIBS = $(DYNLIB) $(LINTLIB)

all: $(LIBS)

install: all $(ROOTLIBS64) $(ROOTLINKS64)
