MAN = Intro.5 \
      acl.5 \
      ad.5 \
      ascii.5 \
      attributes.5 \
      audit_binfile.5 \
      audit_remote.5 \
      audit_syslog.5 \
      brands.5 \
      byteorder.5 \
      cancellation.5 \
      charmap.5 \
      condition.5 \
      crypt_bsdbf.5 \
      crypt_bsdmd5.5 \
      crypt_sha256.5 \
      crypt_sha512.5 \
      crypt_sunmd5.5 \
      crypt_unix.5 \
      device_clean.5 \
      dhcp.5 \
      environ.5 \
      epoll.5 \
      eqnchar.5 \
      eventfd.5 \
      extendedFILE.5 \
      filesystem.5 \
      fnmatch.5 \
      formats.5 \
      fsattr.5 \
      gss_auth_rules.5 \
      hal.5 \
      iconv.5 \
      iconv_unicode.5 \
      ieee802.3.5 \
      ieee802.11.5 \
      ipfilter.5 \
      isalist.5 \
      kerberos.5 \
      krb5_auth_rules.5 \
      krb5envvar.5 \
      largefile.5 \
      lf64.5 \
      lfcompile.5 \
      lfcompile64.5 \
      locale.5 \
      man.5 \
      me.5 \
      mech_spnego.5 \
      mm.5 \
      ms.5 \
      mutex.5 \
      nfssec.5 \
      pam_allow.5 \
      pam_authtok_check.5 \
      pam_authtok_get.5 \
      pam_authtok_store.5 \
      pam_deny.5 \
      pam_dhkeys.5 \
      pam_dial_auth.5 \
      pam_krb5.5 \
      pam_krb5_migrate.5 \
      pam_ldap.5 \
      pam_list.5 \
      pam_passwd_auth.5 \
      pam_rhosts_auth.5 \
      pam_roles.5 \
      pam_sample.5 \
      pam_smb_passwd.5 \
      pam_smbfs_login.5 \
      pam_timestamp.5 \
      pam_unix_account.5 \
      pam_unix_auth.5 \
      pam_unix_cred.5 \
      pam_unix_session.5 \
      pkcs11_kernel.5 \
      pkcs11_softtoken.5 \
      privileges.5 \
      prof.5 \
      rbac.5 \
      regex.5 \
      regexp.5 \
      resource_controls.5 \
      security-flags.5 \
      smf.5 \
      smf_bootstrap.5 \
      smf_method.5 \
      smf_restarter.5 \
      smf_security.5 \
      smf_template.5 \
      standards.5 \
      sticky.5 \
      tecla.5 \
      term.5 \
      threads.5 \
      timerfd.5 \
      vgrindefs.5 \
      zones.5 \
      zpool-features.5

MLINKS+=	Intro.5 intro.5
MLINKS+=	attributes.5 CSI.5
MLINKS+=	attributes.5 MT-Level.5
MLINKS+=	attributes.5 architecture.5
MLINKS+=	attributes.5 availability.5
MLINKS+=	attributes.5 stability.5
MLINKS+=	attributes.5 standard.5
MLINKS+=	byteorder.5 endian.5
MLINKS+=	rbac.5 RBAC.5
MLINKS+=	regexp.5 advance.5
MLINKS+=	regexp.5 compile.5
MLINKS+=	regexp.5 step.5
MLINKS+=	standards.5 ANSI.5
MLINKS+=	standards.5 C++.5
MLINKS+=	standards.5 C.5
MLINKS+=	standards.5 ISO.5
MLINKS+=	standards.5 POSIX.1.5
MLINKS+=	standards.5 POSIX.2.5
MLINKS+=	standards.5 POSIX.5
MLINKS+=	standards.5 SUS.5
MLINKS+=	standards.5 SUSv2.5
MLINKS+=	standards.5 SUSv3.5
MLINKS+=	standards.5 SVID.5
MLINKS+=	standards.5 SVID3.5
MLINKS+=	standards.5 XNS.5
MLINKS+=	standards.5 XNS4.5
MLINKS+=	standards.5 XNS5.5
MLINKS+=	standards.5 XPG.5
MLINKS+=	standards.5 XPG3.5
MLINKS+=	standards.5 XPG4.5
MLINKS+=	standards.5 XPG4v2.5
MLINKS+=	tecla.5 teclarc.5
MLINKS+=	threads.5 pthreads.5

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
