#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = recovery/client
STFDESC = client.vars stf_description
PROGS = bad_seqid clnt_recmaxname01 clnt_recnattr01 \
	clntrecov_pos01 clntrecov_pos03 clntrecov_pos04 \
	clntrecov_pos05 clntrecov_pos06 clntrecov_pos07 \
	clntrecov_pos08 clntrecov_pos09 clntrecov_pos10 \
	clntrecov_rw_pos01 clntrecov_rw_pos02 configure \
	isserverup open_downgrade unconfigure
	
include ../../Makefile.test
