#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TPLDIR = svccfg/templates
TEST = $(TPLDIR)/prop_pattern_units
DESC = config.env prop_pattern_loctext.xml prop_pattern_units.xml \
	stf_description
TCS = prop_pattern_units_001 prop_pattern_units_002 prop_pattern_units_003 \
	prop_pattern_units_004 prop_pattern_units_005 prop_pattern_units_006 \
	prop_pattern_units_007 prop_pattern_units_008 prop_pattern_units_009 \
	prop_pattern_units_010 prop_pattern_units_011

include ../../../Makefile.test
