#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = svccfg/import-export/lists
DESC = astring.in.xml hostname.in.xml time.in.xml \
	boolean.in.xml integer.in.xml uri.in.xml \
	count.in.xml net_address_v4.in.xml ustring.in.xml \
	fmri.in.xml net_address_v6.in.xml host.in.xml \
	opaque.in.xml services stf_description	
TCS = 

include ../../../Makefile.test
