#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = svccfg/import
DESC = import_001.xml import_002.xml import_003_profile.xml \
	import_006.xml import_008.xml import_009.xml import_011.xml \
	import_012a.xml import_012b.xml import_012c.xml stf_description
TCS = import_001 import_002 import_003 import_004 import_005 \
	import_006 import_007 import_008 import_009 import_010 \
	import_011 import_012 svccfg_import_setup

include ../../Makefile.test
