INCDIR=	/usr/platform/i86xpv/include/sys
INCS=	balloon.h	\
	machprivregs.h	\
	xen_mmu.h \
	xpv_impl.h

.include <prog.mk>
.include <inc.mk>

REPOROOT = ${.CURDIR:H:H:H:H:H:H:H}
.include <${REPOROOT}/Makefile.cfgparam>
