INCDIR=	/usr/platform/i86xpv/include/sys
INCS=	balloon.h	\
	machprivregs.h	\
	xen_mmu.h \
	xpv_impl.h

.include <unleashed.mk>
.include <prog.mk>
.include <inc.mk>

.include <${SRCTOP}/Makefile.cfgparam>
