MAN = ea_error.3exacct \
      ea_open.3exacct \
      ea_pack_object.3exacct \
      ea_set_item.3exacct

MLINKS+=	ea_open.3exacct ea_close.3exacct
MLINKS+=	ea_pack_object.3exacct ea_copy_object.3exacct
MLINKS+=	ea_pack_object.3exacct ea_copy_object_tree.3exacct
MLINKS+=	ea_pack_object.3exacct ea_get_creator.3exacct
MLINKS+=	ea_pack_object.3exacct ea_get_hostname.3exacct
MLINKS+=	ea_pack_object.3exacct ea_get_object.3exacct
MLINKS+=	ea_pack_object.3exacct ea_get_object_tree.3exacct
MLINKS+=	ea_pack_object.3exacct ea_next_object.3exacct
MLINKS+=	ea_pack_object.3exacct ea_previous_object.3exacct
MLINKS+=	ea_pack_object.3exacct ea_unpack_object.3exacct
MLINKS+=	ea_pack_object.3exacct ea_write_object.3exacct
MLINKS+=	ea_set_item.3exacct ea_alloc.3exacct
MLINKS+=	ea_set_item.3exacct ea_attach_to_group.3exacct
MLINKS+=	ea_set_item.3exacct ea_attach_to_object.3exacct
MLINKS+=	ea_set_item.3exacct ea_free.3exacct
MLINKS+=	ea_set_item.3exacct ea_free_item.3exacct
MLINKS+=	ea_set_item.3exacct ea_free_object.3exacct
MLINKS+=	ea_set_item.3exacct ea_match_object_catalog.3exacct
MLINKS+=	ea_set_item.3exacct ea_set_group.3exacct
MLINKS+=	ea_set_item.3exacct ea_strdup.3exacct
MLINKS+=	ea_set_item.3exacct ea_strfree.3exacct

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
