MAN = mp.3mp 

MLINKS+=	mp.3mp mp_gcd.3mp
MLINKS+=	mp.3mp mp_itom.3mp
MLINKS+=	mp.3mp mp_madd.3mp
MLINKS+=	mp.3mp mp_mcmp.3mp
MLINKS+=	mp.3mp mp_mdiv.3mp
MLINKS+=	mp.3mp mp_mfree.3mp
MLINKS+=	mp.3mp mp_min.3mp
MLINKS+=	mp.3mp mp_mout.3mp
MLINKS+=	mp.3mp mp_msqrt.3mp
MLINKS+=	mp.3mp mp_msub.3mp
MLINKS+=	mp.3mp mp_mtox.3mp
MLINKS+=	mp.3mp mp_mult.3mp
MLINKS+=	mp.3mp mp_pow.3mp
MLINKS+=	mp.3mp mp_rpow.3mp
MLINKS+=	mp.3mp mp_sdiv.3mp
MLINKS+=	mp.3mp mp_xtom.3mp

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
