#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3xcurses/COLS.3xcurses
file path=usr/share/man/man3xcurses/LINES.3xcurses
file path=usr/share/man/man3xcurses/add_wch.3xcurses
file path=usr/share/man/man3xcurses/add_wchnstr.3xcurses
file path=usr/share/man/man3xcurses/addch.3xcurses
file path=usr/share/man/man3xcurses/addchstr.3xcurses
file path=usr/share/man/man3xcurses/addnstr.3xcurses
file path=usr/share/man/man3xcurses/addnwstr.3xcurses
file path=usr/share/man/man3xcurses/attr_get.3xcurses
file path=usr/share/man/man3xcurses/attroff.3xcurses
file path=usr/share/man/man3xcurses/baudrate.3xcurses
file path=usr/share/man/man3xcurses/beep.3xcurses
file path=usr/share/man/man3xcurses/bkgd.3xcurses
file path=usr/share/man/man3xcurses/bkgrnd.3xcurses
file path=usr/share/man/man3xcurses/border.3xcurses
file path=usr/share/man/man3xcurses/border_set.3xcurses
file path=usr/share/man/man3xcurses/can_change_color.3xcurses
file path=usr/share/man/man3xcurses/cbreak.3xcurses
file path=usr/share/man/man3xcurses/chgat.3xcurses
file path=usr/share/man/man3xcurses/clear.3xcurses
file path=usr/share/man/man3xcurses/clearok.3xcurses
file path=usr/share/man/man3xcurses/clrtobot.3xcurses
file path=usr/share/man/man3xcurses/clrtoeol.3xcurses
file path=usr/share/man/man3xcurses/copywin.3xcurses
file path=usr/share/man/man3xcurses/cur_term.3xcurses
file path=usr/share/man/man3xcurses/curs_set.3xcurses
file path=usr/share/man/man3xcurses/curscr.3xcurses
file path=usr/share/man/man3xcurses/curses.3xcurses
file path=usr/share/man/man3xcurses/def_prog_mode.3xcurses
file path=usr/share/man/man3xcurses/del_curterm.3xcurses
file path=usr/share/man/man3xcurses/delay_output.3xcurses
file path=usr/share/man/man3xcurses/delch.3xcurses
file path=usr/share/man/man3xcurses/deleteln.3xcurses
file path=usr/share/man/man3xcurses/delscreen.3xcurses
file path=usr/share/man/man3xcurses/delwin.3xcurses
file path=usr/share/man/man3xcurses/derwin.3xcurses
file path=usr/share/man/man3xcurses/doupdate.3xcurses
file path=usr/share/man/man3xcurses/dupwin.3xcurses
file path=usr/share/man/man3xcurses/echo.3xcurses
file path=usr/share/man/man3xcurses/echo_wchar.3xcurses
file path=usr/share/man/man3xcurses/echochar.3xcurses
file path=usr/share/man/man3xcurses/endwin.3xcurses
file path=usr/share/man/man3xcurses/erasechar.3xcurses
file path=usr/share/man/man3xcurses/filter.3xcurses
file path=usr/share/man/man3xcurses/flushinp.3xcurses
file path=usr/share/man/man3xcurses/get_wch.3xcurses
file path=usr/share/man/man3xcurses/getbegyx.3xcurses
file path=usr/share/man/man3xcurses/getcchar.3xcurses
file path=usr/share/man/man3xcurses/getch.3xcurses
file path=usr/share/man/man3xcurses/getn_wstr.3xcurses
file path=usr/share/man/man3xcurses/getnstr.3xcurses
file path=usr/share/man/man3xcurses/getwin.3xcurses
file path=usr/share/man/man3xcurses/halfdelay.3xcurses
file path=usr/share/man/man3xcurses/has_ic.3xcurses
file path=usr/share/man/man3xcurses/hline.3xcurses
file path=usr/share/man/man3xcurses/hline_set.3xcurses
file path=usr/share/man/man3xcurses/idcok.3xcurses
file path=usr/share/man/man3xcurses/immedok.3xcurses
file path=usr/share/man/man3xcurses/in_wch.3xcurses
file path=usr/share/man/man3xcurses/in_wchnstr.3xcurses
file path=usr/share/man/man3xcurses/inch.3xcurses
file path=usr/share/man/man3xcurses/inchnstr.3xcurses
file path=usr/share/man/man3xcurses/initscr.3xcurses
file path=usr/share/man/man3xcurses/innstr.3xcurses
file path=usr/share/man/man3xcurses/innwstr.3xcurses
file path=usr/share/man/man3xcurses/ins_nwstr.3xcurses
file path=usr/share/man/man3xcurses/ins_wch.3xcurses
file path=usr/share/man/man3xcurses/insch.3xcurses
file path=usr/share/man/man3xcurses/insdelln.3xcurses
file path=usr/share/man/man3xcurses/insertln.3xcurses
file path=usr/share/man/man3xcurses/insnstr.3xcurses
file path=usr/share/man/man3xcurses/intrflush.3xcurses
file path=usr/share/man/man3xcurses/is_linetouched.3xcurses
file path=usr/share/man/man3xcurses/keyname.3xcurses
file path=usr/share/man/man3xcurses/keypad.3xcurses
file path=usr/share/man/man3xcurses/libcurses.3xcurses
file path=usr/share/man/man3xcurses/longname.3xcurses
file path=usr/share/man/man3xcurses/meta.3xcurses
file path=usr/share/man/man3xcurses/move.3xcurses
file path=usr/share/man/man3xcurses/mvcur.3xcurses
file path=usr/share/man/man3xcurses/mvderwin.3xcurses
file path=usr/share/man/man3xcurses/mvprintw.3xcurses
file path=usr/share/man/man3xcurses/mvscanw.3xcurses
file path=usr/share/man/man3xcurses/mvwin.3xcurses
file path=usr/share/man/man3xcurses/napms.3xcurses
file path=usr/share/man/man3xcurses/newpad.3xcurses
file path=usr/share/man/man3xcurses/nl.3xcurses
file path=usr/share/man/man3xcurses/nodelay.3xcurses
file path=usr/share/man/man3xcurses/noqiflush.3xcurses
file path=usr/share/man/man3xcurses/notimeout.3xcurses
file path=usr/share/man/man3xcurses/overlay.3xcurses
file path=usr/share/man/man3xcurses/pechochar.3xcurses
file path=usr/share/man/man3xcurses/putp.3xcurses
file path=usr/share/man/man3xcurses/redrawwin.3xcurses
file path=usr/share/man/man3xcurses/resetty.3xcurses
file path=usr/share/man/man3xcurses/ripoffline.3xcurses
file path=usr/share/man/man3xcurses/scr_dump.3xcurses
file path=usr/share/man/man3xcurses/scrl.3xcurses
file path=usr/share/man/man3xcurses/set_term.3xcurses
file path=usr/share/man/man3xcurses/setcchar.3xcurses
file path=usr/share/man/man3xcurses/slk_attroff.3xcurses
file path=usr/share/man/man3xcurses/standend.3xcurses
file path=usr/share/man/man3xcurses/stdscr.3xcurses
file path=usr/share/man/man3xcurses/syncok.3xcurses
file path=usr/share/man/man3xcurses/termattrs.3xcurses
file path=usr/share/man/man3xcurses/termname.3xcurses
file path=usr/share/man/man3xcurses/tgetent.3xcurses
file path=usr/share/man/man3xcurses/tigetflag.3xcurses
file path=usr/share/man/man3xcurses/typeahead.3xcurses
file path=usr/share/man/man3xcurses/unctrl.3xcurses
file path=usr/share/man/man3xcurses/ungetch.3xcurses
file path=usr/share/man/man3xcurses/use_env.3xcurses
file path=usr/share/man/man3xcurses/vidattr.3xcurses
file path=usr/share/man/man3xcurses/vw_printw.3xcurses
file path=usr/share/man/man3xcurses/vw_scanw.3xcurses
file path=usr/share/man/man3xcurses/vwprintw.3xcurses
file path=usr/share/man/man3xcurses/vwscanw.3xcurses
file path=usr/share/man/man3xcurses/wunctrl.3xcurses
