#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3/Intro.3
file path=usr/share/man/man3/sockatmark.3
file path=usr/share/man/man3/CMSG_DATA.3
file path=usr/share/man/man3/readdir.3
file path=usr/share/man/man3/err.3
file path=usr/share/man/man3/fts.3
file path=usr/share/man/man3/alloca.3
file path=usr/share/man/man3/malloc.3
file path=usr/share/man/man3/posix_memalign.3
file path=usr/share/man/man3/unvis.3
file path=usr/share/man/man3/valloc.3
file path=usr/share/man/man3/vis.3
link path=usr/share/man/man3/intro.3 target=Intro.3
link path=usr/share/man/man3/CMSG_FIRSTHDR.3 target=CMSG_DATA.3
link path=usr/share/man/man3/CMSG_LEN.3 target=CMSG_DATA.3
link path=usr/share/man/man3/CMSG_NEXTHDR.3 target=CMSG_DATA.3
link path=usr/share/man/man3/CMSG_SPACE.3 target=CMSG_DATA.3
link path=usr/share/man/man3/readdir_r.3 target=readdir.3
link path=usr/share/man/man3/verr.3 target=err.3
link path=usr/share/man/man3/errc.3 target=err.3
link path=usr/share/man/man3/verrc.3 target=err.3
link path=usr/share/man/man3/errx.3 target=err.3
link path=usr/share/man/man3/verrx.3 target=err.3
link path=usr/share/man/man3/warn.3 target=err.3
link path=usr/share/man/man3/vwarn.3 target=err.3
link path=usr/share/man/man3/warnc.3 target=err.3
link path=usr/share/man/man3/vwarnc.3 target=err.3
link path=usr/share/man/man3/warnx.3 target=err.3
link path=usr/share/man/man3/vwarnx.3 target=err.3
link path=usr/share/man/man3/fts_children.3 target=fts.3
link path=usr/share/man/man3/fts_close.3 target=fts.3
link path=usr/share/man/man3/fts_open.3 target=fts.3
link path=usr/share/man/man3/fts_read.3 target=fts.3
link path=usr/share/man/man3/fts_set.3 target=fts.3
link path=usr/share/man/man3/calloc.3 target=malloc.3
link path=usr/share/man/man3/realloc.3 target=malloc.3
link path=usr/share/man/man3/reallocarray.3 target=malloc.3
link path=usr/share/man/man3/free.3 target=malloc.3
link path=usr/share/man/man3/memalign.3 target=posix_memalign.3
link path=usr/share/man/man3/stravis.3 target=vis.3
link path=usr/share/man/man3/strnvis.3 target=vis.3
link path=usr/share/man/man3/strnunvis.3 target=unvis.3
link path=usr/share/man/man3/strunvis.3 target=unvis.3
link path=usr/share/man/man3/strvis.3 target=vis.3
link path=usr/share/man/man3/strvisx.3 target=vis.3
