#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3curses/curs_addch.3curses
file path=usr/share/man/man3curses/curs_addchstr.3curses
file path=usr/share/man/man3curses/curs_addstr.3curses
file path=usr/share/man/man3curses/curs_addwch.3curses
file path=usr/share/man/man3curses/curs_addwchstr.3curses
file path=usr/share/man/man3curses/curs_addwstr.3curses
file path=usr/share/man/man3curses/curs_alecompat.3curses
file path=usr/share/man/man3curses/curs_attr.3curses
file path=usr/share/man/man3curses/curs_beep.3curses
file path=usr/share/man/man3curses/curs_bkgd.3curses
file path=usr/share/man/man3curses/curs_border.3curses
file path=usr/share/man/man3curses/curs_clear.3curses
file path=usr/share/man/man3curses/curs_color.3curses
file path=usr/share/man/man3curses/curs_delch.3curses
file path=usr/share/man/man3curses/curs_deleteln.3curses
file path=usr/share/man/man3curses/curs_getch.3curses
file path=usr/share/man/man3curses/curs_getstr.3curses
file path=usr/share/man/man3curses/curs_getwch.3curses
file path=usr/share/man/man3curses/curs_getwstr.3curses
file path=usr/share/man/man3curses/curs_getyx.3curses
file path=usr/share/man/man3curses/curs_inch.3curses
file path=usr/share/man/man3curses/curs_inchstr.3curses
file path=usr/share/man/man3curses/curs_initscr.3curses
file path=usr/share/man/man3curses/curs_inopts.3curses
file path=usr/share/man/man3curses/curs_insch.3curses
file path=usr/share/man/man3curses/curs_insstr.3curses
file path=usr/share/man/man3curses/curs_instr.3curses
file path=usr/share/man/man3curses/curs_inswch.3curses
file path=usr/share/man/man3curses/curs_inswstr.3curses
file path=usr/share/man/man3curses/curs_inwch.3curses
file path=usr/share/man/man3curses/curs_inwchstr.3curses
file path=usr/share/man/man3curses/curs_inwstr.3curses
file path=usr/share/man/man3curses/curs_kernel.3curses
file path=usr/share/man/man3curses/curs_move.3curses
file path=usr/share/man/man3curses/curs_outopts.3curses
file path=usr/share/man/man3curses/curs_overlay.3curses
file path=usr/share/man/man3curses/curs_pad.3curses
file path=usr/share/man/man3curses/curs_printw.3curses
file path=usr/share/man/man3curses/curs_refresh.3curses
file path=usr/share/man/man3curses/curs_scanw.3curses
file path=usr/share/man/man3curses/curs_scr_dump.3curses
file path=usr/share/man/man3curses/curs_scroll.3curses
file path=usr/share/man/man3curses/curs_slk.3curses
file path=usr/share/man/man3curses/curs_termattrs.3curses
file path=usr/share/man/man3curses/curs_termcap.3curses
file path=usr/share/man/man3curses/curs_terminfo.3curses
file path=usr/share/man/man3curses/curs_touch.3curses
file path=usr/share/man/man3curses/curs_util.3curses
file path=usr/share/man/man3curses/curs_window.3curses
file path=usr/share/man/man3curses/curses.3curses
file path=usr/share/man/man3curses/form_cursor.3curses
file path=usr/share/man/man3curses/form_data.3curses
file path=usr/share/man/man3curses/form_driver.3curses
file path=usr/share/man/man3curses/form_field.3curses
file path=usr/share/man/man3curses/form_field_attributes.3curses
file path=usr/share/man/man3curses/form_field_buffer.3curses
file path=usr/share/man/man3curses/form_field_info.3curses
file path=usr/share/man/man3curses/form_field_just.3curses
file path=usr/share/man/man3curses/form_field_new.3curses
file path=usr/share/man/man3curses/form_field_opts.3curses
file path=usr/share/man/man3curses/form_field_userptr.3curses
file path=usr/share/man/man3curses/form_field_validation.3curses
file path=usr/share/man/man3curses/form_fieldtype.3curses
file path=usr/share/man/man3curses/form_hook.3curses
file path=usr/share/man/man3curses/form_new.3curses
file path=usr/share/man/man3curses/form_new_page.3curses
file path=usr/share/man/man3curses/form_opts.3curses
file path=usr/share/man/man3curses/form_page.3curses
file path=usr/share/man/man3curses/form_post.3curses
file path=usr/share/man/man3curses/form_userptr.3curses
file path=usr/share/man/man3curses/form_win.3curses
file path=usr/share/man/man3curses/forms.3curses
file path=usr/share/man/man3curses/menu_attributes.3curses
file path=usr/share/man/man3curses/menu_cursor.3curses
file path=usr/share/man/man3curses/menu_driver.3curses
file path=usr/share/man/man3curses/menu_format.3curses
file path=usr/share/man/man3curses/menu_hook.3curses
file path=usr/share/man/man3curses/menu_item_current.3curses
file path=usr/share/man/man3curses/menu_item_name.3curses
file path=usr/share/man/man3curses/menu_item_new.3curses
file path=usr/share/man/man3curses/menu_item_opts.3curses
file path=usr/share/man/man3curses/menu_item_userptr.3curses
file path=usr/share/man/man3curses/menu_item_value.3curses
file path=usr/share/man/man3curses/menu_item_visible.3curses
file path=usr/share/man/man3curses/menu_items.3curses
file path=usr/share/man/man3curses/menu_mark.3curses
file path=usr/share/man/man3curses/menu_new.3curses
file path=usr/share/man/man3curses/menu_opts.3curses
file path=usr/share/man/man3curses/menu_pattern.3curses
file path=usr/share/man/man3curses/menu_post.3curses
file path=usr/share/man/man3curses/menu_userptr.3curses
file path=usr/share/man/man3curses/menu_win.3curses
file path=usr/share/man/man3curses/menus.3curses
file path=usr/share/man/man3curses/panel_above.3curses
file path=usr/share/man/man3curses/panel_move.3curses
file path=usr/share/man/man3curses/panel_new.3curses
file path=usr/share/man/man3curses/panel_show.3curses
file path=usr/share/man/man3curses/panel_top.3curses
file path=usr/share/man/man3curses/panel_update.3curses
file path=usr/share/man/man3curses/panel_userptr.3curses
file path=usr/share/man/man3curses/panel_window.3curses
file path=usr/share/man/man3curses/panels.3curses
