MAN = devid_get.3devid 

MLINKS+=	devid_get.3devid devid_compare.3devid
MLINKS+=	devid_get.3devid devid_deviceid_to_nmlist.3devid
MLINKS+=	devid_get.3devid devid_free.3devid
MLINKS+=	devid_get.3devid devid_free_nmlist.3devid
MLINKS+=	devid_get.3devid devid_get_minor_name.3devid
MLINKS+=	devid_get.3devid devid_sizeof.3devid
MLINKS+=	devid_get.3devid devid_str_decode.3devid
MLINKS+=	devid_get.3devid devid_str_encode.3devid
MLINKS+=	devid_get.3devid devid_str_free.3devid
MLINKS+=	devid_get.3devid devid_valid.3devid

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
