/* GENERATED FILE - DO NOT EDIT */

#ifndef	_SYS_CFGPARAM_H
#define	_SYS_CFGPARAM_H

#define	CONFIG_MACH i386
#define	CONFIG_MACH32 i86
#define	CONFIG_MACH64 amd64
#define	CONFIG_BUILD_KMOD_32
#define	CONFIG_BUILD_KMOD_64
#define	CONFIG_LINUX_CORE_SUPPORT
#define	CONFIG_SMB_PRINTING
#define	CONFIG_LOFI
#define	CONFIG_RAMDISK
#define	CONFIG_RANDOM
#define	CONFIG_VIRTIO
#define	CONFIG_E1000G
#define	CONFIG_IGB
#define	CONFIG_IXGBE
#define	CONFIG_SFXGE
#define	CONFIG_VIRTIO_NET
#define	CONFIG_FS_AUTOFS
#define	CONFIG_FS_HSFS
#define	CONFIG_FS_LOFS
#define	CONFIG_FS_NAMEFS
#define	CONFIG_FS_PCFS
#undef	CONFIG_VM_STATS

#endif
