#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = svcadm/disable
DESC = template.xml stf_description
TCS = svcadm_disable_001 svcadm_disable_002 svcadm_disable_003 \
	svcadm_disable_004 svcadm_disable_005 svcadm_disable_006 \
	svcadm_disable_007 svcadm_disable_008 svcadm_disable_009

include ../../Makefile.test
