MAN = nvlist_add_boolean.3nvpair \
      nvlist_alloc.3nvpair \
      nvlist_lookup_boolean.3nvpair \
      nvlist_lookup_nvpair.3nvpair \
      nvlist_next_nvpair.3nvpair \
      nvlist_remove.3nvpair \
      nvpair_value_byte.3nvpair

MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_boolean_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_boolean_value.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_byte.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_byte_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_double.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_int16.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_int16_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_int32.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_int32_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_int64.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_int64_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_int8.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_int8_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_nvlist.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_nvlist_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_nvpair.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_string.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_string_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_uint16.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_uint16_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_uint32.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_uint32_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_uint64.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_uint64_array.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_uint8.3nvpair
MLINKS+=	nvlist_add_boolean.3nvpair nvlist_add_uint8_array.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nv_alloc_fini.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nv_alloc_init.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nv_alloc_reset.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_dup.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_free.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_lookup_nv_alloc.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_merge.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_pack.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_size.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_unpack.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_xalloc.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_xdup.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_xpack.3nvpair
MLINKS+=	nvlist_alloc.3nvpair nvlist_xunpack.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_boolean_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_boolean_value.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_byte.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_byte_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_double.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_int16.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_int16_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_int32.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_int32_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_int64.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_int64_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_int8.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_int8_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_nvlist.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_nvlist_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_pairs.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_string.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_string_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_uint16.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_uint16_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_uint32.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_uint32_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_uint64.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_uint64_array.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_uint8.3nvpair
MLINKS+=	nvlist_lookup_boolean.3nvpair nvlist_lookup_uint8_array.3nvpair
MLINKS+=	nvlist_lookup_nvpair.3nvpair nvlist_empty.3nvpair
MLINKS+=	nvlist_lookup_nvpair.3nvpair nvlist_exists.3nvpair
MLINKS+=	nvlist_next_nvpair.3nvpair nvpair_name.3nvpair
MLINKS+=	nvlist_next_nvpair.3nvpair nvpair_type.3nvpair
MLINKS+=	nvlist_remove.3nvpair nvlist_remove_all.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_boolean_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_boolean_value.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_byte_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_double.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_int16.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_int16_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_int32.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_int32_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_int64.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_int64_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_int8.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_int8_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_nvlist.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_nvlist_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_string.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_string_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_uint16.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_uint16_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_uint32.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_uint32_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_uint64.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_uint64_array.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_uint8.3nvpair
MLINKS+=	nvpair_value_byte.3nvpair nvpair_value_uint8_array.3nvpair

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
