#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 600
post_user = root
post = cleanup
outputdir = /var/tmp/test_results

[/opt/zfs-tests/tests/stress/replica_stress/mirror_stress_003]
tests = ['mirror_stress_003']

[/opt/zfs-tests/tests/stress/replica_stress/mirror_stress_002]
tests = ['mirror_stress_002']

[/opt/zfs-tests/tests/stress/replica_stress/mirror_stress_005]
tests = ['mirror_stress_005']

[/opt/zfs-tests/tests/stress/replica_stress/mirror_stress_006]
tests = ['mirror_stress_006']

[/opt/zfs-tests/tests/stress/replica_stress/mirror_stress_004]
tests = ['mirror_stress_004']

[/opt/zfs-tests/tests/stress/replica_stress/slog_stress_001]
tests = ['slog_stress_001']

[/opt/zfs-tests/tests/stress/replica_stress/slog_stress_002]
tests = ['slog_stress_002']

[/opt/zfs-tests/tests/stress/replica_stress/raidz_stress_001]
tests = ['raidz_stress_001']

[/opt/zfs-tests/tests/stress/replica_stress/raidz_stress_002]
tests = ['raidz_stress_002']
