MAN = config_admin.3cfgadm 

MLINKS+=	config_admin.3cfgadm config_ap_id_cmp.3cfgadm
MLINKS+=	config_admin.3cfgadm config_change_state.3cfgadm
MLINKS+=	config_admin.3cfgadm config_list.3cfgadm
MLINKS+=	config_admin.3cfgadm config_list_ext.3cfgadm
MLINKS+=	config_admin.3cfgadm config_private_func.3cfgadm
MLINKS+=	config_admin.3cfgadm config_stat.3cfgadm
MLINKS+=	config_admin.3cfgadm config_strerror.3cfgadm
MLINKS+=	config_admin.3cfgadm config_test.3cfgadm
MLINKS+=	config_admin.3cfgadm config_unload_libs.3cfgadm

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
