MAN = ct_ctl_adopt.3contract \
      ct_dev_status_get_dev_state.3contract \
      ct_dev_tmpl_set_aset.3contract \
      ct_event_read.3contract \
      ct_pr_event_get_pid.3contract \
      ct_pr_status_get_param.3contract \
      ct_pr_tmpl_set_transfer.3contract \
      ct_status_read.3contract \
      ct_tmpl_activate.3contract

MLINKS+=	ct_ctl_adopt.3contract ct_ctl_abandon.3contract
MLINKS+=	ct_ctl_adopt.3contract ct_ctl_ack.3contract
MLINKS+=	ct_ctl_adopt.3contract ct_ctl_nack.3contract
MLINKS+=	ct_ctl_adopt.3contract ct_ctl_newct.3contract
MLINKS+=	ct_ctl_adopt.3contract ct_ctl_qack.3contract
MLINKS+=	ct_dev_status_get_dev_state.3contract ct_dev_status_get_aset.3contract
MLINKS+=	ct_dev_status_get_dev_state.3contract ct_dev_status_get_minor.3contract
MLINKS+=	ct_dev_status_get_dev_state.3contract ct_dev_status_get_noneg.3contract
MLINKS+=	ct_dev_tmpl_set_aset.3contract ct_dev_tmpl_clear_noneg.3contract
MLINKS+=	ct_dev_tmpl_set_aset.3contract ct_dev_tmpl_get_aset.3contract
MLINKS+=	ct_dev_tmpl_set_aset.3contract ct_dev_tmpl_get_minor.3contract
MLINKS+=	ct_dev_tmpl_set_aset.3contract ct_dev_tmpl_get_noneg.3contract
MLINKS+=	ct_dev_tmpl_set_aset.3contract ct_dev_tmpl_set_minor.3contract
MLINKS+=	ct_dev_tmpl_set_aset.3contract ct_dev_tmpl_set_noneg.3contract
MLINKS+=	ct_event_read.3contract ct_event_free.3contract
MLINKS+=	ct_event_read.3contract ct_event_get_ctid.3contract
MLINKS+=	ct_event_read.3contract ct_event_get_evid.3contract
MLINKS+=	ct_event_read.3contract ct_event_get_flags.3contract
MLINKS+=	ct_event_read.3contract ct_event_get_nevid.3contract
MLINKS+=	ct_event_read.3contract ct_event_get_newct.3contract
MLINKS+=	ct_event_read.3contract ct_event_get_type.3contract
MLINKS+=	ct_event_read.3contract ct_event_read_critical.3contract
MLINKS+=	ct_event_read.3contract ct_event_reliable.3contract
MLINKS+=	ct_event_read.3contract ct_event_reset.3contract
MLINKS+=	ct_pr_event_get_pid.3contract ct_pr_event_get_exitstatus.3contract
MLINKS+=	ct_pr_event_get_pid.3contract ct_pr_event_get_gcorefile.3contract
MLINKS+=	ct_pr_event_get_pid.3contract ct_pr_event_get_pcorefile.3contract
MLINKS+=	ct_pr_event_get_pid.3contract ct_pr_event_get_ppid.3contract
MLINKS+=	ct_pr_event_get_pid.3contract ct_pr_event_get_sender.3contract
MLINKS+=	ct_pr_event_get_pid.3contract ct_pr_event_get_senderct.3contract
MLINKS+=	ct_pr_event_get_pid.3contract ct_pr_event_get_signal.3contract
MLINKS+=	ct_pr_event_get_pid.3contract ct_pr_event_get_zcorefile.3contract
MLINKS+=	ct_pr_status_get_param.3contract ct_pr_status_get_contracts.3contract
MLINKS+=	ct_pr_status_get_param.3contract ct_pr_status_get_fatal.3contract
MLINKS+=	ct_pr_status_get_param.3contract ct_pr_status_get_members.3contract
MLINKS+=	ct_pr_status_get_param.3contract ct_pr_status_get_svc_aux.3contract
MLINKS+=	ct_pr_status_get_param.3contract ct_pr_status_get_svc_creator.3contract
MLINKS+=	ct_pr_status_get_param.3contract ct_pr_status_get_svc_ctid.3contract
MLINKS+=	ct_pr_status_get_param.3contract ct_pr_status_get_svc_fmri.3contract
MLINKS+=	ct_pr_tmpl_set_transfer.3contract ct_pr_tmpl_get_fatal.3contract
MLINKS+=	ct_pr_tmpl_set_transfer.3contract ct_pr_tmpl_get_param.3contract
MLINKS+=	ct_pr_tmpl_set_transfer.3contract ct_pr_tmpl_get_svc_aux.3contract
MLINKS+=	ct_pr_tmpl_set_transfer.3contract ct_pr_tmpl_get_svc_fmri.3contract
MLINKS+=	ct_pr_tmpl_set_transfer.3contract ct_pr_tmpl_get_transfer.3contract
MLINKS+=	ct_pr_tmpl_set_transfer.3contract ct_pr_tmpl_set_fatal.3contract
MLINKS+=	ct_pr_tmpl_set_transfer.3contract ct_pr_tmpl_set_param.3contract
MLINKS+=	ct_pr_tmpl_set_transfer.3contract ct_pr_tmpl_set_svc_aux.3contract
MLINKS+=	ct_pr_tmpl_set_transfer.3contract ct_pr_tmpl_set_svc_fmri.3contract
MLINKS+=	ct_status_read.3contract ct_status_free.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_cookie.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_critical.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_holder.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_id.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_informative.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_nevents.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_nevid.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_ntime.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_qtime.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_state.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_type.3contract
MLINKS+=	ct_status_read.3contract ct_status_get_zoneid.3contract
MLINKS+=	ct_tmpl_activate.3contract ct_tmpl_clear.3contract
MLINKS+=	ct_tmpl_activate.3contract ct_tmpl_create.3contract
MLINKS+=	ct_tmpl_activate.3contract ct_tmpl_get_cookie.3contract
MLINKS+=	ct_tmpl_activate.3contract ct_tmpl_get_critical.3contract
MLINKS+=	ct_tmpl_activate.3contract ct_tmpl_get_informative.3contract
MLINKS+=	ct_tmpl_activate.3contract ct_tmpl_set_cookie.3contract
MLINKS+=	ct_tmpl_activate.3contract ct_tmpl_set_critical.3contract
MLINKS+=	ct_tmpl_activate.3contract ct_tmpl_set_informative.3contract

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
