#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = num_attrs
SHRSRC = data.cfg NUM_ATTRS.flist README
TCLSRC = num_attrs_neg10 num_attrs_neg17 num_attrs_neg18 num_attrs_neg21 \
	num_attrs_neg25 num_attrs_neg28 num_attrs_pos00 num_attrs_pos01 \
	num_attrs_pos02 num_attrs_pos03 num_attrs_pos04 num_attrs_pos05 \
	num_attrs_pos06 num_attrs_pos07 num_attrs_pos08 num_attrs_pos09 \
	num_attrs_pos10 num_attrs_pos11 num_attrs_pos12 num_attrs_pos13 \
	num_attrs_pos14 num_attrs_pos15 num_attrs_pos16 num_attrs_pos17 \
	num_attrs_pos18 num_attrs_pos19 num_attrs_pos20 num_attrs_pos22 \
	num_attrs_pos23 num_attrs_pos24 num_attrs_pos26 num_attrs_pos27 \
	num_attrs_pos28 num_attrs_pos29 num_attrs_pos30
TCS = ck_fattr quota_query01 runtests

include ../Makefile.test
