#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = svccfg/apply
DESC = apply_001_manifest.xml apply_001_profile.xml \
	apply_007_profile.xml stf_description

TCS = apply_001 apply_002 apply_003 apply_004 apply_005 \
	apply_006 apply_007 apply_008 apply_009_010 \
	svccfg_apply_setup

include ../../Makefile.test
