#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = basic_ops/open
SHRSRC = OPEN.env OPEN.flist
TCS = runtests
TCLSRC = open_neg01 open_neg02 open_neg03 open_neg04 open_neg05 \
	open_neg06 open_neg07 open_neg08 open_neg09 open_neg10 \
	open_pos01 open_pos02 open_pos10 OPEN_proc

include ../../Makefile.test
