#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2016 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = named_attrs/cmds
SHRSRC = ATTRCMDS.flist
TCS = attrcmds_funcs attrcmds_neg04 attrcmds_neg05 attrcmds_neg08 \
	attrcmds_pos01 attrcmds_pos02 attrcmds_pos03 attrcmds_pos06 \
	attrcmds_pos07 runtests
TCLSRC =

include ../../Makefile.test
