MAN = uuid_clear.3uuid 

MLINKS+=	uuid_clear.3uuid uuid_compare.3uuid
MLINKS+=	uuid_clear.3uuid uuid_copy.3uuid
MLINKS+=	uuid_clear.3uuid uuid_generate.3uuid
MLINKS+=	uuid_clear.3uuid uuid_generate_random.3uuid
MLINKS+=	uuid_clear.3uuid uuid_generate_time.3uuid
MLINKS+=	uuid_clear.3uuid uuid_is_null.3uuid
MLINKS+=	uuid_clear.3uuid uuid_parse.3uuid
MLINKS+=	uuid_clear.3uuid uuid_time.3uuid
MLINKS+=	uuid_clear.3uuid uuid_unparse.3uuid
MLINKS+=	uuid_clear.3uuid uuid_unparse_lower.3uuid
MLINKS+=	uuid_clear.3uuid uuid_unparse_upper.3uuid

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
