/* GENERATED FILE - DO NOT EDIT */

#ifndef	_SYS_CFGPARAM_H
#define	_SYS_CFGPARAM_H

#define	CONFIG_MACH sparc
#define	CONFIG_MACH32 sparcv7
#define	CONFIG_MACH64 sparcv9
#undef	CONFIG_BUILD_KMOD_32
#define	CONFIG_BUILD_KMOD_64
#undef	CONFIG_LINUX_CORE_SUPPORT
#define	CONFIG_SMB_PRINTING
#define	CONFIG_LOFI
#define	CONFIG_RAMDISK
#define	CONFIG_RANDOM
#undef	CONFIG_VIRTIO
#define	CONFIG_E1000G
#undef	CONFIG_I40E
#define	CONFIG_IGB
#define	CONFIG_IXGBE
#undef	CONFIG_NGE
#define	CONFIG_NXGE
#undef	CONFIG_SFXGE
#undef	CONFIG_VIRTIO_NET
#undef	CONFIG_IWN
#define	CONFIG_FS_AUTOFS
#define	CONFIG_FS_HSFS
#define	CONFIG_FS_LOFS
#define	CONFIG_FS_NAMEFS
#define	CONFIG_FS_PCFS
#undef	CONFIG_VM_STATS

#endif
