#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TPLDIR = svccfg/templates
TEST = $(TPLDIR)/pg_pattern_common_name
DESC = config.env pg_pattern_common_name.xml pg_pattern_loctext.xml \
	stf_description
TCS = pg_pattern_common_name_001 pg_pattern_common_name_002 \
	pg_pattern_common_name_003 pg_pattern_common_name_004 \
	pg_pattern_common_name_005 pg_pattern_common_name_006 \
	pg_pattern_common_name_007 pg_pattern_common_name_008 \
	pg_pattern_common_name_009 pg_pattern_common_name_010 \
	pg_pattern_common_name_011

include ../../../Makefile.test
