#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#
include $(SRC)/Makefile.master

TEST = svcadm/enable
DESC = template.xml stf_description
TCS = svcadm_enable_001 svcadm_enable_002 svcadm_enable_003 \
	svcadm_enable_004 svcadm_enable_005 svcadm_enable_006 \
	svcadm_enable_007 svcadm_enable_008 svcadm_enable_009 \
	svcadm_enable_010 svcadm_enable_011 svcadm_enable_012 \
	svcadm_enable_013 svcadm_enable_014

include ../../Makefile.test
