MAN = Intro.2 \
      __sparc_utrap_install.2 \
      _lwp_cond_signal.2 \
      _lwp_cond_wait.2 \
      _lwp_info.2 \
      _lwp_kill.2 \
      _lwp_mutex_lock.2 \
      _lwp_self.2 \
      _lwp_sema_wait.2 \
      _lwp_suspend.2 \
      access.2 \
      acct.2 \
      acl.2 \
      adjtime.2 \
      alarm.2 \
      audit.2 \
      auditon.2 \
      brk.2 \
      chdir.2 \
      chmod.2 \
      chown.2 \
      chroot.2 \
      close.2 \
      creat.2 \
      dup.2 \
      exec.2 \
      exit.2 \
      fcntl.2 \
      fork.2 \
      fpathconf.2 \
      getacct.2 \
      getaudit.2 \
      getauid.2 \
      getcontext.2 \
      getdents.2 \
      getgroups.2 \
      getisax.2 \
      getitimer.2 \
      getmsg.2 \
      getpflags.2 \
      getpid.2 \
      getppriv.2 \
      getrlimit.2 \
      getsid.2 \
      getuid.2 \
      getustack.2 \
      ioctl.2 \
      issetugid.2 \
      kill.2 \
      link.2 \
      llseek.2 \
      lseek.2 \
      memcntl.2 \
      meminfo.2 \
      mincore.2 \
      mkdir.2 \
      mknod.2 \
      mmap.2 \
      mmapobj.2 \
      mount.2 \
      mprotect.2 \
      msgctl.2 \
      msgget.2 \
      msgids.2 \
      msgrcv.2 \
      msgsnap.2 \
      msgsnd.2 \
      munmap.2 \
      nice.2 \
      ntp_adjtime.2 \
      ntp_gettime.2 \
      open.2 \
      p_online.2 \
      pause.2 \
      pcsample.2 \
      pipe.2 \
      poll.2 \
      priocntl.2 \
      priocntlset.2 \
      processor_bind.2 \
      processor_info.2 \
      profil.2 \
      pset_bind.2 \
      pset_create.2 \
      pset_info.2 \
      pset_list.2 \
      pset_setattr.2 \
      putmsg.2 \
      read.2 \
      readlink.2 \
      rename.2 \
      resolvepath.2 \
      rmdir.2 \
      semctl.2 \
      semget.2 \
      semids.2 \
      semop.2 \
      setpgid.2 \
      setpgrp.2 \
      setrctl.2 \
      setregid.2 \
      setreuid.2 \
      setsid.2 \
      settaskid.2 \
      setuid.2 \
      shmctl.2 \
      shmget.2 \
      shmids.2 \
      shmop.2 \
      sigaction.2 \
      sigaltstack.2 \
      sigpending.2 \
      sigprocmask.2 \
      sigsend.2 \
      sigsuspend.2 \
      sigwait.2 \
      stat.2 \
      statvfs.2 \
      stime.2 \
      swapctl.2 \
      symlink.2 \
      sync.2 \
      sysfs.2 \
      sysinfo.2 \
      time.2 \
      times.2 \
      uadmin.2 \
      ulimit.2 \
      umask.2 \
      umount.2 \
      uname.2 \
      unlink.2 \
      ustat.2 \
      utime.2 \
      utimes.2 \
      uucopy.2 \
      vfork.2 \
      vhangup.2 \
      waitid.2 \
      write.2 \
      yield.2

MLINKS+=	Intro.2 intro.2
MLINKS+=	_lwp_cond_signal.2 _lwp_cond_broadcast.2
MLINKS+=	_lwp_cond_wait.2 _lwp_cond_reltimedwait.2
MLINKS+=	_lwp_cond_wait.2 _lwp_cond_timedwait.2
MLINKS+=	_lwp_mutex_lock.2 _lwp_mutex_trylock.2
MLINKS+=	_lwp_mutex_lock.2 _lwp_mutex_unlock.2
MLINKS+=	_lwp_sema_wait.2 _lwp_sema_init.2
MLINKS+=	_lwp_sema_wait.2 _lwp_sema_post.2
MLINKS+=	_lwp_sema_wait.2 _lwp_sema_trywait.2
MLINKS+=	_lwp_suspend.2 _lwp_continue.2
MLINKS+=	access.2 faccessat.2
MLINKS+=	acl.2 facl.2
MLINKS+=	brk.2 sbrk.2
MLINKS+=	chdir.2 fchdir.2
MLINKS+=	chmod.2 fchmod.2
MLINKS+=	chmod.2 fchmodat.2
MLINKS+=	chown.2 fchown.2
MLINKS+=	chown.2 fchownat.2
MLINKS+=	chown.2 lchown.2
MLINKS+=	chroot.2 fchroot.2
MLINKS+=	exec.2 execl.2
MLINKS+=	exec.2 execle.2
MLINKS+=	exec.2 execlp.2
MLINKS+=	exec.2 execv.2
MLINKS+=	exec.2 execve.2
MLINKS+=	exec.2 execvp.2
MLINKS+=	exit.2 _Exit.2
MLINKS+=	exit.2 _exit.2
MLINKS+=	fork.2 fork1.2
MLINKS+=	fork.2 forkall.2
MLINKS+=	fork.2 forkallx.2
MLINKS+=	fork.2 forkx.2
MLINKS+=	fpathconf.2 pathconf.2
MLINKS+=	getacct.2 putacct.2
MLINKS+=	getacct.2 wracct.2
MLINKS+=	getaudit.2 getaudit_addr.2
MLINKS+=	getaudit.2 setaudit.2
MLINKS+=	getaudit.2 setaudit_addr.2
MLINKS+=	getauid.2 setauid.2
MLINKS+=	getcontext.2 setcontext.2
MLINKS+=	getgroups.2 setgroups.2
MLINKS+=	getitimer.2 setitimer.2
MLINKS+=	getmsg.2 getpmsg.2
MLINKS+=	getpflags.2 setpflags.2
MLINKS+=	getpid.2 getpgid.2
MLINKS+=	getpid.2 getpgrp.2
MLINKS+=	getpid.2 getppid.2
MLINKS+=	getppriv.2 setppriv.2
MLINKS+=	getrlimit.2 setrlimit.2
MLINKS+=	getuid.2 getegid.2
MLINKS+=	getuid.2 geteuid.2
MLINKS+=	getuid.2 getgid.2
MLINKS+=	getustack.2 setustack.2
MLINKS+=	link.2 linkat.2
MLINKS+=	mkdir.2 mkdirat.2
MLINKS+=	mknod.2 mknodat.2
MLINKS+=	open.2 openat.2
MLINKS+=	pipe.2 pipe2.2
MLINKS+=	poll.2 ppoll.2
MLINKS+=	pset_create.2 pset_assign.2
MLINKS+=	pset_create.2 pset_destroy.2
MLINKS+=	pset_setattr.2 pset_getattr.2
MLINKS+=	putmsg.2 putpmsg.2
MLINKS+=	read.2 pread.2
MLINKS+=	read.2 readv.2
MLINKS+=	read.2 preadv.2
MLINKS+=	readlink.2 readlinkat.2
MLINKS+=	rename.2 renameat.2
MLINKS+=	semop.2 semtimedop.2
MLINKS+=	setrctl.2 getrctl.2
MLINKS+=	settaskid.2 getprojid.2
MLINKS+=	settaskid.2 gettaskid.2
MLINKS+=	setuid.2 setegid.2
MLINKS+=	setuid.2 seteuid.2
MLINKS+=	setuid.2 setgid.2
MLINKS+=	shmop.2 shmat.2
MLINKS+=	shmop.2 shmdt.2
MLINKS+=	sigsend.2 sigsendset.2
MLINKS+=	symlink.2 symlinkat.2
MLINKS+=	stat.2 fstat.2
MLINKS+=	stat.2 fstatat.2
MLINKS+=	stat.2 lstat.2
MLINKS+=	statvfs.2 fstatvfs.2
MLINKS+=	umount.2 umount2.2
MLINKS+=	unlink.2 unlinkat.2
MLINKS+=	utimes.2 futimens.2
MLINKS+=	utimes.2 futimesat.2
MLINKS+=	utimes.2 utimensat.2
MLINKS+=	vfork.2 vforkx.2
MLINKS+=	write.2 pwrite.2
MLINKS+=	write.2 writev.2
MLINKS+=	write.2 pwritev.2

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
